import ArithS.Necessitation.Prologue

/-!
# ArithS.Necessitation.NumIdRows — the pin's rows (GENERATED by `arith/scripts/gen_numid.py`)

The rows `Pin.lean` needs beyond the prologue table (`DESIGN_fragments.md` §7.1 steps 1–4): the EXISTING
library rows `instBIntro`, `congSubstArg`, `bnumZeroCert`, `bnumOneCert`, `bnumEvenCert` (their `Lib`,
`quote_row_` and `inst_` blocks are in `Lib/Frag.lean` and `RowInstB.lean`; none of them was in any table) and
ONE new row `bnumOddOfEven` — the odd bit-step `1 ≤ m → s = bnum (2m) → u = s ^+ 𝟏 → u = bnum (2m + 1)`
through the even numeral (`bnumOddCert` has 12 witnesses and 12 antecedents, above the cap `M = 9` every
`ListOK` of the pin runs at; with `bnumEvenCert` (9 witnesses, cap 9) it covers every bit). The extra rows
`numIdExtraRows` sit at `nIdx_<row> = proRowCount + k` — APPEND-ONLY after the prologue table and SYMBOLIC
in `proRowCount`, so a prologue row appended concurrently moves only the base; the piece table `numIdPieces`
extends `proPieces` entrywise with a zero pad over the certification tail (whose rows have no pieces, being
used only through `reidxL`); per row `nmk_<row>`, `ntag_<row>`, `nok_<row>` — the applicability lemmas take
the table readings at the row's index as EXPLICIT hypotheses; `NumIdTable` lives in `Pin.lean`.
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open PeanoMinus ISigma0 ISigma1
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 0. The new library row (`Lib`) -/

section numIdLib

/-- `1 ≤ m → s = bnum (2 * m) → u = s ^+ 𝟏 (as `func`/`∷` facts) → u = bnum (2 * m + 1)` — the odd bit-step THROUGH the even numeral (`bnumOddCert` has 12 witnesses, above the cap `M = 9`). -/
noncomputable def bnumOddOfEvenB : ArithmeticSemisentence 6 :=
  “u x x' s one m. 1 ≤ m → !bnumGraph s (2 * m) → !qqFuncDef one 0 (0 + 1) 0 → !adjoinDef x' one 0 → !adjoinDef x s x' → !qqFuncDef u (0 + 1 + 1) 0 x → !bnumGraph u ((2 * m) + 1)”
noncomputable def bnumOddOfEven : ArithmeticSentence := ∀¹* bnumOddOfEvenB
lemma models_bnumOddOfEven : V↓[ℒₒᵣ] ⊧ bnumOddOfEven ↔ ∀ u x x' s one m : V, (1 : V) ≤ m → s = bnum ((2 : V) * m) → one = ^func (0 : V) ((0 : V) + 1) (0 : V) → x' = one ∷ (0 : V) → x = s ∷ x' → u = ^func ((0 : V) + 1 + 1) (0 : V) x → u = bnum (((2 : V) * m) + (1 : V)) := by
  simp [bnumOddOfEven, bnumOddOfEvenB, models_iff, Matrix.vecForall_iff, bnum.defined.iff]
theorem pa_proves_bnumOddOfEven : 𝗣𝗔 ⊢ bnumOddOfEven :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_bnumOddOfEven.mpr fun _ _ _ _ _ _ h₁ h₂ h₃ h₄ h₅ h₆ ↦ by subst_vars; rw [bnum_two_mul_add_one h₁, ← bnum_two_mul h₁]; simp only [qqAdd, coe_addIndex_eq, Arithmetic.one, qqFuncN_eq_qqFunc, qqFunc_absolute, coe_oneIndex_eq, Nat.cast_zero, zero_add, one_add_one_eq_two]
theorem lib_bnumOddOfEven : Lib bnumOddOfEven := Lib.of_pa pa_proves_bnumOddOfEven

end numIdLib

/-! ## 1. Its `quote_row_`/`inst_` block (the `RowInstB` template) -/

section numIdRowInst

/-! ### `bnumOddOfEven` — `“u x x' s one m. …”`, `m = 6` -/

noncomputable def row_bnumOddOfEven_as : List V := [subst LAct (listToVec [(𝟏 : V), bv 5]) Ple, subst LAct (listToVec [bv 3, (((𝟏 : V) ^+ (𝟏 : V)) ^* bv 5)]) Pbnum, subst LAct (listToVec [bv 4, (𝟎 : V), cT 1, (𝟎 : V)]) Pfunc, subst LAct (listToVec [bv 2, bv 4, (𝟎 : V)]) Padjoin, subst LAct (listToVec [bv 1, bv 3, bv 2]) Padjoin, subst LAct (listToVec [bv 0, cT 2, (𝟎 : V), bv 1]) Pfunc]
noncomputable def row_bnumOddOfEven_c : V := subst LAct (listToVec [bv 0, ((((𝟏 : V) ^+ (𝟏 : V)) ^* bv 5) ^+ (𝟏 : V))]) Pbnum

theorem quote_row_bnumOddOfEven : (⌜Semiformula.lMap emb bnumOddOfEvenB⌝ : V) = impChain LAct row_bnumOddOfEven_as row_bnumOddOfEven_c := by
  unfold bnumOddOfEvenB row_bnumOddOfEven_as row_bnumOddOfEven_c Padjoin Pbnum Pfunc Ple leS
  all_goals row_shapeB

lemma isSemiformula_bnumOddOfEven_as : ∀ A ∈ row_bnumOddOfEven_as, IsSemiformula LAct ((6 : ℕ) : V) A := by
  unfold row_bnumOddOfEven_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pbnum _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pfunc _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Padjoin _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Padjoin _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pfunc _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩⟩⟩⟩)
lemma isSemiformula_bnumOddOfEven_c : IsSemiformula LAct ((6 : ℕ) : V) row_bnumOddOfEven_c := by
  unfold row_bnumOddOfEven_c
  exact isSemiformula_substRow isSemiformula_Pbnum _ (by rfl) (by row_entriesB)

/-- `bnumOddOfEven` at the witnesses `[wm, wone, ws, wxp, wx, wu]` (the DSL variables right-to-left). -/
lemma inst_bnumOddOfEven {wm wone ws wxp wx wu : V} (hwm : IsSemiterm LAct 0 wm) (hwone : IsSemiterm LAct 0 wone) (hws : IsSemiterm LAct 0 ws) (hwxp : IsSemiterm LAct 0 wxp) (hwx : IsSemiterm LAct 0 wx) (hwu : IsSemiterm LAct 0 wu) :
    row_bnumOddOfEven_as.map (instOuter LAct [wm, wone, ws, wxp, wx, wu]) = [leFact (𝟏 : V) wm, bnumFact ws (((𝟏 : V) ^+ (𝟏 : V)) ^* wm), funcFact wone (𝟎 : V) (cT 1) (𝟎 : V), adjFact wxp wone (𝟎 : V), adjFact wx ws wxp, funcFact wu (cT 2) (𝟎 : V) wx] ∧
    instOuter LAct [wm, wone, ws, wxp, wx, wu] row_bnumOddOfEven_c = bnumFact wu ((((𝟏 : V) ^+ (𝟏 : V)) ^* wm) ^+ (𝟏 : V)) := by
  have hes : ∀ e ∈ ([wm, wone, ws, wxp, wx, wu] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwm, List.forall_mem_cons.mpr ⟨hwone, List.forall_mem_cons.mpr ⟨hws, List.forall_mem_cons.mpr ⟨hwxp, List.forall_mem_cons.mpr ⟨hwx, List.forall_mem_cons.mpr ⟨hwu, List.forall_mem_nil _⟩⟩⟩⟩⟩⟩)
  unfold row_bnumOddOfEven_as row_bnumOddOfEven_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pbnum (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pfunc (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Padjoin (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Padjoin (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pfunc (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pbnum (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

end numIdRowInst

/-! ## 2. The extra rows at `proRowCount + k`, the piece table, the applicability lemmas -/

section numIdRowsTable

def nIdx_instBIntro : ℕ := proRowCount + 0
def nIdx_congSubstArg : ℕ := proRowCount + 1
def nIdx_bnumZeroCert : ℕ := proRowCount + 2
def nIdx_bnumOneCert : ℕ := proRowCount + 3
def nIdx_bnumEvenCert : ℕ := proRowCount + 4
def nIdx_bnumOddOfEven : ℕ := proRowCount + 5
def numIdExtraRowCount : ℕ := 6

/-- The extra rows at `proRowCount + k`, in index order (append-only). -/
noncomputable def numIdExtraRows : List WRow := [
  ⟨5, instBIntroB, lib_instBIntro⟩,
  ⟨4, congSubstArgB, lib_congSubstArg⟩,
  ⟨1, bnumZeroCertB, lib_bnumZeroCert⟩,
  ⟨1, bnumOneCertB, lib_bnumOneCert⟩,
  ⟨9, bnumEvenCertB, lib_bnumEvenCert⟩,
  ⟨6, bnumOddOfEvenB, lib_bnumOddOfEven⟩
]

lemma numIdExtraRows_length : numIdExtraRows.length = numIdExtraRowCount := rfl

/-- **The pin table's rows**: the prologue rows, then the pin's rows. -/
noncomputable def numIdRows : List WRow := proRows ++ numIdExtraRows
def numIdRowCount : ℕ := proRowCount + numIdExtraRowCount
lemma numIdRows_length : numIdRows.length = numIdRowCount := by
  simp only [numIdRows, List.length_append, proRows_length, numIdExtraRows_length, numIdRowCount]

/-! ### The piece table -/

noncomputable def npiece_instBIntro : V := ⟪(0 : V), vecOf row_instBIntro_as, row_instBIntro_c⟫
noncomputable def npiece_congSubstArg : V := ⟪(0 : V), vecOf row_congSubstArg_as, row_congSubstArg_c⟫
noncomputable def npiece_bnumZeroCert : V := ⟪(0 : V), vecOf row_bnumZeroCert_as, row_bnumZeroCert_c⟫
noncomputable def npiece_bnumOneCert : V := ⟪(0 : V), vecOf row_bnumOneCert_as, row_bnumOneCert_c⟫
noncomputable def npiece_bnumEvenCert : V := ⟪(0 : V), vecOf row_bnumEvenCert_as, row_bnumEvenCert_c⟫
noncomputable def npiece_bnumOddOfEven : V := ⟪(0 : V), vecOf row_bnumOddOfEven_as, row_bnumOddOfEven_c⟫

noncomputable def numIdExtraPieceList : List V := [
  npiece_instBIntro,
  npiece_congSubstArg,
  npiece_bnumZeroCert,
  npiece_bnumOneCert,
  npiece_bnumEvenCert,
  npiece_bnumOddOfEven
]

/-- A zero pad over the certification tail (whose rows are used only through re-indexed lists and have no pieces). -/
noncomputable def numIdPadPieceList : List V := List.replicate (certRowCount - walkRowCount) (0 : V)

/-- **The piece table of the pin**: the prologue's pieces, the pad, then the extra rows' pieces. -/
noncomputable def numIdPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList)

lemma numIdPieces_nth_lt (i : ℕ) (hi : i < proBase) : (numIdPieces : V).[(i : V)] = (proPieces : V).[(i : V)] := by
  unfold numIdPieces proPieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList : List V).length = numIdRowCount from rfl]
    exact lt_of_lt_of_le hi (by simp only [numIdRowCount, proRowCount]; omega)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length = proBase from rfl]; exact hi
  have h3 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList : List V).length := by
    rw [List.length_append]; exact lt_of_lt_of_le h2 (Nat.le_add_right _ _)
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact (List.getElem_append_left h3).trans (List.getElem_append_left h2)

/-- A prologue step read from the pin's pieces is the prologue's step. -/
lemma mkStep_numIdPieces_lt (i : ℕ) (hi : i < proBase) (ev : V) :
    mkStep numIdPieces (i : V) ev = mkStep proPieces (i : V) ev := by
  rw [mkStep, mkStep, numIdPieces_nth_lt i hi]

lemma numIdPieces_instBIntro : (numIdPieces : V).[((nIdx_instBIntro : ℕ) : V)] = npiece_instBIntro := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_instBIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_instBIntro (ev : V) :
    mkStep numIdPieces ((nIdx_instBIntro : ℕ) : V) ev = sUseHorn ((nIdx_instBIntro : ℕ) : V) ev (vecOf row_instBIntro_as) row_instBIntro_c := by
  rw [mkStep, numIdPieces_instBIntro]
  simp [npiece_instBIntro, sUseHorn]

lemma ntag_instBIntro {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_instBIntro : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_instBIntro]; simp

lemma numIdPieces_congSubstArg : (numIdPieces : V).[((nIdx_congSubstArg : ℕ) : V)] = npiece_congSubstArg := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_congSubstArg (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_congSubstArg (ev : V) :
    mkStep numIdPieces ((nIdx_congSubstArg : ℕ) : V) ev = sUseHorn ((nIdx_congSubstArg : ℕ) : V) ev (vecOf row_congSubstArg_as) row_congSubstArg_c := by
  rw [mkStep, numIdPieces_congSubstArg]
  simp [npiece_congSubstArg, sUseHorn]

lemma ntag_congSubstArg {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_congSubstArg : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_congSubstArg]; simp

lemma numIdPieces_bnumZeroCert : (numIdPieces : V).[((nIdx_bnumZeroCert : ℕ) : V)] = npiece_bnumZeroCert := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_bnumZeroCert (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_bnumZeroCert (ev : V) :
    mkStep numIdPieces ((nIdx_bnumZeroCert : ℕ) : V) ev = sUseHorn ((nIdx_bnumZeroCert : ℕ) : V) ev (vecOf row_bnumZeroCert_as) row_bnumZeroCert_c := by
  rw [mkStep, numIdPieces_bnumZeroCert]
  simp [npiece_bnumZeroCert, sUseHorn]

lemma ntag_bnumZeroCert {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_bnumZeroCert : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_bnumZeroCert]; simp

lemma numIdPieces_bnumOneCert : (numIdPieces : V).[((nIdx_bnumOneCert : ℕ) : V)] = npiece_bnumOneCert := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_bnumOneCert (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_bnumOneCert (ev : V) :
    mkStep numIdPieces ((nIdx_bnumOneCert : ℕ) : V) ev = sUseHorn ((nIdx_bnumOneCert : ℕ) : V) ev (vecOf row_bnumOneCert_as) row_bnumOneCert_c := by
  rw [mkStep, numIdPieces_bnumOneCert]
  simp [npiece_bnumOneCert, sUseHorn]

lemma ntag_bnumOneCert {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_bnumOneCert : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_bnumOneCert]; simp

lemma numIdPieces_bnumEvenCert : (numIdPieces : V).[((nIdx_bnumEvenCert : ℕ) : V)] = npiece_bnumEvenCert := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_bnumEvenCert (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_bnumEvenCert (ev : V) :
    mkStep numIdPieces ((nIdx_bnumEvenCert : ℕ) : V) ev = sUseHorn ((nIdx_bnumEvenCert : ℕ) : V) ev (vecOf row_bnumEvenCert_as) row_bnumEvenCert_c := by
  rw [mkStep, numIdPieces_bnumEvenCert]
  simp [npiece_bnumEvenCert, sUseHorn]

lemma ntag_bnumEvenCert {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_bnumEvenCert : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_bnumEvenCert]; simp

lemma numIdPieces_bnumOddOfEven : (numIdPieces : V).[((nIdx_bnumOddOfEven : ℕ) : V)] = npiece_bnumOddOfEven := by
  unfold numIdPieces
  rw [nth_vecOf _ nIdx_bnumOddOfEven (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma nmk_bnumOddOfEven (ev : V) :
    mkStep numIdPieces ((nIdx_bnumOddOfEven : ℕ) : V) ev = sUseHorn ((nIdx_bnumOddOfEven : ℕ) : V) ev (vecOf row_bnumOddOfEven_as) row_bnumOddOfEven_c := by
  rw [mkStep, numIdPieces_bnumOddOfEven]
  simp [npiece_bnumOddOfEven, sUseHorn]

lemma ntag_bnumOddOfEven {W : V} (hWp : W = numIdPieces) (ev : V) : sTag (mkStep W ((nIdx_bnumOddOfEven : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [nmk_bnumOddOfEven]; simp

/-! ### The per-row applicability lemmas `nok_<row>` (against explicit table readings) -/

/-- Row `instBIntro` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_instBIntro {tbl N E Γ W : V} {wn wk wt wv wg : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_instBIntro : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_instBIntro : ℕ) : V)] = ((5 : ℕ) : V) ∧
      rowB tbl.[((nIdx_instBIntro : ℕ) : V)] = impChainV LAct (vecOf row_instBIntro_as) row_instBIntro_c)
    (hΓ : IsFormulaSet LAct Γ) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hwk : IsSemiterm LAct 0 wk) (hEwk : termLen LAct wk ≤ E) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hwv : IsSemiterm LAct 0 wv) (hEwv : termLen LAct wv ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hmem0 : neg LAct (bnumFact wt wk) ∈ Γ) (hmem1 : neg LAct (adjFact wv wt (𝟎 : V)) ∈ Γ) (hmem2 : neg LAct (substFact wg wv wn) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((nIdx_instBIntro : ℕ) : V) ?[wn, wk, wt, wv, wg]) ∧ sTag (mkStep W ((nIdx_instBIntro : ℕ) : V) ?[wn, wk, wt, wv, wg]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_instBIntro : ℕ) : V) ?[wn, wk, wt, wv, wg]) = insert (neg LAct (instBFact wg wn wk)) Γ := by
  subst hWp
  have hstep := nmk_instBIntro (V := V) ?[wn, wk, wt, wv, wg]
  have hes : ∀ e ∈ [wn, wk, wt, wv, wg], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_cons.mpr ⟨⟨hwk, hEwk⟩, List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hwv, hEwv⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_nil _⟩⟩⟩⟩⟩
  have hinst := inst_instBIntro hwn hwk hwt hwv hwg
  rw [hstep, show (?[wn, wk, wt, wv, wg] : V) = vecOf [wn, wk, wt, wv, wg] from rfl]
  refine ⟨stepOK_useHorn htbl [wn, wk, wt, wv, wg] row_instBIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 5 ≤ 8))
    (by rw [show row_instBIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wn, wk, wt, wv, wg] row_instBIntro_as isSemiformula_instBIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `congSubstArg` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_congSubstArg {tbl N E Γ W : V} {wy ww wn wnp : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_congSubstArg : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_congSubstArg : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((nIdx_congSubstArg : ℕ) : V)] = impChainV LAct (vecOf row_congSubstArg_as) row_congSubstArg_c)
    (hΓ : IsFormulaSet LAct Γ) (hwy : IsSemiterm LAct 0 wy) (hEwy : termLen LAct wy ≤ E) (hww : IsSemiterm LAct 0 ww) (hEww : termLen LAct ww ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hwnp : IsSemiterm LAct 0 wnp) (hEwnp : termLen LAct wnp ≤ E) (hmem0 : neg LAct (eqFactB wn wnp) ∈ Γ) (hmem1 : neg LAct (substFact wy ww wn) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((nIdx_congSubstArg : ℕ) : V) ?[wy, ww, wn, wnp]) ∧ sTag (mkStep W ((nIdx_congSubstArg : ℕ) : V) ?[wy, ww, wn, wnp]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_congSubstArg : ℕ) : V) ?[wy, ww, wn, wnp]) = insert (neg LAct (substFact wy ww wnp)) Γ := by
  subst hWp
  have hstep := nmk_congSubstArg (V := V) ?[wy, ww, wn, wnp]
  have hes : ∀ e ∈ [wy, ww, wn, wnp], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwy, hEwy⟩, List.forall_mem_cons.mpr ⟨⟨hww, hEww⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_cons.mpr ⟨⟨hwnp, hEwnp⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_congSubstArg hwy hww hwn hwnp
  rw [hstep, show (?[wy, ww, wn, wnp] : V) = vecOf [wy, ww, wn, wnp] from rfl]
  refine ⟨stepOK_useHorn htbl [wy, ww, wn, wnp] row_congSubstArg_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_congSubstArg_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wy, ww, wn, wnp] row_congSubstArg_as isSemiformula_congSubstArg_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `bnumZeroCert` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_bnumZeroCert {tbl N E Γ W : V} {wt : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_bnumZeroCert : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_bnumZeroCert : ℕ) : V)] = ((1 : ℕ) : V) ∧
      rowB tbl.[((nIdx_bnumZeroCert : ℕ) : V)] = impChainV LAct (vecOf row_bnumZeroCert_as) row_bnumZeroCert_c)
    (hΓ : IsFormulaSet LAct Γ) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hmem0 : neg LAct (funcFact wt (𝟎 : V) (𝟎 : V) (𝟎 : V)) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((nIdx_bnumZeroCert : ℕ) : V) ?[wt]) ∧ sTag (mkStep W ((nIdx_bnumZeroCert : ℕ) : V) ?[wt]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_bnumZeroCert : ℕ) : V) ?[wt]) = insert (neg LAct (bnumFact wt (𝟎 : V))) Γ := by
  subst hWp
  have hstep := nmk_bnumZeroCert (V := V) ?[wt]
  have hes : ∀ e ∈ [wt], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_nil _⟩
  have hinst := inst_bnumZeroCert hwt
  rw [hstep, show (?[wt] : V) = vecOf [wt] from rfl]
  refine ⟨stepOK_useHorn htbl [wt] row_bnumZeroCert_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 1 ≤ 8))
    (by rw [show row_bnumZeroCert_as.length = 1 from rfl] <;> exact_mod_cast (by decide : 1 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_nil _⟩)
  · rw [ctxAfter_useHorn [wt] row_bnumZeroCert_as isSemiformula_bnumZeroCert_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `bnumOneCert` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_bnumOneCert {tbl N E Γ W : V} {wt : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_bnumOneCert : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_bnumOneCert : ℕ) : V)] = ((1 : ℕ) : V) ∧
      rowB tbl.[((nIdx_bnumOneCert : ℕ) : V)] = impChainV LAct (vecOf row_bnumOneCert_as) row_bnumOneCert_c)
    (hΓ : IsFormulaSet LAct Γ) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hmem0 : neg LAct (funcFact wt (𝟎 : V) (cT 1) (𝟎 : V)) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((nIdx_bnumOneCert : ℕ) : V) ?[wt]) ∧ sTag (mkStep W ((nIdx_bnumOneCert : ℕ) : V) ?[wt]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_bnumOneCert : ℕ) : V) ?[wt]) = insert (neg LAct (bnumFact wt (𝟏 : V))) Γ := by
  subst hWp
  have hstep := nmk_bnumOneCert (V := V) ?[wt]
  have hes : ∀ e ∈ [wt], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_nil _⟩
  have hinst := inst_bnumOneCert hwt
  rw [hstep, show (?[wt] : V) = vecOf [wt] from rfl]
  refine ⟨stepOK_useHorn htbl [wt] row_bnumOneCert_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 1 ≤ 8))
    (by rw [show row_bnumOneCert_as.length = 1 from rfl] <;> exact_mod_cast (by decide : 1 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_nil _⟩)
  · rw [ctxAfter_useHorn [wt] row_bnumOneCert_as isSemiformula_bnumOneCert_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `bnumEvenCert` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_bnumEvenCert {tbl N E Γ W : V} {wm wt wone wwp ww wtwo wvp wv wu : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_bnumEvenCert : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_bnumEvenCert : ℕ) : V)] = ((9 : ℕ) : V) ∧
      rowB tbl.[((nIdx_bnumEvenCert : ℕ) : V)] = impChainV LAct (vecOf row_bnumEvenCert_as) row_bnumEvenCert_c)
    (hΓ : IsFormulaSet LAct Γ) (hwm : IsSemiterm LAct 0 wm) (hEwm : termLen LAct wm ≤ E) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hwone : IsSemiterm LAct 0 wone) (hEwone : termLen LAct wone ≤ E) (hwwp : IsSemiterm LAct 0 wwp) (hEwwp : termLen LAct wwp ≤ E) (hww : IsSemiterm LAct 0 ww) (hEww : termLen LAct ww ≤ E) (hwtwo : IsSemiterm LAct 0 wtwo) (hEwtwo : termLen LAct wtwo ≤ E) (hwvp : IsSemiterm LAct 0 wvp) (hEwvp : termLen LAct wvp ≤ E) (hwv : IsSemiterm LAct 0 wv) (hEwv : termLen LAct wv ≤ E) (hwu : IsSemiterm LAct 0 wu) (hEwu : termLen LAct wu ≤ E) (hmem0 : neg LAct (leFact (𝟏 : V) wm) ∈ Γ) (hmem1 : neg LAct (bnumFact wt wm) ∈ Γ) (hmem2 : neg LAct (funcFact wone (𝟎 : V) (cT 1) (𝟎 : V)) ∈ Γ) (hmem3 : neg LAct (adjFact wwp wone (𝟎 : V)) ∈ Γ) (hmem4 : neg LAct (adjFact ww wone wwp) ∈ Γ) (hmem5 : neg LAct (funcFact wtwo (cT 2) (𝟎 : V) ww) ∈ Γ) (hmem6 : neg LAct (adjFact wvp wt (𝟎 : V)) ∈ Γ) (hmem7 : neg LAct (adjFact wv wtwo wvp) ∈ Γ) (hmem8 : neg LAct (funcFact wu (cT 2) (cT 1) wv) ∈ Γ) :
    StepOK tbl E ((9 : ℕ) : V) Γ (mkStep W ((nIdx_bnumEvenCert : ℕ) : V) ?[wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu]) ∧ sTag (mkStep W ((nIdx_bnumEvenCert : ℕ) : V) ?[wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_bnumEvenCert : ℕ) : V) ?[wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu]) = insert (neg LAct (bnumFact wu (((𝟏 : V) ^+ (𝟏 : V)) ^* wm))) Γ := by
  subst hWp
  have hstep := nmk_bnumEvenCert (V := V) ?[wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu]
  have hes : ∀ e ∈ [wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwm, hEwm⟩, List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hwone, hEwone⟩, List.forall_mem_cons.mpr ⟨⟨hwwp, hEwwp⟩, List.forall_mem_cons.mpr ⟨⟨hww, hEww⟩, List.forall_mem_cons.mpr ⟨⟨hwtwo, hEwtwo⟩, List.forall_mem_cons.mpr ⟨⟨hwvp, hEwvp⟩, List.forall_mem_cons.mpr ⟨⟨hwv, hEwv⟩, List.forall_mem_cons.mpr ⟨⟨hwu, hEwu⟩, List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩
  have hinst := inst_bnumEvenCert hwm hwt hwone hwwp hww hwtwo hwvp hwv hwu
  rw [hstep, show (?[wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu] : V) = vecOf [wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu] from rfl]
  refine ⟨stepOK_useHorn htbl [wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu] row_bnumEvenCert_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 9 ≤ 9))
    (by rw [show row_bnumEvenCert_as.length = 9 from rfl] <;> exact_mod_cast (by decide : 9 ≤ 9)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_cons.mpr ⟨hmem3, List.forall_mem_cons.mpr ⟨hmem4, List.forall_mem_cons.mpr ⟨hmem5, List.forall_mem_cons.mpr ⟨hmem6, List.forall_mem_cons.mpr ⟨hmem7, List.forall_mem_cons.mpr ⟨hmem8, List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩)
  · rw [ctxAfter_useHorn [wm, wt, wone, wwp, ww, wtwo, wvp, wv, wu] row_bnumEvenCert_as isSemiformula_bnumEvenCert_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `bnumOddOfEven` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma nok_bnumOddOfEven {tbl N E Γ W : V} {wm wone ws wxp wx wu : V} (htbl : TableOK tbl N) (hWp : W = numIdPieces)
    (hlen : ((nIdx_bnumOddOfEven : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((nIdx_bnumOddOfEven : ℕ) : V)] = ((6 : ℕ) : V) ∧
      rowB tbl.[((nIdx_bnumOddOfEven : ℕ) : V)] = impChainV LAct (vecOf row_bnumOddOfEven_as) row_bnumOddOfEven_c)
    (hΓ : IsFormulaSet LAct Γ) (hwm : IsSemiterm LAct 0 wm) (hEwm : termLen LAct wm ≤ E) (hwone : IsSemiterm LAct 0 wone) (hEwone : termLen LAct wone ≤ E) (hws : IsSemiterm LAct 0 ws) (hEws : termLen LAct ws ≤ E) (hwxp : IsSemiterm LAct 0 wxp) (hEwxp : termLen LAct wxp ≤ E) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hwu : IsSemiterm LAct 0 wu) (hEwu : termLen LAct wu ≤ E) (hmem0 : neg LAct (leFact (𝟏 : V) wm) ∈ Γ) (hmem1 : neg LAct (bnumFact ws (((𝟏 : V) ^+ (𝟏 : V)) ^* wm)) ∈ Γ) (hmem2 : neg LAct (funcFact wone (𝟎 : V) (cT 1) (𝟎 : V)) ∈ Γ) (hmem3 : neg LAct (adjFact wxp wone (𝟎 : V)) ∈ Γ) (hmem4 : neg LAct (adjFact wx ws wxp) ∈ Γ) (hmem5 : neg LAct (funcFact wu (cT 2) (𝟎 : V) wx) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((nIdx_bnumOddOfEven : ℕ) : V) ?[wm, wone, ws, wxp, wx, wu]) ∧ sTag (mkStep W ((nIdx_bnumOddOfEven : ℕ) : V) ?[wm, wone, ws, wxp, wx, wu]) = 0 ∧
    ctxAfter Γ (mkStep W ((nIdx_bnumOddOfEven : ℕ) : V) ?[wm, wone, ws, wxp, wx, wu]) = insert (neg LAct (bnumFact wu ((((𝟏 : V) ^+ (𝟏 : V)) ^* wm) ^+ (𝟏 : V)))) Γ := by
  subst hWp
  have hstep := nmk_bnumOddOfEven (V := V) ?[wm, wone, ws, wxp, wx, wu]
  have hes : ∀ e ∈ [wm, wone, ws, wxp, wx, wu], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwm, hEwm⟩, List.forall_mem_cons.mpr ⟨⟨hwone, hEwone⟩, List.forall_mem_cons.mpr ⟨⟨hws, hEws⟩, List.forall_mem_cons.mpr ⟨⟨hwxp, hEwxp⟩, List.forall_mem_cons.mpr ⟨⟨hwx, hEwx⟩, List.forall_mem_cons.mpr ⟨⟨hwu, hEwu⟩, List.forall_mem_nil _⟩⟩⟩⟩⟩⟩
  have hinst := inst_bnumOddOfEven hwm hwone hws hwxp hwx hwu
  rw [hstep, show (?[wm, wone, ws, wxp, wx, wu] : V) = vecOf [wm, wone, ws, wxp, wx, wu] from rfl]
  refine ⟨stepOK_useHorn htbl [wm, wone, ws, wxp, wx, wu] row_bnumOddOfEven_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 6 ≤ 8))
    (by rw [show row_bnumOddOfEven_as.length = 6 from rfl] <;> exact_mod_cast (by decide : 6 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_cons.mpr ⟨hmem3, List.forall_mem_cons.mpr ⟨hmem4, List.forall_mem_cons.mpr ⟨hmem5, List.forall_mem_nil _⟩⟩⟩⟩⟩⟩)
  · rw [ctxAfter_useHorn [wm, wone, ws, wxp, wx, wu] row_bnumOddOfEven_as isSemiformula_bnumOddOfEven_c (fun e he ↦ (hes e he).1), hinst.2]

end numIdRowsTable

end ArithS
