import ArithS.Necessitation.NumIdRows
import ArithS.Necessitation.Frag2Rows

/-!
# ArithS.Necessitation.ProAxmRows — the `axm` prologue's row (GENERATED by `arith/scripts/gen_proaxm.py`)

ONE new row beyond the pin table (`NumIdRows.lean`): `congAxch` — `!axch x → y = x → !axch y`, the congruence
of the `TAct`-axiom recognizer `(Theory.Δ₁ch TAct).sigma` (predicate code `Paxch`, fact code `axchFact`,
`Frag2Rows.lean` §0) along an equality. It is the closing step of `axm` case (i) (`DESIGN_fragments.md` §4.10 (i),
`ProAxm.lean`): from NumId's `eqFact &ip (numeral ⌜σ⌝)` and the closed `Lib` fact `axchFact (numeral ⌜σ⌝)` (an
`sLemma`) it concludes `axchFact &ip` — ONE row for every standard axiom σ, where `Lib/Nodes.lean`'s `axiomRec σ`
would need one row per σ. The extra rows `proAxmExtraRows` sit at `aIdx_<row> = numIdRowCount + k` — APPEND-ONLY
after the pin table and SYMBOLIC in `numIdRowCount`; the piece table `proAxmPieces` extends `numIdPieces`
entrywise; per row `amk_<row>`, `atag_<row>`, `aok_<row>` — the applicability lemmas take the table readings at
the row's index as EXPLICIT hypotheses; `ProAxmTable` lives in `ProAxm.lean`.
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open PeanoMinus ISigma0 ISigma1
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 0. The new library row (`Lib`) -/

section proAxmLib

/-- `x ∈ TAct.Δ₁Class → y = x → y ∈ TAct.Δ₁Class` — the recognizer `(Theory.Δ₁ch TAct).sigma` along an equality (the `axm`(i) closing step: `axchFact (numeral ⌜σ⌝)` and `&ip = numeral ⌜σ⌝` give `axchFact &ip`). -/
noncomputable def congAxchB : ArithmeticSemisentence 2 :=
  “y x. !(Theory.Δ₁ch TAct).sigma x → y = x → !(Theory.Δ₁ch TAct).sigma y”
noncomputable def congAxch : ArithmeticSentence := ∀¹* congAxchB
lemma models_congAxch : V↓[ℒₒᵣ] ⊧ congAxch ↔ ∀ y x : V, x ∈ TAct.Δ₁Class → y = x → y ∈ TAct.Δ₁Class := by
  simp [congAxch, congAxchB, models_iff, Matrix.vecForall_iff]
theorem pa_proves_congAxch : 𝗣𝗔 ⊢ congAxch :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_congAxch.mpr fun _ _ h1 h2 ↦ by subst_vars; first | rfl | assumption | trivial
theorem lib_congAxch : Lib congAxch := Lib.of_pa pa_proves_congAxch

end proAxmLib

/-! ## 1. Its `quote_row_`/`inst_` block (the `RowInstB` template) -/

section proAxmRowInst

/-! ### `congAxch` — `“y x. …”`, `m = 2` -/

noncomputable def row_congAxch_as : List V := [subst LAct (listToVec [bv 1]) Paxch, subst LAct (listToVec [bv 0, bv 1]) PeqB]
noncomputable def row_congAxch_c : V := subst LAct (listToVec [bv 0]) Paxch

theorem quote_row_congAxch : (⌜Semiformula.lMap emb congAxchB⌝ : V) = impChain LAct row_congAxch_as row_congAxch_c := by
  unfold congAxchB row_congAxch_as row_congAxch_c Paxch PeqB
  all_goals row_shapeB

lemma isSemiformula_congAxch_as : ∀ A ∈ row_congAxch_as, IsSemiformula LAct ((2 : ℕ) : V) A := by
  unfold row_congAxch_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Paxch _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩)
lemma isSemiformula_congAxch_c : IsSemiformula LAct ((2 : ℕ) : V) row_congAxch_c := by
  unfold row_congAxch_c
  exact isSemiformula_substRow isSemiformula_Paxch _ (by rfl) (by row_entriesB)

/-- `congAxch` at the witnesses `[wx, wy]` (the DSL variables right-to-left). -/
lemma inst_congAxch {wx wy : V} (hwx : IsSemiterm LAct 0 wx) (hwy : IsSemiterm LAct 0 wy) :
    row_congAxch_as.map (instOuter LAct [wx, wy]) = [axchFact wx, eqFactB wy wx] ∧
    instOuter LAct [wx, wy] row_congAxch_c = axchFact wy := by
  have hes : ∀ e ∈ ([wx, wy] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwx, List.forall_mem_cons.mpr ⟨hwy, List.forall_mem_nil _⟩⟩)
  unfold row_congAxch_as row_congAxch_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Paxch (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Paxch (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

end proAxmRowInst

/-! ## 2. The extra rows at `numIdRowCount + k`, the piece table, the applicability lemmas -/

section proAxmRowsTable

def aIdx_congAxch : ℕ := numIdRowCount + 0
def proAxmExtraRowCount : ℕ := 1

/-- The extra rows at `numIdRowCount + k`, in index order (append-only). -/
noncomputable def proAxmExtraRows : List WRow := [
  ⟨2, congAxchB, lib_congAxch⟩
]

lemma proAxmExtraRows_length : proAxmExtraRows.length = proAxmExtraRowCount := rfl

/-- **The `axm` table's rows**: the pin's rows, then the `axm` rows. -/
noncomputable def proAxmRows : List WRow := numIdRows ++ proAxmExtraRows
def proAxmRowCount : ℕ := numIdRowCount + proAxmExtraRowCount
lemma proAxmRows_length : proAxmRows.length = proAxmRowCount := by
  simp only [proAxmRows, List.length_append, numIdRows_length, proAxmExtraRows_length, proAxmRowCount]

/-! ### The piece table -/

noncomputable def apiece_congAxch : V := ⟪(0 : V), vecOf row_congAxch_as, row_congAxch_c⟫

noncomputable def proAxmExtraPieceList : List V := [
  apiece_congAxch
]

/-- **The piece table of the `axm` prologue**: the pin's pieces, then the extra rows' pieces. -/
noncomputable def proAxmPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList ++ proAxmExtraPieceList)

set_option maxHeartbeats 1000000 in
lemma proAxmPieces_nth_lt (i : ℕ) (hi : i < numIdRowCount) : (proAxmPieces : V).[(i : V)] = (numIdPieces : V).[(i : V)] := by
  unfold proAxmPieces numIdPieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList ++ proAxmExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList ++ proAxmExtraPieceList : List V).length = proAxmRowCount from rfl]
    exact lt_of_lt_of_le hi (by simp only [proAxmRowCount]; omega)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList ++ numIdPadPieceList ++ numIdExtraPieceList : List V).length = numIdRowCount from rfl]; exact hi
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact List.getElem_append_left h2

/-- A pin step read from the `axm` pieces is the pin's step. -/
lemma mkStep_proAxmPieces_lt (i : ℕ) (hi : i < numIdRowCount) (ev : V) :
    mkStep proAxmPieces (i : V) ev = mkStep numIdPieces (i : V) ev := by
  rw [mkStep, mkStep, proAxmPieces_nth_lt i hi]

set_option maxHeartbeats 1000000 in
lemma proAxmPieces_congAxch : (proAxmPieces : V).[((aIdx_congAxch : ℕ) : V)] = apiece_congAxch := by
  unfold proAxmPieces
  rw [nth_vecOf _ aIdx_congAxch (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma amk_congAxch (ev : V) :
    mkStep proAxmPieces ((aIdx_congAxch : ℕ) : V) ev = sUseHorn ((aIdx_congAxch : ℕ) : V) ev (vecOf row_congAxch_as) row_congAxch_c := by
  rw [mkStep, proAxmPieces_congAxch]
  simp [apiece_congAxch, sUseHorn]

lemma atag_congAxch {W : V} (hWp : W = proAxmPieces) (ev : V) : sTag (mkStep W ((aIdx_congAxch : ℕ) : V) ev) = 0 := by
  subst hWp
  rw [amk_congAxch]; simp

/-! ### The per-row applicability lemmas `aok_<row>` (against explicit table readings) -/

/-- Row `congAxch` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma aok_congAxch {tbl N E Γ W : V} {wx wy : V} (htbl : TableOK tbl N) (hWp : W = proAxmPieces)
    (hlen : ((aIdx_congAxch : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((aIdx_congAxch : ℕ) : V)] = ((2 : ℕ) : V) ∧
      rowB tbl.[((aIdx_congAxch : ℕ) : V)] = impChainV LAct (vecOf row_congAxch_as) row_congAxch_c)
    (hΓ : IsFormulaSet LAct Γ) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hwy : IsSemiterm LAct 0 wy) (hEwy : termLen LAct wy ≤ E) (hmem0 : neg LAct (axchFact wx) ∈ Γ) (hmem1 : neg LAct (eqFactB wy wx) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W ((aIdx_congAxch : ℕ) : V) ?[wx, wy]) ∧ sTag (mkStep W ((aIdx_congAxch : ℕ) : V) ?[wx, wy]) = 0 ∧
    ctxAfter Γ (mkStep W ((aIdx_congAxch : ℕ) : V) ?[wx, wy]) = insert (neg LAct (axchFact wy)) Γ := by
  subst hWp
  have hstep := amk_congAxch (V := V) ?[wx, wy]
  have hes : ∀ e ∈ [wx, wy], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwx, hEwx⟩, List.forall_mem_cons.mpr ⟨⟨hwy, hEwy⟩, List.forall_mem_nil _⟩⟩
  have hinst := inst_congAxch hwx hwy
  rw [hstep, show (?[wx, wy] : V) = vecOf [wx, wy] from rfl]
  refine ⟨stepOK_useHorn htbl [wx, wy] row_congAxch_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 2 ≤ 8))
    (by rw [show row_congAxch_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wx, wy] row_congAxch_as isSemiformula_congAxch_c (fun e he ↦ (hes e he).1), hinst.2]

end proAxmRowsTable

end ArithS
