import ArithS.Necessitation.Top

/-!
# ArithS.Necessitation.PrologueRows — the prologue rows (GENERATED by `arith/scripts/gen_prologue.py`)

The rows `Prologue.lean` needs beyond the top table, each with its `Lib` block (`<row>B`, `models_`,
`pa_proves_`, `lib_`) and its `quote_row_`/`inst_` block; the extra rows `proExtraRows` at
`pIdx_<row> = topRowCount + k` (APPEND-ONLY, index-stable); the piece table `proPieces` extending
`topPieces` entrywise (`mkStep_proPieces_lt`); per row `pmk_<row>`, `ptag_<row>`, `pok_<row>`.
The applicability lemmas take the table readings at the row's index as EXPLICIT hypotheses — no table
predicate is defined here (`Prologue.lean`'s `ProTable` places these rows and the certification tail).

Currently: `setLenSingLe` (155) — `t = insert x ∅ → l = setLen t → lx = |x| → l ≤ lx`, the base of the
`setLen` fold (`DESIGN_fragments.md` §3.4; the library's `setLenInsertLe` needs a length object of the
set below, and the empty set has none in any table); `setLenEmptyLe` (156) — `l = setLen ∅ → l ≤ 0`, the
EMPTY sequent's layout; and two library rows that were in no piece table, `congSubsetL` (157) and
`congSetShiftR` (158) (their `Lib` and `inst_` blocks live in `Lib/Frag.lean` / `RowInstB.lean`).
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open PeanoMinus ISigma0 ISigma1
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 0. The library rows (`Lib`) -/

section proLib

/-- `t = insert x ∅ → l = setLen t → lx = |x| → l ≤ lx` (the base of the `setLen` fold: a singleton is at most its member). -/
noncomputable def setLenSingLeB : ArithmeticSemisentence 4 :=
  “lx l t x. !insertDef t x 0 → !(setLenDef LAct) l t → !(formulaLenGraph LAct) lx x → l ≤ lx”
noncomputable def setLenSingLe : ArithmeticSentence := ∀¹* setLenSingLeB
lemma models_setLenSingLe : V↓[ℒₒᵣ] ⊧ setLenSingLe ↔ ∀ lx l t x : V, t = insert x (0 : V) → l = setLen LAct t → lx = formulaLen LAct x → l ≤ lx := by
  simp [setLenSingLe, setLenSingLeB, models_iff, Matrix.vecForall_iff, setLen_defined.iff, formulaLen.defined.iff]
theorem pa_proves_setLenSingLe : 𝗣𝗔 ⊢ setLenSingLe :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_setLenSingLe.mpr fun _ _ _ _ h₁ h₂ h₃ ↦ by subst_vars; rw [setLen_insert_of_not_mem_V (L := LAct) (by simp), ← emptyset_def, setLen_empty, zero_add]
theorem lib_setLenSingLe : Lib setLenSingLe := Lib.of_pa pa_proves_setLenSingLe

/-- `l = setLen ∅ → l ≤ 0` (the empty sequent: its length object is bounded by the numeral `bnum 0 = 𝟎`). -/
noncomputable def setLenEmptyLeB : ArithmeticSemisentence 1 :=
  “l. !(setLenDef LAct) l 0 → l ≤ 0”
noncomputable def setLenEmptyLe : ArithmeticSentence := ∀¹* setLenEmptyLeB
lemma models_setLenEmptyLe : V↓[ℒₒᵣ] ⊧ setLenEmptyLe ↔ ∀ l : V, l = setLen LAct (0 : V) → l ≤ (0 : V) := by
  simp [setLenEmptyLe, setLenEmptyLeB, models_iff, Matrix.vecForall_iff, setLen_defined.iff]
theorem pa_proves_setLenEmptyLe : 𝗣𝗔 ⊢ setLenEmptyLe :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_setLenEmptyLe.mpr fun _ h₁ ↦ by subst_vars; rw [← emptyset_def, setLen_empty]; try exact le_refl _
theorem lib_setLenEmptyLe : Lib setLenEmptyLe := Lib.of_pa pa_proves_setLenEmptyLe

/-- `x = y → x ≤ y` (the `exs` witness term: from `eqTotal`'s eigenvariable `l = bnum |t|` to `leFact l (bnum |t|)`; the library's `leOfEq` has no `inst_` block). -/
noncomputable def leOfEqPB : ArithmeticSemisentence 2 :=
  “y x. x = y → x ≤ y”
noncomputable def leOfEqP : ArithmeticSentence := ∀¹* leOfEqPB
lemma models_leOfEqP : V↓[ℒₒᵣ] ⊧ leOfEqP ↔ ∀ y x : V, x = y → x ≤ y := by
  simp [leOfEqP, leOfEqPB, models_iff, Matrix.vecForall_iff]
theorem pa_proves_leOfEqP : 𝗣𝗔 ⊢ leOfEqP :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_leOfEqP.mpr fun _ _ h₁ ↦ by subst_vars; exact le_refl _
theorem lib_leOfEqP : Lib leOfEqP := Lib.of_pa pa_proves_leOfEqP

end proLib

/-! ## 1. The rows as pieces: `row_<r>_as`/`_c`, `quote_row_<r>`, `inst_<r>` (the `RowInstB` template) -/

section proRowInst

/-! ### `setLenSingLe` — `“lx l t x. …”`, `m = 4` -/

noncomputable def row_setLenSingLe_as : List V := [subst LAct (listToVec [bv 2, bv 3, (𝟎 : V)]) Pinsert, subst LAct (listToVec [bv 1, bv 2]) PsetLen, subst LAct (listToVec [bv 0, bv 3]) PflenG]
noncomputable def row_setLenSingLe_c : V := subst LAct (listToVec [bv 1, bv 0]) Ple

theorem quote_row_setLenSingLe : (⌜Semiformula.lMap emb setLenSingLeB⌝ : V) = impChain LAct row_setLenSingLe_as row_setLenSingLe_c := by
  unfold setLenSingLeB row_setLenSingLe_as row_setLenSingLe_c PflenG Pinsert Ple PsetLen leS
  all_goals row_shapeB

lemma isSemiformula_setLenSingLe_as : ∀ A ∈ row_setLenSingLe_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_setLenSingLe_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pinsert _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PsetLen _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PflenG _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_setLenSingLe_c : IsSemiformula LAct ((4 : ℕ) : V) row_setLenSingLe_c := by
  unfold row_setLenSingLe_c
  exact isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB)

/-- `setLenSingLe` at the witnesses `[wx, wt, wl, wlx]` (the DSL variables right-to-left). -/
lemma inst_setLenSingLe {wx wt wl wlx : V} (hwx : IsSemiterm LAct 0 wx) (hwt : IsSemiterm LAct 0 wt) (hwl : IsSemiterm LAct 0 wl) (hwlx : IsSemiterm LAct 0 wlx) :
    row_setLenSingLe_as.map (instOuter LAct [wx, wt, wl, wlx]) = [insFact wt wx (𝟎 : V), setLenFact wl wt, lenFact wlx wx] ∧
    instOuter LAct [wx, wt, wl, wlx] row_setLenSingLe_c = leFact wl wlx := by
  have hes : ∀ e ∈ ([wx, wt, wl, wlx] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwx, List.forall_mem_cons.mpr ⟨hwt, List.forall_mem_cons.mpr ⟨hwl, List.forall_mem_cons.mpr ⟨hwlx, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_setLenSingLe_as row_setLenSingLe_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pinsert (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PsetLen (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PflenG (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `setLenEmptyLe` — `“l. …”`, `m = 1` -/

noncomputable def row_setLenEmptyLe_as : List V := [subst LAct (listToVec [bv 0, (𝟎 : V)]) PsetLen]
noncomputable def row_setLenEmptyLe_c : V := subst LAct (listToVec [bv 0, (𝟎 : V)]) Ple

theorem quote_row_setLenEmptyLe : (⌜Semiformula.lMap emb setLenEmptyLeB⌝ : V) = impChain LAct row_setLenEmptyLe_as row_setLenEmptyLe_c := by
  unfold setLenEmptyLeB row_setLenEmptyLe_as row_setLenEmptyLe_c Ple PsetLen leS
  all_goals row_shapeB

lemma isSemiformula_setLenEmptyLe_as : ∀ A ∈ row_setLenEmptyLe_as, IsSemiformula LAct ((1 : ℕ) : V) A := by
  unfold row_setLenEmptyLe_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PsetLen _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩)
lemma isSemiformula_setLenEmptyLe_c : IsSemiformula LAct ((1 : ℕ) : V) row_setLenEmptyLe_c := by
  unfold row_setLenEmptyLe_c
  exact isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB)

/-- `setLenEmptyLe` at the witnesses `[wl]` (the DSL variables right-to-left). -/
lemma inst_setLenEmptyLe {wl : V} (hwl : IsSemiterm LAct 0 wl) :
    row_setLenEmptyLe_as.map (instOuter LAct [wl]) = [setLenFact wl (𝟎 : V)] ∧
    instOuter LAct [wl] row_setLenEmptyLe_c = leFact wl (𝟎 : V) := by
  have hes : ∀ e ∈ ([wl] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwl, List.forall_mem_nil _⟩)
  unfold row_setLenEmptyLe_as row_setLenEmptyLe_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_PsetLen (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `leOfEqP` — `“y x. …”`, `m = 2` -/

noncomputable def row_leOfEqP_as : List V := [subst LAct (listToVec [bv 1, bv 0]) PeqB]
noncomputable def row_leOfEqP_c : V := subst LAct (listToVec [bv 1, bv 0]) Ple

theorem quote_row_leOfEqP : (⌜Semiformula.lMap emb leOfEqPB⌝ : V) = impChain LAct row_leOfEqP_as row_leOfEqP_c := by
  unfold leOfEqPB row_leOfEqP_as row_leOfEqP_c PeqB Ple leS
  all_goals row_shapeB

lemma isSemiformula_leOfEqP_as : ∀ A ∈ row_leOfEqP_as, IsSemiformula LAct ((2 : ℕ) : V) A := by
  unfold row_leOfEqP_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩)
lemma isSemiformula_leOfEqP_c : IsSemiformula LAct ((2 : ℕ) : V) row_leOfEqP_c := by
  unfold row_leOfEqP_c
  exact isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB)

/-- `leOfEqP` at the witnesses `[wx, wy]` (the DSL variables right-to-left). -/
lemma inst_leOfEqP {wx wy : V} (hwx : IsSemiterm LAct 0 wx) (hwy : IsSemiterm LAct 0 wy) :
    row_leOfEqP_as.map (instOuter LAct [wx, wy]) = [eqFactB wx wy] ∧
    instOuter LAct [wx, wy] row_leOfEqP_c = leFact wx wy := by
  have hes : ∀ e ∈ ([wx, wy] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwx, List.forall_mem_cons.mpr ⟨hwy, List.forall_mem_nil _⟩⟩)
  unfold row_leOfEqP_as row_leOfEqP_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

end proRowInst

/-! ## 2. The extra rows at `topRowCount + k`, the piece table, the applicability lemmas -/

section proRowsTable

def pIdx_setLenSingLe : ℕ := 155
def pIdx_setLenEmptyLe : ℕ := 156
def pIdx_congSubsetL : ℕ := 157
def pIdx_congSetShiftR : ℕ := 158
def pIdx_leOfEqP : ℕ := 159
def proExtraRowCount : ℕ := 5

/-- The extra rows at `topRowCount + k`, in index order (append-only). -/
noncomputable def proExtraRows : List WRow := [
  ⟨4, setLenSingLeB, lib_setLenSingLe⟩,
  ⟨1, setLenEmptyLeB, lib_setLenEmptyLe⟩,
  ⟨3, congSubsetLB, lib_congSubsetL⟩,
  ⟨3, congSetShiftRB, lib_congSetShiftR⟩,
  ⟨2, leOfEqPB, lib_leOfEqP⟩
]

lemma proExtraRows_length : proExtraRows.length = proExtraRowCount := rfl

/-! ### The piece table -/

noncomputable def ppiece_setLenSingLe : V := ⟪(0 : V), vecOf row_setLenSingLe_as, row_setLenSingLe_c⟫
noncomputable def ppiece_setLenEmptyLe : V := ⟪(0 : V), vecOf row_setLenEmptyLe_as, row_setLenEmptyLe_c⟫
noncomputable def ppiece_congSubsetL : V := ⟪(0 : V), vecOf row_congSubsetL_as, row_congSubsetL_c⟫
noncomputable def ppiece_congSetShiftR : V := ⟪(0 : V), vecOf row_congSetShiftR_as, row_congSetShiftR_c⟫
noncomputable def ppiece_leOfEqP : V := ⟪(0 : V), vecOf row_leOfEqP_as, row_leOfEqP_c⟫

noncomputable def proExtraPieceList : List V := [
  ppiece_setLenSingLe,
  ppiece_setLenEmptyLe,
  ppiece_congSubsetL,
  ppiece_congSetShiftR,
  ppiece_leOfEqP
]

/-- **The piece table of the prologue producers**: the top's pieces, then the extra rows' pieces. -/
noncomputable def proPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList)

lemma proPieces_nth_lt (i : ℕ) (hi : i < topRowCount) : (proPieces : V).[(i : V)] = (topPieces : V).[(i : V)] := by
  unfold proPieces topPieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length = topRowCount + proExtraRowCount from rfl]
    exact lt_of_lt_of_le hi (Nat.le_add_right _ _)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length = topRowCount from rfl]; exact hi
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact List.getElem_append_left h2

/-- A top step read from the prologue pieces is the top's step. -/
lemma mkStep_proPieces_lt (i : ℕ) (hi : i < topRowCount) (ev : V) :
    mkStep proPieces (i : V) ev = mkStep topPieces (i : V) ev := by
  rw [mkStep, mkStep, proPieces_nth_lt i hi]

lemma proPieces_setLenSingLe : (proPieces : V).[((pIdx_setLenSingLe : ℕ) : V)] = ppiece_setLenSingLe := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_setLenSingLe (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_setLenSingLe (ev : V) :
    mkStep proPieces ((pIdx_setLenSingLe : ℕ) : V) ev = sUseHorn ((pIdx_setLenSingLe : ℕ) : V) ev (vecOf row_setLenSingLe_as) row_setLenSingLe_c := by
  rw [mkStep, proPieces_setLenSingLe]
  simp [ppiece_setLenSingLe, sUseHorn]

lemma ptag_setLenSingLe {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (155 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_setLenSingLe : ℕ) : V) = (155 : V) := by simp [pIdx_setLenSingLe]
  rw [← hk, pmk_setLenSingLe]; simp

lemma proPieces_setLenEmptyLe : (proPieces : V).[((pIdx_setLenEmptyLe : ℕ) : V)] = ppiece_setLenEmptyLe := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_setLenEmptyLe (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_setLenEmptyLe (ev : V) :
    mkStep proPieces ((pIdx_setLenEmptyLe : ℕ) : V) ev = sUseHorn ((pIdx_setLenEmptyLe : ℕ) : V) ev (vecOf row_setLenEmptyLe_as) row_setLenEmptyLe_c := by
  rw [mkStep, proPieces_setLenEmptyLe]
  simp [ppiece_setLenEmptyLe, sUseHorn]

lemma ptag_setLenEmptyLe {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (156 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_setLenEmptyLe : ℕ) : V) = (156 : V) := by simp [pIdx_setLenEmptyLe]
  rw [← hk, pmk_setLenEmptyLe]; simp

lemma proPieces_congSubsetL : (proPieces : V).[((pIdx_congSubsetL : ℕ) : V)] = ppiece_congSubsetL := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_congSubsetL (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_congSubsetL (ev : V) :
    mkStep proPieces ((pIdx_congSubsetL : ℕ) : V) ev = sUseHorn ((pIdx_congSubsetL : ℕ) : V) ev (vecOf row_congSubsetL_as) row_congSubsetL_c := by
  rw [mkStep, proPieces_congSubsetL]
  simp [ppiece_congSubsetL, sUseHorn]

lemma ptag_congSubsetL {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (157 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_congSubsetL : ℕ) : V) = (157 : V) := by simp [pIdx_congSubsetL]
  rw [← hk, pmk_congSubsetL]; simp

lemma proPieces_congSetShiftR : (proPieces : V).[((pIdx_congSetShiftR : ℕ) : V)] = ppiece_congSetShiftR := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_congSetShiftR (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_congSetShiftR (ev : V) :
    mkStep proPieces ((pIdx_congSetShiftR : ℕ) : V) ev = sUseHorn ((pIdx_congSetShiftR : ℕ) : V) ev (vecOf row_congSetShiftR_as) row_congSetShiftR_c := by
  rw [mkStep, proPieces_congSetShiftR]
  simp [ppiece_congSetShiftR, sUseHorn]

lemma ptag_congSetShiftR {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (158 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_congSetShiftR : ℕ) : V) = (158 : V) := by simp [pIdx_congSetShiftR]
  rw [← hk, pmk_congSetShiftR]; simp

lemma proPieces_leOfEqP : (proPieces : V).[((pIdx_leOfEqP : ℕ) : V)] = ppiece_leOfEqP := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_leOfEqP (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_leOfEqP (ev : V) :
    mkStep proPieces ((pIdx_leOfEqP : ℕ) : V) ev = sUseHorn ((pIdx_leOfEqP : ℕ) : V) ev (vecOf row_leOfEqP_as) row_leOfEqP_c := by
  rw [mkStep, proPieces_leOfEqP]
  simp [ppiece_leOfEqP, sUseHorn]

lemma ptag_leOfEqP {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (159 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_leOfEqP : ℕ) : V) = (159 : V) := by simp [pIdx_leOfEqP]
  rw [← hk, pmk_leOfEqP]; simp

/-! ### The per-row applicability lemmas `pok_<row>` (against explicit table readings) -/

/-- Row `setLenSingLe` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_setLenSingLe {tbl N E Γ W : V} {wx wt wl wlx : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_setLenSingLe : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_setLenSingLe : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((pIdx_setLenSingLe : ℕ) : V)] = impChainV LAct (vecOf row_setLenSingLe_as) row_setLenSingLe_c)
    (hΓ : IsFormulaSet LAct Γ) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hwl : IsSemiterm LAct 0 wl) (hEwl : termLen LAct wl ≤ E) (hwlx : IsSemiterm LAct 0 wlx) (hEwlx : termLen LAct wlx ≤ E) (hmem0 : neg LAct (insFact wt wx (𝟎 : V)) ∈ Γ) (hmem1 : neg LAct (setLenFact wl wt) ∈ Γ) (hmem2 : neg LAct (lenFact wlx wx) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 155 ?[wx, wt, wl, wlx]) ∧ sTag (mkStep W 155 ?[wx, wt, wl, wlx]) = 0 ∧
    ctxAfter Γ (mkStep W 155 ?[wx, wt, wl, wlx]) = insert (neg LAct (leFact wl wlx)) Γ := by
  subst hWp
  have hk : ((pIdx_setLenSingLe : ℕ) : V) = (155 : V) := by simp [pIdx_setLenSingLe]
  have hstep := pmk_setLenSingLe (V := V) ?[wx, wt, wl, wlx]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wx, wt, wl, wlx], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwx, hEwx⟩, List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hwl, hEwl⟩, List.forall_mem_cons.mpr ⟨⟨hwlx, hEwlx⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_setLenSingLe hwx hwt hwl hwlx
  rw [hstep, show (?[wx, wt, wl, wlx] : V) = vecOf [wx, wt, wl, wlx] from rfl]
  refine ⟨stepOK_useHorn htbl [wx, wt, wl, wlx] row_setLenSingLe_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_setLenSingLe_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wx, wt, wl, wlx] row_setLenSingLe_as isSemiformula_setLenSingLe_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `setLenEmptyLe` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_setLenEmptyLe {tbl N E Γ W : V} {wl : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_setLenEmptyLe : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_setLenEmptyLe : ℕ) : V)] = ((1 : ℕ) : V) ∧
      rowB tbl.[((pIdx_setLenEmptyLe : ℕ) : V)] = impChainV LAct (vecOf row_setLenEmptyLe_as) row_setLenEmptyLe_c)
    (hΓ : IsFormulaSet LAct Γ) (hwl : IsSemiterm LAct 0 wl) (hEwl : termLen LAct wl ≤ E) (hmem0 : neg LAct (setLenFact wl (𝟎 : V)) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 156 ?[wl]) ∧ sTag (mkStep W 156 ?[wl]) = 0 ∧
    ctxAfter Γ (mkStep W 156 ?[wl]) = insert (neg LAct (leFact wl (𝟎 : V))) Γ := by
  subst hWp
  have hk : ((pIdx_setLenEmptyLe : ℕ) : V) = (156 : V) := by simp [pIdx_setLenEmptyLe]
  have hstep := pmk_setLenEmptyLe (V := V) ?[wl]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wl], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwl, hEwl⟩, List.forall_mem_nil _⟩
  have hinst := inst_setLenEmptyLe hwl
  rw [hstep, show (?[wl] : V) = vecOf [wl] from rfl]
  refine ⟨stepOK_useHorn htbl [wl] row_setLenEmptyLe_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 1 ≤ 8))
    (by rw [show row_setLenEmptyLe_as.length = 1 from rfl] <;> exact_mod_cast (by decide : 1 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_nil _⟩)
  · rw [ctxAfter_useHorn [wl] row_setLenEmptyLe_as isSemiformula_setLenEmptyLe_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `congSubsetL` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_congSubsetL {tbl N E Γ W : V} {wt wtp wu : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_congSubsetL : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_congSubsetL : ℕ) : V)] = ((3 : ℕ) : V) ∧
      rowB tbl.[((pIdx_congSubsetL : ℕ) : V)] = impChainV LAct (vecOf row_congSubsetL_as) row_congSubsetL_c)
    (hΓ : IsFormulaSet LAct Γ) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hwtp : IsSemiterm LAct 0 wtp) (hEwtp : termLen LAct wtp ≤ E) (hwu : IsSemiterm LAct 0 wu) (hEwu : termLen LAct wu ≤ E) (hmem0 : neg LAct (eqFactB wtp wt) ∈ Γ) (hmem1 : neg LAct (subsetFact wt wu) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 157 ?[wt, wtp, wu]) ∧ sTag (mkStep W 157 ?[wt, wtp, wu]) = 0 ∧
    ctxAfter Γ (mkStep W 157 ?[wt, wtp, wu]) = insert (neg LAct (subsetFact wtp wu)) Γ := by
  subst hWp
  have hk : ((pIdx_congSubsetL : ℕ) : V) = (157 : V) := by simp [pIdx_congSubsetL]
  have hstep := pmk_congSubsetL (V := V) ?[wt, wtp, wu]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wt, wtp, wu], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hwtp, hEwtp⟩, List.forall_mem_cons.mpr ⟨⟨hwu, hEwu⟩, List.forall_mem_nil _⟩⟩⟩
  have hinst := inst_congSubsetL hwt hwtp hwu
  rw [hstep, show (?[wt, wtp, wu] : V) = vecOf [wt, wtp, wu] from rfl]
  refine ⟨stepOK_useHorn htbl [wt, wtp, wu] row_congSubsetL_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 3 ≤ 8))
    (by rw [show row_congSubsetL_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wt, wtp, wu] row_congSubsetL_as isSemiformula_congSubsetL_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `congSetShiftR` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_congSetShiftR {tbl N E Γ W : V} {wt ws wsp : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_congSetShiftR : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_congSetShiftR : ℕ) : V)] = ((3 : ℕ) : V) ∧
      rowB tbl.[((pIdx_congSetShiftR : ℕ) : V)] = impChainV LAct (vecOf row_congSetShiftR_as) row_congSetShiftR_c)
    (hΓ : IsFormulaSet LAct Γ) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hws : IsSemiterm LAct 0 ws) (hEws : termLen LAct ws ≤ E) (hwsp : IsSemiterm LAct 0 wsp) (hEwsp : termLen LAct wsp ≤ E) (hmem0 : neg LAct (eqFactB wsp ws) ∈ Γ) (hmem1 : neg LAct (setShiftFact wt ws) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 158 ?[wt, ws, wsp]) ∧ sTag (mkStep W 158 ?[wt, ws, wsp]) = 0 ∧
    ctxAfter Γ (mkStep W 158 ?[wt, ws, wsp]) = insert (neg LAct (setShiftFact wt wsp)) Γ := by
  subst hWp
  have hk : ((pIdx_congSetShiftR : ℕ) : V) = (158 : V) := by simp [pIdx_congSetShiftR]
  have hstep := pmk_congSetShiftR (V := V) ?[wt, ws, wsp]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wt, ws, wsp], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hws, hEws⟩, List.forall_mem_cons.mpr ⟨⟨hwsp, hEwsp⟩, List.forall_mem_nil _⟩⟩⟩
  have hinst := inst_congSetShiftR hwt hws hwsp
  rw [hstep, show (?[wt, ws, wsp] : V) = vecOf [wt, ws, wsp] from rfl]
  refine ⟨stepOK_useHorn htbl [wt, ws, wsp] row_congSetShiftR_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 3 ≤ 8))
    (by rw [show row_congSetShiftR_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wt, ws, wsp] row_congSetShiftR_as isSemiformula_congSetShiftR_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `leOfEqP` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_leOfEqP {tbl N E Γ W : V} {wx wy : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_leOfEqP : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_leOfEqP : ℕ) : V)] = ((2 : ℕ) : V) ∧
      rowB tbl.[((pIdx_leOfEqP : ℕ) : V)] = impChainV LAct (vecOf row_leOfEqP_as) row_leOfEqP_c)
    (hΓ : IsFormulaSet LAct Γ) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hwy : IsSemiterm LAct 0 wy) (hEwy : termLen LAct wy ≤ E) (hmem0 : neg LAct (eqFactB wx wy) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 159 ?[wx, wy]) ∧ sTag (mkStep W 159 ?[wx, wy]) = 0 ∧
    ctxAfter Γ (mkStep W 159 ?[wx, wy]) = insert (neg LAct (leFact wx wy)) Γ := by
  subst hWp
  have hk : ((pIdx_leOfEqP : ℕ) : V) = (159 : V) := by simp [pIdx_leOfEqP]
  have hstep := pmk_leOfEqP (V := V) ?[wx, wy]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wx, wy], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwx, hEwx⟩, List.forall_mem_cons.mpr ⟨⟨hwy, hEwy⟩, List.forall_mem_nil _⟩⟩
  have hinst := inst_leOfEqP hwx hwy
  rw [hstep, show (?[wx, wy] : V) = vecOf [wx, wy] from rfl]
  refine ⟨stepOK_useHorn htbl [wx, wy] row_leOfEqP_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 2 ≤ 8))
    (by rw [show row_leOfEqP_as.length = 1 from rfl] <;> exact_mod_cast (by decide : 1 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_nil _⟩)
  · rw [ctxAfter_useHorn [wx, wy] row_leOfEqP_as isSemiformula_leOfEqP_c (fun e he ↦ (hes e he).1), hinst.2]

end proRowsTable

end ArithS
