import ArithS.Necessitation.Top

/-!
# ArithS.Necessitation.PrologueRows — the prologue rows (GENERATED by `arith/scripts/gen_prologue.py`)

The rows `Prologue.lean` needs beyond the top table, each with its `Lib` block (`<row>B`, `models_`,
`pa_proves_`, `lib_`) and its `quote_row_`/`inst_` block; the extra rows `proExtraRows` at
`pIdx_<row> = topRowCount + k` (APPEND-ONLY, index-stable); the piece table `proPieces` extending
`topPieces` entrywise (`mkStep_proPieces_lt`); per row `pmk_<row>`, `ptag_<row>`, `pok_<row>`.
The applicability lemmas take the table readings at the row's index as EXPLICIT hypotheses — no table
predicate is defined here (`Prologue.lean`'s `ProTable` places these rows and the certification tail).

Currently: `setLenSingLe` — `t = insert x ∅ → l = setLen t → lx = |x| → l ≤ lx`, the base of the
`setLen` fold (`DESIGN_fragments.md` §3.4; the library's `setLenInsertLe` needs a length object of the
set below, and the empty set has none in any table).
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open PeanoMinus ISigma0 ISigma1
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 0. The library rows (`Lib`) -/

section proLib

/-- `t = insert x ∅ → l = setLen t → lx = |x| → l ≤ lx` (the base of the `setLen` fold: a singleton is at most its member). -/
noncomputable def setLenSingLeB : ArithmeticSemisentence 4 :=
  “lx l t x. !insertDef t x 0 → !(setLenDef LAct) l t → !(formulaLenGraph LAct) lx x → l ≤ lx”
noncomputable def setLenSingLe : ArithmeticSentence := ∀¹* setLenSingLeB
lemma models_setLenSingLe : V↓[ℒₒᵣ] ⊧ setLenSingLe ↔ ∀ lx l t x : V, t = insert x (0 : V) → l = setLen LAct t → lx = formulaLen LAct x → l ≤ lx := by
  simp [setLenSingLe, setLenSingLeB, models_iff, Matrix.vecForall_iff, setLen_defined.iff, formulaLen.defined.iff]
theorem pa_proves_setLenSingLe : 𝗣𝗔 ⊢ setLenSingLe :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_setLenSingLe.mpr fun _ _ _ _ h₁ h₂ h₃ ↦ by subst_vars; rw [setLen_insert_of_not_mem_V (L := LAct) (by simp), ← emptyset_def, setLen_empty, zero_add]
theorem lib_setLenSingLe : Lib setLenSingLe := Lib.of_pa pa_proves_setLenSingLe

end proLib

/-! ## 1. The rows as pieces: `row_<r>_as`/`_c`, `quote_row_<r>`, `inst_<r>` (the `RowInstB` template) -/

section proRowInst

/-! ### `setLenSingLe` — `“lx l t x. …”`, `m = 4` -/

noncomputable def row_setLenSingLe_as : List V := [subst LAct (listToVec [bv 2, bv 3, (𝟎 : V)]) Pinsert, subst LAct (listToVec [bv 1, bv 2]) PsetLen, subst LAct (listToVec [bv 0, bv 3]) PflenG]
noncomputable def row_setLenSingLe_c : V := subst LAct (listToVec [bv 1, bv 0]) Ple

theorem quote_row_setLenSingLe : (⌜Semiformula.lMap emb setLenSingLeB⌝ : V) = impChain LAct row_setLenSingLe_as row_setLenSingLe_c := by
  unfold setLenSingLeB row_setLenSingLe_as row_setLenSingLe_c PflenG Pinsert Ple PsetLen leS
  all_goals row_shapeB

lemma isSemiformula_setLenSingLe_as : ∀ A ∈ row_setLenSingLe_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_setLenSingLe_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pinsert _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PsetLen _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PflenG _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_setLenSingLe_c : IsSemiformula LAct ((4 : ℕ) : V) row_setLenSingLe_c := by
  unfold row_setLenSingLe_c
  exact isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB)

/-- `setLenSingLe` at the witnesses `[wx, wt, wl, wlx]` (the DSL variables right-to-left). -/
lemma inst_setLenSingLe {wx wt wl wlx : V} (hwx : IsSemiterm LAct 0 wx) (hwt : IsSemiterm LAct 0 wt) (hwl : IsSemiterm LAct 0 wl) (hwlx : IsSemiterm LAct 0 wlx) :
    row_setLenSingLe_as.map (instOuter LAct [wx, wt, wl, wlx]) = [insFact wt wx (𝟎 : V), setLenFact wl wt, lenFact wlx wx] ∧
    instOuter LAct [wx, wt, wl, wlx] row_setLenSingLe_c = leFact wl wlx := by
  have hes : ∀ e ∈ ([wx, wt, wl, wlx] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwx, List.forall_mem_cons.mpr ⟨hwt, List.forall_mem_cons.mpr ⟨hwl, List.forall_mem_cons.mpr ⟨hwlx, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_setLenSingLe_as row_setLenSingLe_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pinsert (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PsetLen (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PflenG (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

end proRowInst

/-! ## 2. The extra rows at `topRowCount + k`, the piece table, the applicability lemmas -/

section proRowsTable

def pIdx_setLenSingLe : ℕ := 155
def proExtraRowCount : ℕ := 1

/-- The extra rows at `topRowCount + k`, in index order (append-only). -/
noncomputable def proExtraRows : List WRow := [
  ⟨4, setLenSingLeB, lib_setLenSingLe⟩
]

lemma proExtraRows_length : proExtraRows.length = proExtraRowCount := rfl

/-! ### The piece table -/

noncomputable def ppiece_setLenSingLe : V := ⟪(0 : V), vecOf row_setLenSingLe_as, row_setLenSingLe_c⟫

noncomputable def proExtraPieceList : List V := [
  ppiece_setLenSingLe
]

/-- **The piece table of the prologue producers**: the top's pieces, then the extra rows' pieces. -/
noncomputable def proPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList)

lemma proPieces_nth_lt (i : ℕ) (hi : i < topRowCount) : (proPieces : V).[(i : V)] = (topPieces : V).[(i : V)] := by
  unfold proPieces topPieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList ++ proExtraPieceList : List V).length = topRowCount + proExtraRowCount from rfl]
    exact lt_of_lt_of_le hi (Nat.le_add_right _ _)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length = topRowCount from rfl]; exact hi
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact List.getElem_append_left h2

/-- A top step read from the prologue pieces is the top's step. -/
lemma mkStep_proPieces_lt (i : ℕ) (hi : i < topRowCount) (ev : V) :
    mkStep proPieces (i : V) ev = mkStep topPieces (i : V) ev := by
  rw [mkStep, mkStep, proPieces_nth_lt i hi]

lemma proPieces_setLenSingLe : (proPieces : V).[((pIdx_setLenSingLe : ℕ) : V)] = ppiece_setLenSingLe := by
  unfold proPieces
  rw [nth_vecOf _ pIdx_setLenSingLe (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma pmk_setLenSingLe (ev : V) :
    mkStep proPieces ((pIdx_setLenSingLe : ℕ) : V) ev = sUseHorn ((pIdx_setLenSingLe : ℕ) : V) ev (vecOf row_setLenSingLe_as) row_setLenSingLe_c := by
  rw [mkStep, proPieces_setLenSingLe]
  simp [ppiece_setLenSingLe, sUseHorn]

lemma ptag_setLenSingLe {W : V} (hWp : W = proPieces) (ev : V) : sTag (mkStep W (155 : V) ev) = 0 := by
  subst hWp
  have hk : ((pIdx_setLenSingLe : ℕ) : V) = (155 : V) := by simp [pIdx_setLenSingLe]
  rw [← hk, pmk_setLenSingLe]; simp

/-! ### The per-row applicability lemmas `pok_<row>` (against explicit table readings) -/

/-- Row `setLenSingLe` as a step, against the table readings `hlen`/`hrow` at its index. -/
lemma pok_setLenSingLe {tbl N E Γ W : V} {wx wt wl wlx : V} (htbl : TableOK tbl N) (hWp : W = proPieces)
    (hlen : ((pIdx_setLenSingLe : ℕ) : V) < len tbl)
    (hrow : rowM tbl.[((pIdx_setLenSingLe : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((pIdx_setLenSingLe : ℕ) : V)] = impChainV LAct (vecOf row_setLenSingLe_as) row_setLenSingLe_c)
    (hΓ : IsFormulaSet LAct Γ) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hwt : IsSemiterm LAct 0 wt) (hEwt : termLen LAct wt ≤ E) (hwl : IsSemiterm LAct 0 wl) (hEwl : termLen LAct wl ≤ E) (hwlx : IsSemiterm LAct 0 wlx) (hEwlx : termLen LAct wlx ≤ E) (hmem0 : neg LAct (insFact wt wx (𝟎 : V)) ∈ Γ) (hmem1 : neg LAct (setLenFact wl wt) ∈ Γ) (hmem2 : neg LAct (lenFact wlx wx) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 155 ?[wx, wt, wl, wlx]) ∧ sTag (mkStep W 155 ?[wx, wt, wl, wlx]) = 0 ∧
    ctxAfter Γ (mkStep W 155 ?[wx, wt, wl, wlx]) = insert (neg LAct (leFact wl wlx)) Γ := by
  subst hWp
  have hk : ((pIdx_setLenSingLe : ℕ) : V) = (155 : V) := by simp [pIdx_setLenSingLe]
  have hstep := pmk_setLenSingLe (V := V) ?[wx, wt, wl, wlx]
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wx, wt, wl, wlx], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwx, hEwx⟩, List.forall_mem_cons.mpr ⟨⟨hwt, hEwt⟩, List.forall_mem_cons.mpr ⟨⟨hwl, hEwl⟩, List.forall_mem_cons.mpr ⟨⟨hwlx, hEwlx⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_setLenSingLe hwx hwt hwl hwlx
  rw [hstep, show (?[wx, wt, wl, wlx] : V) = vecOf [wx, wt, wl, wlx] from rfl]
  refine ⟨stepOK_useHorn htbl [wx, wt, wl, wlx] row_setLenSingLe_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_setLenSingLe_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wx, wt, wl, wlx] row_setLenSingLe_as isSemiformula_setLenSingLe_c (fun e he ↦ (hes e he).1), hinst.2]

end proRowsTable

end ArithS
