import ArithS.Necessitation.Verify
import ArithS.Necessitation.Dossier
import ArithS.Necessitation.NumLength
import ArithS.Necessitation.NumMul

/-!
# ArithS.Necessitation.Top — the top (`DESIGN_fragments.md` §7) against an explicit kit

The final assembly of U10: from a `TAct`-proof code `ρ` of the `k`-instance `instB ⌜χ⌝ k` with
`dlen ρ ≤ gBudget k`, a proof code of the `k`-instance of the box `Box_g χ` — i.e. of the sentence
"`instB ⌜χ⌝ k` has a proof of length `≤ g(k)`" — of length `≤ C_χ · ((gBudget k)^3 + 1)`, hence
`BoundedInnerNec 3` (`Assembly/Prep.lean` §6). The verification recursion (`Verify.lean`) still lacks
its prologue producers, so its two theorems (§6.3 `verifySteps_ok`, §6.4 `dlen_verifySteps_le`) do
not exist yet; this file states EXACTLY what the top needs from them as the fields of a `Prop`
structure `VerifyKit`, states the per-`χ` pinning of §7.2 as a second structure `PinKit`, and proves
everything else. `boundedInnerNec_three_of_kit` is the top; discharging the two kits is the
remaining `Verify`/`Cert` work (their docstrings say precisely what).

**Universe.** `V : Type` throughout — `BoundedInnerNec` quantifies over `V : Type`, and several
`InstV` lemmas are stated there. TRAP (found here): a statement like `IsSemiterm LAct 0 (qNum χ)`
with `variable {V : Type}` elaborates the `0` BEFORE `V` is pinned and defaults the whole statement
to `V := ℕ` — which type-checks (ℕ is a model) and is USELESS. Every statement ascribes `V`.

## Contents

* §1 The two new predicate codes (`lenDerivableDef TAct`, `boxCore` through the Σ₁ symbol
  `boxCoreS`/`boxRel`), the three new library rows `gIntroNum`, `lenDerIntro`, `boxIntro` (`Lib`,
  soundness by `pa_proves_of_models`), their pieces/`inst_` lemmas, the table
  `topRows := frag2Rows ++ [dlenDefIntro, proofIntro, gIntroNum, lenDerIntro, boxIntro]` at
  `150 + k` (`TopTable`, `exists_topTable`), the pieces `topPieces`, the step lemmas `tok_<row>`
  and `tfok_leTrans` (GENERATED by the session script `gen_top.py` on the `gen_frag2.py` template).
  Design choice (vs. `DESIGN_fragments.md` §7.1 step 9): the target is closed by ONE Horn row
  `boxIntro “n k g a. gGraph a k → instBGraph g n k → lenDerivableDef a g → boxCore n k”`
  whose conclusion IS the target fact, so the leaf is `axLFactCode` — no `targetLeafCode`.
  Likewise `lenDerIntro` folds `proof`/`dlenDef`/`≤` into `lenDerivableDef`, and `gIntroNum`
  reads the cube from the two numeral products directly (no eigenvariable `l̂`, no congruence glue).
* §2 The target's code shape: `instB ⌜Box_g χ⌝ k = boxFact (qNum χ) (bnum k)` with
  `qNum χ := numeral ⌜χ⌝` the unary numeral of the code of `χ` — proved for a VARIABLE `χ`
  (`quote_Box_g`, `instB_quote_Box_g`, `target_eq_boxFact`); the numeral's closedness, shift law and
  length (`termLen (numeral x) ≤ 2x + 1`).
* §3 The root layout `RootLayout` (what the walk + chain of the root sequent `{x}` deliver), the kits
  `VerifyKit` (§6.3/§6.4/§5 for the RELATION `VerifyGraph`) and `PinKit χ` (§7.1 steps 1–4 / §7.2).
* §4 `rootSteps` — the root layout is produced (`describeF` + `chainSteps` + `dossierAt_of_walk`).
* §5 `closeSteps` — from the recovered root goal to the target fact: the four `sLemma` numeral steps
  (N5, N4 ×2, N2) and the five rows.
* §6 The whole list, `chainCode_proof`, and the cost polynomial.
* §7 `boundedInnerNec_three_of_kit : … → BoundedInnerNec 3`.
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open PeanoMinus ISigma0 ISigma1
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 1. The rows, the table and the pieces (GENERATED — `gen_top.py` on the `gen_frag2.py` template) -/

/-! ### The two new predicate codes: `lenDerivableDef TAct` and `boxCore` -/

/-- `boxCore` as a Σ₁ symbol (an `∃` over two Σ₁ graphs), so that the DSL `!boxCoreS n k` reads through a
`Defined` instance (the `bewB` route) and `simp` never unfolds it under a substitution. -/
noncomputable def boxCoreS : 𝚺₁.Semisentence 2 := .mkSigma “n k. ∃ a, !gGraph a k ∧ !bewBDef a n k”

lemma boxCoreS_val : ((boxCoreS : 𝚺₁.Semisentence 2) : Semisentence ℒₒᵣ 2) = boxCore := rfl

/-- The relation the box core defines: `n k ↦ LenDerivable TAct (gBudget k) (instB n k)` (`eval_boxCore`). -/
def boxRel (n k : V) : Prop := LenDerivable TAct (gBudget k) (instB n k)

instance boxRel.defined : 𝚺₁-Relation[V] boxRel via boxCoreS := .mk fun v ↦ by
  simp [boxCoreS, boxRel, bewB]

/-- The code of `lenDer` (arity 2). -/
noncomputable def PlenDer : V := ⌜Semiformula.lMap emb (↑(lenDerivableDef TAct) : ArithmeticSemisentence 2)⌝
lemma isSemiformula_PlenDer : IsSemiformula LAct ((2 : ℕ) : V) (PlenDer : V) := Sentence.quote_isSemiformula _
lemma shift_PlenDer : shift LAct (PlenDer : V) = PlenDer := shift_quote_sentence _
lemma fvOccF_PlenDer : fvOccF LAct (PlenDer : V) = 0 := fvOccF_quote_sentence _

/-- The code of `box` (arity 2). -/
noncomputable def Pbox : V := ⌜Semiformula.lMap emb (↑boxCoreS : ArithmeticSemisentence 2)⌝
lemma isSemiformula_Pbox : IsSemiformula LAct ((2 : ℕ) : V) (Pbox : V) := Sentence.quote_isSemiformula _
lemma shift_Pbox : shift LAct (Pbox : V) = Pbox := shift_quote_sentence _
lemma fvOccF_Pbox : fvOccF LAct (Pbox : V) = 0 := fvOccF_quote_sentence _

noncomputable def lenDerFact (a g : V) : V := subst LAct (listToVec [a, g]) PlenDer
lemma isFormula_lenDerFact {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) : IsFormula LAct (lenDerFact a g) :=
  isFormula_fact isSemiformula_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨ha, List.forall_mem_cons.mpr ⟨hg, List.forall_mem_nil _⟩⟩)
lemma shift_lenDerFact {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) :
    shift LAct (lenDerFact a g) = lenDerFact (termShift LAct a) (termShift LAct g) := by
  unfold lenDerFact
  rw [shift_subst_listToVec [a, g] isSemiformula_PlenDer shift_PlenDer (n := 0) (List.forall_mem_cons.mpr ⟨ha, List.forall_mem_cons.mpr ⟨hg, List.forall_mem_nil _⟩⟩)]
  rfl
lemma formulaLen_lenDerFact_le {B : V} (hB : 1 ≤ B) {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) (hla : termLen LAct a ≤ B) (hlg : termLen LAct g ≤ B) :
    formulaLen LAct (lenDerFact a g) ≤ formulaLen LAct (PlenDer : V) * B :=
  formulaLen_fact_le hB isSemiformula_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨⟨ha, hla⟩, List.forall_mem_cons.mpr ⟨⟨hg, hlg⟩, List.forall_mem_nil _⟩⟩)
lemma fvOccF_lenDerFact_le {M : V} {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) (hoa : fvOcc LAct a ≤ M) (hog : fvOcc LAct g ≤ M) :
    fvOccF LAct (lenDerFact a g) ≤ bvOccF LAct (PlenDer : V) * M :=
  fvOccF_fact_le isSemiformula_PlenDer fvOccF_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨⟨ha, hoa⟩, List.forall_mem_cons.mpr ⟨⟨hg, hog⟩, List.forall_mem_nil _⟩⟩)

noncomputable def boxFact (n k : V) : V := subst LAct (listToVec [n, k]) Pbox
lemma isFormula_boxFact {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) : IsFormula LAct (boxFact n k) :=
  isFormula_fact isSemiformula_Pbox _ rfl (List.forall_mem_cons.mpr ⟨hn, List.forall_mem_cons.mpr ⟨hk, List.forall_mem_nil _⟩⟩)
lemma shift_boxFact {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) :
    shift LAct (boxFact n k) = boxFact (termShift LAct n) (termShift LAct k) := by
  unfold boxFact
  rw [shift_subst_listToVec [n, k] isSemiformula_Pbox shift_Pbox (n := 0) (List.forall_mem_cons.mpr ⟨hn, List.forall_mem_cons.mpr ⟨hk, List.forall_mem_nil _⟩⟩)]
  rfl
lemma formulaLen_boxFact_le {B : V} (hB : 1 ≤ B) {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) (hln : termLen LAct n ≤ B) (hlk : termLen LAct k ≤ B) :
    formulaLen LAct (boxFact n k) ≤ formulaLen LAct (Pbox : V) * B :=
  formulaLen_fact_le hB isSemiformula_Pbox _ rfl (List.forall_mem_cons.mpr ⟨⟨hn, hln⟩, List.forall_mem_cons.mpr ⟨⟨hk, hlk⟩, List.forall_mem_nil _⟩⟩)
lemma fvOccF_boxFact_le {M : V} {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) (hon : fvOcc LAct n ≤ M) (hok : fvOcc LAct k ≤ M) :
    fvOccF LAct (boxFact n k) ≤ bvOccF LAct (Pbox : V) * M :=
  fvOccF_fact_le isSemiformula_Pbox fvOccF_Pbox _ rfl (List.forall_mem_cons.mpr ⟨⟨hn, hon⟩, List.forall_mem_cons.mpr ⟨⟨hk, hok⟩, List.forall_mem_nil _⟩⟩)

/-! ### The three new library rows (`Lib`), on the `Lib/Frag.lean` template -/

/-- `l = ‖k‖ → l * l = b → b * l = a → a = gBudget k` (the cube through two numeral products, §7.1 step 8). -/
noncomputable def gIntroNumB : ArithmeticSemisentence 4 :=
  “a b l k. !lengthDef l k → (l * l) = b → (b * l) = a → !gGraph a k”
noncomputable def gIntroNum : ArithmeticSentence := ∀¹* gIntroNumB
lemma models_gIntroNum : V↓[ℒₒᵣ] ⊧ gIntroNum ↔ ∀ a b l k : V, l = ‖k‖ → (l * l) = b → (b * l) = a → a = gBudget k := by
  simp [gIntroNum, gIntroNumB, models_iff, Matrix.vecForall_iff, length_defined.iff, gBudget.defined.iff]
theorem pa_proves_gIntroNum : 𝗣𝗔 ⊢ gIntroNum :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_gIntroNum.mpr fun _ _ _ _ h1 h2 h3 ↦ by subst_vars; first | rfl | assumption | trivial
theorem lib_gIntroNum : Lib gIntroNum := Lib.of_pa pa_proves_gIntroNum

/-- `proof d g → n = dlen d → n ≤ a → LenDerivable a g` (§7.1 step 7, folded). -/
noncomputable def lenDerIntroB : ArithmeticSemisentence 4 :=
  “a g n d. !(proof TAct).sigma d g → !(dlenDef TAct) n d → n ≤ a → !(lenDerivableDef TAct) a g”
noncomputable def lenDerIntro : ArithmeticSentence := ∀¹* lenDerIntroB
lemma models_lenDerIntro : V↓[ℒₒᵣ] ⊧ lenDerIntro ↔ ∀ a g n d : V, Proof TAct d g → n = dlen TAct d → n ≤ a → LenDerivable TAct a g := by
  simp [lenDerIntro, lenDerIntroB, models_iff, Matrix.vecForall_iff, dlen_defined.iff, (LenDerivable.defined (V := V) TAct).iff]
theorem pa_proves_lenDerIntro : 𝗣𝗔 ⊢ lenDerIntro :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_lenDerIntro.mpr fun _ _ _ _ h₁ h₂ h₃ ↦ by exact ⟨_, h₁, by rw [← h₂]; exact h₃⟩
theorem lib_lenDerIntro : Lib lenDerIntro := Lib.of_pa pa_proves_lenDerIntro

/-- `a = gBudget k → g = instB n k → LenDerivable a g → boxCore n k` — the target's ONE closing row (§7.1 step 9, as a row). -/
noncomputable def boxIntroB : ArithmeticSemisentence 4 :=
  “n k g a. !gGraph a k → !instBGraph g n k → !(lenDerivableDef TAct) a g → !boxCoreS n k”
noncomputable def boxIntro : ArithmeticSentence := ∀¹* boxIntroB
lemma models_boxIntro : V↓[ℒₒᵣ] ⊧ boxIntro ↔ ∀ n k g a : V, a = gBudget k → g = instB n k → LenDerivable TAct a g → LenDerivable TAct (gBudget k) (instB n k) := by
  simp [boxIntro, boxIntroB, models_iff, Matrix.vecForall_iff, gBudget.defined.iff, instB.defined.iff, (LenDerivable.defined (V := V) TAct).iff, boxRel.defined.iff, boxRel]
theorem pa_proves_boxIntro : 𝗣𝗔 ⊢ boxIntro :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_boxIntro.mpr fun _ _ _ _ h1 h2 h3 ↦ by subst_vars; first | rfl | assumption | trivial
theorem lib_boxIntro : Lib boxIntro := Lib.of_pa pa_proves_boxIntro

/-! ### The rows as pieces: `row_<r>_as`/`_c`, `quote_row_<r>`, `inst_<r>` (the `RowInstB` template) -/

/-! ### `gIntroNum` — `“a b l k. …”`, `m = 4` -/

noncomputable def row_gIntroNum_as : List V := [subst LAct (listToVec [bv 2, bv 3]) Plength, subst LAct (listToVec [(bv 2 ^* bv 2), bv 1]) PeqB, subst LAct (listToVec [(bv 1 ^* bv 2), bv 0]) PeqB]
noncomputable def row_gIntroNum_c : V := subst LAct (listToVec [bv 0, bv 3]) Pg

theorem quote_row_gIntroNum : (⌜Semiformula.lMap emb gIntroNumB⌝ : V) = impChain LAct row_gIntroNum_as row_gIntroNum_c := by
  unfold gIntroNumB row_gIntroNum_as row_gIntroNum_c PeqB Pg Plength
  all_goals row_shapeB

lemma isSemiformula_gIntroNum_as : ∀ A ∈ row_gIntroNum_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_gIntroNum_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Plength _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_gIntroNum_c : IsSemiformula LAct ((4 : ℕ) : V) row_gIntroNum_c := by
  unfold row_gIntroNum_c
  exact isSemiformula_substRow isSemiformula_Pg _ (by rfl) (by row_entriesB)

/-- `gIntroNum` at the witnesses `[wk, wl, wb, wa]` (the DSL variables right-to-left). -/
lemma inst_gIntroNum {wk wl wb wa : V} (hwk : IsSemiterm LAct 0 wk) (hwl : IsSemiterm LAct 0 wl) (hwb : IsSemiterm LAct 0 wb) (hwa : IsSemiterm LAct 0 wa) :
    row_gIntroNum_as.map (instOuter LAct [wk, wl, wb, wa]) = [lengthFact wl wk, eqFactB (wl ^* wl) wb, eqFactB (wb ^* wl) wa] ∧
    instOuter LAct [wk, wl, wb, wa] row_gIntroNum_c = gFact wa wk := by
  have hes : ∀ e ∈ ([wk, wl, wb, wa] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwk, List.forall_mem_cons.mpr ⟨hwl, List.forall_mem_cons.mpr ⟨hwb, List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_gIntroNum_as row_gIntroNum_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Plength (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pg (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `lenDerIntro` — `“a g n d. …”`, `m = 4` -/

noncomputable def row_lenDerIntro_as : List V := [subst LAct (listToVec [bv 3, bv 1]) Pproof, subst LAct (listToVec [bv 2, bv 3]) PdlenDef, subst LAct (listToVec [bv 2, bv 0]) Ple]
noncomputable def row_lenDerIntro_c : V := subst LAct (listToVec [bv 0, bv 1]) PlenDer

theorem quote_row_lenDerIntro : (⌜Semiformula.lMap emb lenDerIntroB⌝ : V) = impChain LAct row_lenDerIntro_as row_lenDerIntro_c := by
  unfold lenDerIntroB row_lenDerIntro_as row_lenDerIntro_c PdlenDef Ple PlenDer Pproof leS
  all_goals row_shapeB

lemma isSemiformula_lenDerIntro_as : ∀ A ∈ row_lenDerIntro_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_lenDerIntro_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pproof _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PdlenDef _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_lenDerIntro_c : IsSemiformula LAct ((4 : ℕ) : V) row_lenDerIntro_c := by
  unfold row_lenDerIntro_c
  exact isSemiformula_substRow isSemiformula_PlenDer _ (by rfl) (by row_entriesB)

/-- `lenDerIntro` at the witnesses `[wd, wn, wg, wa]` (the DSL variables right-to-left). -/
lemma inst_lenDerIntro {wd wn wg wa : V} (hwd : IsSemiterm LAct 0 wd) (hwn : IsSemiterm LAct 0 wn) (hwg : IsSemiterm LAct 0 wg) (hwa : IsSemiterm LAct 0 wa) :
    row_lenDerIntro_as.map (instOuter LAct [wd, wn, wg, wa]) = [proofFact wd wg, dlenDefFact wn wd, leFact wn wa] ∧
    instOuter LAct [wd, wn, wg, wa] row_lenDerIntro_c = lenDerFact wa wg := by
  have hes : ∀ e ∈ ([wd, wn, wg, wa] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwd, List.forall_mem_cons.mpr ⟨hwn, List.forall_mem_cons.mpr ⟨hwg, List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_lenDerIntro_as row_lenDerIntro_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pproof (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PdlenDef (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PlenDer (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `boxIntro` — `“n k g a. …”`, `m = 4` -/

noncomputable def row_boxIntro_as : List V := [subst LAct (listToVec [bv 3, bv 1]) Pg, subst LAct (listToVec [bv 2, bv 0, bv 1]) PinstB, subst LAct (listToVec [bv 3, bv 2]) PlenDer]
noncomputable def row_boxIntro_c : V := subst LAct (listToVec [bv 0, bv 1]) Pbox

theorem quote_row_boxIntro : (⌜Semiformula.lMap emb boxIntroB⌝ : V) = impChain LAct row_boxIntro_as row_boxIntro_c := by
  unfold boxIntroB row_boxIntro_as row_boxIntro_c Pbox Pg PinstB PlenDer
  all_goals row_shapeB

lemma isSemiformula_boxIntro_as : ∀ A ∈ row_boxIntro_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_boxIntro_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pg _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PinstB _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PlenDer _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_boxIntro_c : IsSemiformula LAct ((4 : ℕ) : V) row_boxIntro_c := by
  unfold row_boxIntro_c
  exact isSemiformula_substRow isSemiformula_Pbox _ (by rfl) (by row_entriesB)

/-- `boxIntro` at the witnesses `[wa, wg, wk, wn]` (the DSL variables right-to-left). -/
lemma inst_boxIntro {wa wg wk wn : V} (hwa : IsSemiterm LAct 0 wa) (hwg : IsSemiterm LAct 0 wg) (hwk : IsSemiterm LAct 0 wk) (hwn : IsSemiterm LAct 0 wn) :
    row_boxIntro_as.map (instOuter LAct [wa, wg, wk, wn]) = [gFact wa wk, instBFact wg wn wk, lenDerFact wa wg] ∧
    instOuter LAct [wa, wg, wk, wn] row_boxIntro_c = boxFact wn wk := by
  have hes : ∀ e ∈ ([wa, wg, wk, wn] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_cons.mpr ⟨hwg, List.forall_mem_cons.mpr ⟨hwk, List.forall_mem_cons.mpr ⟨hwn, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_boxIntro_as row_boxIntro_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pg (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PinstB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PlenDer (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pbox (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### The top table: the Frag2 rows, then the five top rows at `150 + k` -/

section topTable

def tIdx_dlenDefIntro : ℕ := 150
def tIdx_proofIntro : ℕ := 151
def tIdx_gIntroNum : ℕ := 152
def tIdx_lenDerIntro : ℕ := 153
def tIdx_boxIntro : ℕ := 154
def topRowCount : ℕ := 155

/-- The rows at `150 + k`, in index order. -/
noncomputable def topExtraRows : List WRow := [
  ⟨2, dlenDefIntroB, lib_dlenDefIntro⟩,
  ⟨3, proofIntroB, lib_proofIntro⟩,
  ⟨4, gIntroNumB, lib_gIntroNum⟩,
  ⟨4, lenDerIntroB, lib_lenDerIntro⟩,
  ⟨4, boxIntroB, lib_boxIntro⟩
]

/-- The top table's rows: Frag2's, then the five top rows. -/
noncomputable def topRows : List WRow := frag2Rows ++ topExtraRows

lemma topRows_length : topRows.length = topRowCount := rfl

/-- **The top proof table**: `topRowCount` rows at least, the `i`-th with the arity and the matrix of
`topRows[i]`. -/
def TopTable (tbl : V) : Prop :=
  (topRowCount : V) ≤ len tbl ∧
  ∀ (i : ℕ) (h : i < topRows.length),
    rowM tbl.[(i : V)] = ((topRows[i]).m : V) ∧ rowB tbl.[(i : V)] = ⌜Semiformula.lMap emb (topRows[i]).B⌝

/-- A top table is a fragment-2 table (the first 150 rows). -/
lemma TopTable.frag2Table {tbl : V} (h : TopTable tbl) : Frag2Table tbl := by
  refine ⟨le_trans (by exact_mod_cast (by decide : frag2RowCount ≤ topRowCount)) h.1, ?_⟩
  intro i hi
  have hi' : i < topRows.length := by
    rw [topRows_length]; exact lt_of_lt_of_le (frag2Rows_length ▸ hi) (by decide)
  have := h.2 i hi'
  rwa [show topRows[i] = frag2Rows[i] from List.getElem_append_left hi] at this

lemma TopTable.frag1Table {tbl : V} (h : TopTable tbl) : Frag1Table tbl := h.frag2Table.frag1Table
lemma TopTable.layoutTable {tbl : V} (h : TopTable tbl) : LayoutTable tbl := h.frag2Table.layoutTable
lemma TopTable.walkTable {tbl : V} (h : TopTable tbl) : WalkTable tbl := h.frag2Table.walkTable

/-- **The top proof table exists in every model, with one standard length bound.** -/
theorem exists_topTable : ∃ N : ℕ, ∀ (V : Type) [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁],
    ∃ tbl : V, TableOK tbl (N : V) ∧ TopTable tbl := by
  obtain ⟨N, hN⟩ := exists_rows topRows
  refine ⟨N, fun V _ _ ↦ ?_⟩
  obtain ⟨rows, hlen, hok, hidx⟩ := hN V
  refine ⟨vecOf rows, tableOK_vecOf rows hok, ?_, ?_⟩
  · rw [len_vecOf, hlen, topRows_length]
  · intro i h
    have h' : i < rows.length := by rw [hlen]; exact h
    rw [nth_vecOf rows i h']
    exact hidx i h h'

lemma topTable_len {tbl : V} (h : TopTable tbl) (i : ℕ) (hi : i < topRowCount) : ((i : ℕ) : V) < len tbl :=
  lt_of_lt_of_le (by exact_mod_cast hi) h.1

/-! ### The per-row readings of `TopTable` -/

lemma topTable_dlenDefIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ((2 : ℕ) : V) ∧
    rowB tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = impChainV LAct (vecOf row_dlenDefIntro_as) row_dlenDefIntro_c := by
  have this : rowM tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ((2 : ℕ) : V) ∧
      rowB tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ⌜Semiformula.lMap emb dlenDefIntroB⌝ :=
    h.2 tIdx_dlenDefIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_dlenDefIntro]

lemma topTable_proofIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_proofIntro : ℕ) : V)] = ((3 : ℕ) : V) ∧
    rowB tbl.[((tIdx_proofIntro : ℕ) : V)] = impChainV LAct (vecOf row_proofIntro_as) row_proofIntro_c := by
  have this : rowM tbl.[((tIdx_proofIntro : ℕ) : V)] = ((3 : ℕ) : V) ∧
      rowB tbl.[((tIdx_proofIntro : ℕ) : V)] = ⌜Semiformula.lMap emb proofIntroB⌝ :=
    h.2 tIdx_proofIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_proofIntro]

lemma topTable_gIntroNum {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_gIntroNum : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_gIntroNum : ℕ) : V)] = impChainV LAct (vecOf row_gIntroNum_as) row_gIntroNum_c := by
  have this : rowM tbl.[((tIdx_gIntroNum : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_gIntroNum : ℕ) : V)] = ⌜Semiformula.lMap emb gIntroNumB⌝ :=
    h.2 tIdx_gIntroNum (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_gIntroNum]

lemma topTable_lenDerIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_lenDerIntro : ℕ) : V)] = impChainV LAct (vecOf row_lenDerIntro_as) row_lenDerIntro_c := by
  have this : rowM tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ⌜Semiformula.lMap emb lenDerIntroB⌝ :=
    h.2 tIdx_lenDerIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_lenDerIntro]

lemma topTable_boxIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_boxIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_boxIntro : ℕ) : V)] = impChainV LAct (vecOf row_boxIntro_as) row_boxIntro_c := by
  have this : rowM tbl.[((tIdx_boxIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_boxIntro : ℕ) : V)] = ⌜Semiformula.lMap emb boxIntroB⌝ :=
    h.2 tIdx_boxIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_boxIntro]

/-! ### The piece table -/

noncomputable def tpiece_dlenDefIntro : V := ⟪(0 : V), vecOf row_dlenDefIntro_as, row_dlenDefIntro_c⟫
noncomputable def tpiece_proofIntro : V := ⟪(0 : V), vecOf row_proofIntro_as, row_proofIntro_c⟫
noncomputable def tpiece_gIntroNum : V := ⟪(0 : V), vecOf row_gIntroNum_as, row_gIntroNum_c⟫
noncomputable def tpiece_lenDerIntro : V := ⟪(0 : V), vecOf row_lenDerIntro_as, row_lenDerIntro_c⟫
noncomputable def tpiece_boxIntro : V := ⟪(0 : V), vecOf row_boxIntro_as, row_boxIntro_c⟫

noncomputable def topExtraPieceList : List V := [
  tpiece_dlenDefIntro,
  tpiece_proofIntro,
  tpiece_gIntroNum,
  tpiece_lenDerIntro,
  tpiece_boxIntro
]

/-- **The piece table of the top**: Frag2's pieces, then the top rows' pieces. -/
noncomputable def topPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList)

lemma topPieces_nth_lt (i : ℕ) (hi : i < frag2RowCount) : (topPieces : V).[(i : V)] = (frag2Pieces : V).[(i : V)] := by
  unfold topPieces frag2Pieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length = topRowCount from rfl]
    exact lt_of_lt_of_le hi (by decide)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList : List V).length = frag2RowCount from rfl]; exact hi
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact List.getElem_append_left h2

/-- A Frag2 step read from the top pieces is Frag2's step. -/
lemma mkStep_topPieces_lt (i : ℕ) (hi : i < frag2RowCount) (ev : V) :
    mkStep topPieces (i : V) ev = mkStep frag2Pieces (i : V) ev := by
  rw [mkStep, mkStep, topPieces_nth_lt i hi]

lemma topPieces_dlenDefIntro : (topPieces : V).[((tIdx_dlenDefIntro : ℕ) : V)] = tpiece_dlenDefIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_dlenDefIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_dlenDefIntro (ev : V) :
    mkStep topPieces ((tIdx_dlenDefIntro : ℕ) : V) ev = sUseHorn ((tIdx_dlenDefIntro : ℕ) : V) ev (vecOf row_dlenDefIntro_as) row_dlenDefIntro_c := by
  rw [mkStep, topPieces_dlenDefIntro]
  simp [tpiece_dlenDefIntro, sUseHorn]

lemma ttag_dlenDefIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (150 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_dlenDefIntro : ℕ) : V) = (150 : V) := by simp [tIdx_dlenDefIntro]
  rw [← hk, tmk_dlenDefIntro]; simp

lemma topPieces_proofIntro : (topPieces : V).[((tIdx_proofIntro : ℕ) : V)] = tpiece_proofIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_proofIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_proofIntro (ev : V) :
    mkStep topPieces ((tIdx_proofIntro : ℕ) : V) ev = sUseHorn ((tIdx_proofIntro : ℕ) : V) ev (vecOf row_proofIntro_as) row_proofIntro_c := by
  rw [mkStep, topPieces_proofIntro]
  simp [tpiece_proofIntro, sUseHorn]

lemma ttag_proofIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (151 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_proofIntro : ℕ) : V) = (151 : V) := by simp [tIdx_proofIntro]
  rw [← hk, tmk_proofIntro]; simp

lemma topPieces_gIntroNum : (topPieces : V).[((tIdx_gIntroNum : ℕ) : V)] = tpiece_gIntroNum := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_gIntroNum (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_gIntroNum (ev : V) :
    mkStep topPieces ((tIdx_gIntroNum : ℕ) : V) ev = sUseHorn ((tIdx_gIntroNum : ℕ) : V) ev (vecOf row_gIntroNum_as) row_gIntroNum_c := by
  rw [mkStep, topPieces_gIntroNum]
  simp [tpiece_gIntroNum, sUseHorn]

lemma ttag_gIntroNum {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (152 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_gIntroNum : ℕ) : V) = (152 : V) := by simp [tIdx_gIntroNum]
  rw [← hk, tmk_gIntroNum]; simp

lemma topPieces_lenDerIntro : (topPieces : V).[((tIdx_lenDerIntro : ℕ) : V)] = tpiece_lenDerIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_lenDerIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_lenDerIntro (ev : V) :
    mkStep topPieces ((tIdx_lenDerIntro : ℕ) : V) ev = sUseHorn ((tIdx_lenDerIntro : ℕ) : V) ev (vecOf row_lenDerIntro_as) row_lenDerIntro_c := by
  rw [mkStep, topPieces_lenDerIntro]
  simp [tpiece_lenDerIntro, sUseHorn]

lemma ttag_lenDerIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (153 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_lenDerIntro : ℕ) : V) = (153 : V) := by simp [tIdx_lenDerIntro]
  rw [← hk, tmk_lenDerIntro]; simp

lemma topPieces_boxIntro : (topPieces : V).[((tIdx_boxIntro : ℕ) : V)] = tpiece_boxIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_boxIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_boxIntro (ev : V) :
    mkStep topPieces ((tIdx_boxIntro : ℕ) : V) ev = sUseHorn ((tIdx_boxIntro : ℕ) : V) ev (vecOf row_boxIntro_as) row_boxIntro_c := by
  rw [mkStep, topPieces_boxIntro]
  simp [tpiece_boxIntro, sUseHorn]

lemma ttag_boxIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (154 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_boxIntro : ℕ) : V) = (154 : V) := by simp [tIdx_boxIntro]
  rw [← hk, tmk_boxIntro]; simp

/-! ### The per-row applicability lemmas `tok_<row>` -/

/-- Row `dlenDefIntro` as a step. -/
lemma tok_dlenDefIntro {tbl N E Γ W : V} {wd wn : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hmem0 : neg LAct (derFact wd) ∈ Γ) (hmem1 : neg LAct (dlenFact wd wn) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 150 ?[wd, wn]) ∧ sTag (mkStep W 150 ?[wd, wn]) = 0 ∧
    ctxAfter Γ (mkStep W 150 ?[wd, wn]) = insert (neg LAct (dlenDefFact wn wd)) Γ := by
  subst hWp
  have hk : ((tIdx_dlenDefIntro : ℕ) : V) = (150 : V) := by simp [tIdx_dlenDefIntro]
  have hstep := tmk_dlenDefIntro (V := V) ?[wd, wn]
  have hlen := topTable_len hT tIdx_dlenDefIntro (by decide)
  have hrow := topTable_dlenDefIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wd, wn], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_nil _⟩⟩
  have hinst := inst_dlenDefIntro hwd hwn
  rw [hstep, show (?[wd, wn] : V) = vecOf [wd, wn] from rfl]
  refine ⟨stepOK_useHorn htbl [wd, wn] row_dlenDefIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 2 ≤ 8))
    (by rw [show row_dlenDefIntro_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wd, wn] row_dlenDefIntro_as isSemiformula_dlenDefIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `proofIntro` as a step. -/
lemma tok_proofIntro {tbl N E Γ W : V} {ws wg wd : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hws : IsSemiterm LAct 0 ws) (hEws : termLen LAct ws ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hmem0 : neg LAct (insFact ws wg (𝟎 : V)) ∈ Γ) (hmem1 : neg LAct (fstIdxFact ws wd) ∈ Γ) (hmem2 : neg LAct (derFact wd) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 151 ?[ws, wg, wd]) ∧ sTag (mkStep W 151 ?[ws, wg, wd]) = 0 ∧
    ctxAfter Γ (mkStep W 151 ?[ws, wg, wd]) = insert (neg LAct (proofFact wd wg)) Γ := by
  subst hWp
  have hk : ((tIdx_proofIntro : ℕ) : V) = (151 : V) := by simp [tIdx_proofIntro]
  have hstep := tmk_proofIntro (V := V) ?[ws, wg, wd]
  have hlen := topTable_len hT tIdx_proofIntro (by decide)
  have hrow := topTable_proofIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [ws, wg, wd], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hws, hEws⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_nil _⟩⟩⟩
  have hinst := inst_proofIntro hws hwg hwd
  rw [hstep, show (?[ws, wg, wd] : V) = vecOf [ws, wg, wd] from rfl]
  refine ⟨stepOK_useHorn htbl [ws, wg, wd] row_proofIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 3 ≤ 8))
    (by rw [show row_proofIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [ws, wg, wd] row_proofIntro_as isSemiformula_proofIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `gIntroNum` as a step. -/
lemma tok_gIntroNum {tbl N E Γ W : V} {wk wl wb wa : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwk : IsSemiterm LAct 0 wk) (hEwk : termLen LAct wk ≤ E) (hwl : IsSemiterm LAct 0 wl) (hEwl : termLen LAct wl ≤ E) (hwb : IsSemiterm LAct 0 wb) (hEwb : termLen LAct wb ≤ E) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hmem0 : neg LAct (lengthFact wl wk) ∈ Γ) (hmem1 : neg LAct (eqFactB (wl ^* wl) wb) ∈ Γ) (hmem2 : neg LAct (eqFactB (wb ^* wl) wa) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 152 ?[wk, wl, wb, wa]) ∧ sTag (mkStep W 152 ?[wk, wl, wb, wa]) = 0 ∧
    ctxAfter Γ (mkStep W 152 ?[wk, wl, wb, wa]) = insert (neg LAct (gFact wa wk)) Γ := by
  subst hWp
  have hk : ((tIdx_gIntroNum : ℕ) : V) = (152 : V) := by simp [tIdx_gIntroNum]
  have hstep := tmk_gIntroNum (V := V) ?[wk, wl, wb, wa]
  have hlen := topTable_len hT tIdx_gIntroNum (by decide)
  have hrow := topTable_gIntroNum hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wk, wl, wb, wa], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwk, hEwk⟩, List.forall_mem_cons.mpr ⟨⟨hwl, hEwl⟩, List.forall_mem_cons.mpr ⟨⟨hwb, hEwb⟩, List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_gIntroNum hwk hwl hwb hwa
  rw [hstep, show (?[wk, wl, wb, wa] : V) = vecOf [wk, wl, wb, wa] from rfl]
  refine ⟨stepOK_useHorn htbl [wk, wl, wb, wa] row_gIntroNum_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_gIntroNum_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wk, wl, wb, wa] row_gIntroNum_as isSemiformula_gIntroNum_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `lenDerIntro` as a step. -/
lemma tok_lenDerIntro {tbl N E Γ W : V} {wd wn wg wa : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hmem0 : neg LAct (proofFact wd wg) ∈ Γ) (hmem1 : neg LAct (dlenDefFact wn wd) ∈ Γ) (hmem2 : neg LAct (leFact wn wa) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 153 ?[wd, wn, wg, wa]) ∧ sTag (mkStep W 153 ?[wd, wn, wg, wa]) = 0 ∧
    ctxAfter Γ (mkStep W 153 ?[wd, wn, wg, wa]) = insert (neg LAct (lenDerFact wa wg)) Γ := by
  subst hWp
  have hk : ((tIdx_lenDerIntro : ℕ) : V) = (153 : V) := by simp [tIdx_lenDerIntro]
  have hstep := tmk_lenDerIntro (V := V) ?[wd, wn, wg, wa]
  have hlen := topTable_len hT tIdx_lenDerIntro (by decide)
  have hrow := topTable_lenDerIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wd, wn, wg, wa], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_lenDerIntro hwd hwn hwg hwa
  rw [hstep, show (?[wd, wn, wg, wa] : V) = vecOf [wd, wn, wg, wa] from rfl]
  refine ⟨stepOK_useHorn htbl [wd, wn, wg, wa] row_lenDerIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_lenDerIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wd, wn, wg, wa] row_lenDerIntro_as isSemiformula_lenDerIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `boxIntro` as a step. -/
lemma tok_boxIntro {tbl N E Γ W : V} {wa wg wk wn : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwk : IsSemiterm LAct 0 wk) (hEwk : termLen LAct wk ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hmem0 : neg LAct (gFact wa wk) ∈ Γ) (hmem1 : neg LAct (instBFact wg wn wk) ∈ Γ) (hmem2 : neg LAct (lenDerFact wa wg) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 154 ?[wa, wg, wk, wn]) ∧ sTag (mkStep W 154 ?[wa, wg, wk, wn]) = 0 ∧
    ctxAfter Γ (mkStep W 154 ?[wa, wg, wk, wn]) = insert (neg LAct (boxFact wn wk)) Γ := by
  subst hWp
  have hk : ((tIdx_boxIntro : ℕ) : V) = (154 : V) := by simp [tIdx_boxIntro]
  have hstep := tmk_boxIntro (V := V) ?[wa, wg, wk, wn]
  have hlen := topTable_len hT tIdx_boxIntro (by decide)
  have hrow := topTable_boxIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wa, wg, wk, wn], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwk, hEwk⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_boxIntro hwa hwg hwk hwn
  rw [hstep, show (?[wa, wg, wk, wn] : V) = vecOf [wa, wg, wk, wn] from rfl]
  refine ⟨stepOK_useHorn htbl [wa, wg, wk, wn] row_boxIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_boxIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wa, wg, wk, wn] row_boxIntro_as isSemiformula_boxIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-! ### The Frag1 row `leTrans` (110), read from the top pieces -/

lemma tfok_leTrans {tbl N E Γ W : V} {wz wy wx : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwz : IsSemiterm LAct 0 wz) (hEwz : termLen LAct wz ≤ E) (hwy : IsSemiterm LAct 0 wy) (hEwy : termLen LAct wy ≤ E) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hmem0 : neg LAct (leFact wx wy) ∈ Γ) (hmem1 : neg LAct (leFact wy wz) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 110 ?[wz, wy, wx]) ∧ sTag (mkStep W 110 ?[wz, wy, wx]) = 0 ∧
    ctxAfter Γ (mkStep W 110 ?[wz, wy, wx]) = insert (neg LAct (leFact wx wz)) Γ := by
  subst hWp
  have e : ∀ ev : V, mkStep topPieces (110 : V) ev = mkStep frag1Pieces (110 : V) ev := fun ev ↦ by
    have h1 := mkStep_topPieces_lt 110 (by decide) ev
    have h2 := mkStep_frag2Pieces_lt 110 (by decide) ev
    simp only [Nat.cast_ofNat] at h1 h2; rw [h1, h2]
  rw [e]
  exact fok_leTrans htbl hT.frag1Table rfl hΓ hwz hEwz hwy hEwy hwx hEwx hmem0 hmem1

end topTable

/-! ## 2. The target's code shape (for a VARIABLE `χ` — no closed quote is ever unfolded) -/

section targetShape

noncomputable def qNum (χ : Semisentence LAct 1) : V := numeral (⌜χ⌝ : V)

lemma isSemiterm_qNum (χ : Semisentence LAct 1) : IsSemiterm LAct (0 : V) (qNum χ) :=
  InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)

theorem quote_Box_g (χ : Semisentence LAct 1) :
    (⌜Box_g χ⌝ : V) = subst LAct (qNum χ ∷ ^#0 ∷ 0) Pbox := by
  rw [Box_g_def]
  conv_lhs =>
    rw [Sentence.quote_def, Semiformula.coe_subst_eq_subst_coe, Semiformula.quote_def,
      Semiformula.typed_quote_substs, Bootstrapping.Semiformula.val_substs, ← Semiformula.quote_def,
      ← Sentence.quote_def]
  unfold Pbox
  congr 1
  have hv : (fun i ↦ (⌜(Rew.emb (![Semiterm.lMap emb (⌜χ⌝ : ArithmeticSemiterm Empty 1), #0] i) :
      SyntacticSemiterm LAct 1)⌝ : Bootstrapping.Semiterm V LAct 1)) =
      ![⌜(Rew.emb (Semiterm.lMap emb (⌜χ⌝ : ArithmeticSemiterm Empty 1)) : SyntacticSemiterm LAct 1)⌝,
        ⌜(Rew.emb (#0 : Semiterm LAct Empty 1) : SyntacticSemiterm LAct 1)⌝] := by
    funext i; fin_cases i <;> rfl
  rw [hv]
  simp only [SemitermVec.val_cons, SemitermVec.val_nil, Diag.typed_val_emb, quote_lMap_gödel]
  rfl

lemma termShift_numeral_LAct (x : V) : termShift LAct (numeral x) = numeral x := by
  induction x using ISigma1.sigma1_succ_induction
  · definability
  case zero => rw [numeral_zero, termShift_qqZero isFunc_LAct_zeroIndex]
  case succ x ih =>
    rcases zero_or_succ x with (rfl | ⟨x, rfl⟩)
    · rw [zero_add, numeral_one, termShift_qqOne isFunc_LAct_oneIndex]
    · rw [numeral_add_two, termShift_qqAdd isFunc_LAct_addIndex
        (InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)).isUTerm qqOne_uterm_LAct, ih,
        termShift_qqOne isFunc_LAct_oneIndex]

lemma termLen_numeral_le (x : V) : termLen LAct (numeral x) ≤ 2 * x + 1 := by
  induction x using ISigma1.sigma1_succ_induction
  · definability
  case zero => rw [numeral_zero, termLen_qqZero isFunc_LAct_zeroIndex]; simp
  case succ x ih =>
    rcases zero_or_succ x with (rfl | ⟨x, rfl⟩)
    · rw [zero_add, numeral_one, termLen_qqOne isFunc_LAct_oneIndex]; simp
    · rw [numeral_add_two, termLen_qqAdd isFunc_LAct_addIndex
        (InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)).isUTerm qqOne_uterm_LAct,
        termLen_qqOne isFunc_LAct_oneIndex]
      calc termLen LAct (numeral (x + 1)) + 1 + 1 ≤ 2 * (x + 1) + 1 + 1 + 1 := by
            exact add_le_add (add_le_add ih le_rfl) le_rfl
        _ = 2 * (x + 1 + 1) + 1 := by ring

theorem instB_quote_Box_g (χ : Semisentence LAct 1) (k : V) :
    instB (⌜Box_g χ⌝ : V) k = subst LAct (qNum χ ∷ bnum k ∷ 0) Pbox := by
  rw [quote_Box_g, instB]
  have hq : IsSemiterm LAct ((0 : V) + 1) (qNum χ) := InstV.isSemiterm_LAct_of_LOR (numeral_semiterm ((0 : V) + 1) _)
  have hb : IsSemiterm LAct ((0 : V) + 1) (^#0 : V) := by simp
  have hv : IsSemitermVec LAct ((0 : V) + 1 + 1) ((0 : V) + 1) (qNum χ ∷ ^#0 ∷ (0 : V)) :=
    IsSemitermVec.adjoin (IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)) hb) hq
  have hw : IsSemitermVec LAct ((0 : V) + 1) (0 : V) (bnum k ∷ (0 : V)) :=
    IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) (0 : V)) (bnum_term_LAct k)
  have h2 : ((2 : ℕ) : V) = 0 + 1 + 1 := by simp [one_add_one_eq_two]
  rw [substs_substs (h2 ▸ isSemiformula_Pbox) hw hv]
  congr 1
  rw [termSubstVec_cons hq.isUTerm (IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)) hb).isUTerm,
    termSubstVec_cons hb.isUTerm (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)).isUTerm, termSubstVec_nil, termSubst_bvar,
    termSubst_eq_self (L := LAct) (w := bnum k ∷ (0 : V)) (isSemiterm_qNum χ) (fun i hi ↦ by simp at hi)]
  simp


/-- **The target IS the `boxIntro` fact**: `instB ⌜Box_g χ⌝ k = boxFact (qNum χ) (bnum k)`. -/
theorem target_eq_boxFact (χ : Semisentence LAct 1) (k : V) :
    instB (⌜Box_g χ⌝ : V) k = boxFact (qNum χ) (bnum k) :=
  instB_quote_Box_g χ k

lemma termShift_qNum (χ : Semisentence LAct 1) : termShift LAct (qNum χ : V) = qNum χ :=
  termShift_numeral_LAct _

/-- The numeral's length is a STANDARD constant of `χ`: `≤ 2·⌜χ⌝ + 1` with `⌜χ⌝ : ℕ` cast. -/
lemma termLen_qNum_le (χ : Semisentence LAct 1) :
    termLen LAct (qNum χ : V) ≤ ((2 * (⌜χ⌝ : ℕ) + 1 : ℕ) : V) := by
  unfold qNum
  push_cast
  rw [Sentence.coe_quote_eq_quote χ]
  exact termLen_numeral_le _

end targetShape

end ArithS
