import ArithS.Necessitation.Verify
import ArithS.Necessitation.Dossier
import ArithS.Necessitation.NumLength
import ArithS.Necessitation.NumMul

/-!
# ArithS.Necessitation.Top — the top (`DESIGN_fragments.md` §7) against an explicit kit

The final assembly of U10: from a `TAct`-proof code `ρ` of the `k`-instance `instB ⌜χ⌝ k` with
`dlen ρ ≤ gBudget k`, a proof code of the `k`-instance of the box `Box_g χ` — i.e. of the sentence
"`instB ⌜χ⌝ k` has a proof of length `≤ g(k)`" — of length `≤ C_χ · ((gBudget k)^3 + 1)`, hence
`BoundedInnerNec 3` (`Assembly/Prep.lean` §6). The verification recursion (`Verify.lean`) still lacks
its prologue producers, so its two theorems (§6.3 `verifySteps_ok`, §6.4 `dlen_verifySteps_le`) do
not exist yet; this file states EXACTLY what the top needs from them as the fields of a `Prop`
structure `VerifyKit`, states the per-`χ` pinning of §7.2 as a second structure `PinKit`, and proves
everything else. `boundedInnerNec_three_of_kit` is the top; discharging the two kits is the
remaining `Verify`/`Cert` work (their docstrings say precisely what).

**Universe.** `V : Type` throughout — `BoundedInnerNec` quantifies over `V : Type`, and several
`InstV` lemmas are stated there. TRAP (found here): a statement like `IsSemiterm LAct 0 (qNum χ)`
with `variable {V : Type}` elaborates the `0` BEFORE `V` is pinned and defaults the whole statement
to `V := ℕ` — which type-checks (ℕ is a model) and is USELESS. Every statement ascribes `V`.

## Contents

* §1 The two new predicate codes (`lenDerivableDef TAct`, `boxCore` through the Σ₁ symbol
  `boxCoreS`/`boxRel`), the three new library rows `gIntroNum`, `lenDerIntro`, `boxIntro` (`Lib`,
  soundness by `pa_proves_of_models`), their pieces/`inst_` lemmas, the table
  `topRows := frag2Rows ++ [dlenDefIntro, proofIntro, gIntroNum, lenDerIntro, boxIntro]` at
  `150 + k` (`TopTable`, `exists_topTable`), the pieces `topPieces`, the step lemmas `tok_<row>`
  and `tfok_leTrans` (GENERATED by the session script `gen_top.py` on the `gen_frag2.py` template).
  Design choice (vs. `DESIGN_fragments.md` §7.1 step 9): the target is closed by ONE Horn row
  `boxIntro “n k g a. gGraph a k → instBGraph g n k → lenDerivableDef a g → boxCore n k”`
  whose conclusion IS the target fact, so the leaf is `axLFactCode` — no `targetLeafCode`.
  Likewise `lenDerIntro` folds `proof`/`dlenDef`/`≤` into `lenDerivableDef`, and `gIntroNum`
  reads the cube from the two numeral products directly (no eigenvariable `l̂`, no congruence glue).
* §2 The target's code shape: `instB ⌜Box_g χ⌝ k = boxFact (qNum χ) (bnum k)` with
  `qNum χ := numeral ⌜χ⌝` the unary numeral of the code of `χ` — proved for a VARIABLE `χ`
  (`quote_Box_g`, `instB_quote_Box_g`, `target_eq_boxFact`); the numeral's closedness, shift law and
  length (`termLen (numeral x) ≤ 2x + 1`).
* §3 The root layout `RootLayout` (what the walk + chain of the root sequent `{x}` deliver), the kits
  `VerifyKit` (§6.3/§6.4/§5 for the RELATION `VerifyGraph`) and `PinKit χ` (§7.1 steps 1–4 / §7.2).
* §4 `rootSteps` — the root layout is produced (`describeF` + `chainSteps` + `dossierAt_of_walk`).
* §5 `closeSteps` — from the recovered root goal to the target fact: the four `sLemma` numeral steps
  (N5, N4 ×2, N2) and the five rows.
* §6 The whole list, `chainCode_proof`, and the cost polynomial.
* §7 `boundedInnerNec_three_of_kit : … → BoundedInnerNec 3`.
-/

namespace ArithS

open FFL FFL.FirstOrder Arithmetic Bootstrapping
open FFL.FirstOrder.Arithmetic.Bootstrapping.Arithmetic
open PeanoMinus ISigma0 ISigma1
open LAct

variable {V : Type} [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁]

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 20000

/-! ## 1. The rows, the table and the pieces (GENERATED — `gen_top.py` on the `gen_frag2.py` template) -/

/-! ### The two new predicate codes: `lenDerivableDef TAct` and `boxCore` -/

/-- `boxCore` as a Σ₁ symbol (an `∃` over two Σ₁ graphs), so that the DSL `!boxCoreS n k` reads through a
`Defined` instance (the `bewB` route) and `simp` never unfolds it under a substitution. -/
noncomputable def boxCoreS : 𝚺₁.Semisentence 2 := .mkSigma “n k. ∃ a, !gGraph a k ∧ !bewBDef a n k”

lemma boxCoreS_val : ((boxCoreS : 𝚺₁.Semisentence 2) : Semisentence ℒₒᵣ 2) = boxCore := rfl

/-- The relation the box core defines: `n k ↦ LenDerivable TAct (gBudget k) (instB n k)` (`eval_boxCore`). -/
def boxRel (n k : V) : Prop := LenDerivable TAct (gBudget k) (instB n k)

instance boxRel.defined : 𝚺₁-Relation[V] boxRel via boxCoreS := .mk fun v ↦ by
  simp [boxCoreS, boxRel, bewB]

/-- The code of `lenDer` (arity 2). -/
noncomputable def PlenDer : V := ⌜Semiformula.lMap emb (↑(lenDerivableDef TAct) : ArithmeticSemisentence 2)⌝
lemma isSemiformula_PlenDer : IsSemiformula LAct ((2 : ℕ) : V) (PlenDer : V) := Sentence.quote_isSemiformula _
lemma shift_PlenDer : shift LAct (PlenDer : V) = PlenDer := shift_quote_sentence _
lemma fvOccF_PlenDer : fvOccF LAct (PlenDer : V) = 0 := fvOccF_quote_sentence _

/-- The code of `box` (arity 2). -/
noncomputable def Pbox : V := ⌜Semiformula.lMap emb (↑boxCoreS : ArithmeticSemisentence 2)⌝
lemma isSemiformula_Pbox : IsSemiformula LAct ((2 : ℕ) : V) (Pbox : V) := Sentence.quote_isSemiformula _
lemma shift_Pbox : shift LAct (Pbox : V) = Pbox := shift_quote_sentence _
lemma fvOccF_Pbox : fvOccF LAct (Pbox : V) = 0 := fvOccF_quote_sentence _

noncomputable def lenDerFact (a g : V) : V := subst LAct (listToVec [a, g]) PlenDer
lemma isFormula_lenDerFact {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) : IsFormula LAct (lenDerFact a g) :=
  isFormula_fact isSemiformula_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨ha, List.forall_mem_cons.mpr ⟨hg, List.forall_mem_nil _⟩⟩)
lemma shift_lenDerFact {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) :
    shift LAct (lenDerFact a g) = lenDerFact (termShift LAct a) (termShift LAct g) := by
  unfold lenDerFact
  rw [shift_subst_listToVec [a, g] isSemiformula_PlenDer shift_PlenDer (n := 0) (List.forall_mem_cons.mpr ⟨ha, List.forall_mem_cons.mpr ⟨hg, List.forall_mem_nil _⟩⟩)]
  rfl
lemma formulaLen_lenDerFact_le {B : V} (hB : 1 ≤ B) {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) (hla : termLen LAct a ≤ B) (hlg : termLen LAct g ≤ B) :
    formulaLen LAct (lenDerFact a g) ≤ formulaLen LAct (PlenDer : V) * B :=
  formulaLen_fact_le hB isSemiformula_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨⟨ha, hla⟩, List.forall_mem_cons.mpr ⟨⟨hg, hlg⟩, List.forall_mem_nil _⟩⟩)
lemma fvOccF_lenDerFact_le {M : V} {a g : V} (ha : IsSemiterm LAct 0 a) (hg : IsSemiterm LAct 0 g) (hoa : fvOcc LAct a ≤ M) (hog : fvOcc LAct g ≤ M) :
    fvOccF LAct (lenDerFact a g) ≤ bvOccF LAct (PlenDer : V) * M :=
  fvOccF_fact_le isSemiformula_PlenDer fvOccF_PlenDer _ rfl (List.forall_mem_cons.mpr ⟨⟨ha, hoa⟩, List.forall_mem_cons.mpr ⟨⟨hg, hog⟩, List.forall_mem_nil _⟩⟩)

noncomputable def boxFact (n k : V) : V := subst LAct (listToVec [n, k]) Pbox
lemma isFormula_boxFact {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) : IsFormula LAct (boxFact n k) :=
  isFormula_fact isSemiformula_Pbox _ rfl (List.forall_mem_cons.mpr ⟨hn, List.forall_mem_cons.mpr ⟨hk, List.forall_mem_nil _⟩⟩)
lemma shift_boxFact {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) :
    shift LAct (boxFact n k) = boxFact (termShift LAct n) (termShift LAct k) := by
  unfold boxFact
  rw [shift_subst_listToVec [n, k] isSemiformula_Pbox shift_Pbox (n := 0) (List.forall_mem_cons.mpr ⟨hn, List.forall_mem_cons.mpr ⟨hk, List.forall_mem_nil _⟩⟩)]
  rfl
lemma formulaLen_boxFact_le {B : V} (hB : 1 ≤ B) {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) (hln : termLen LAct n ≤ B) (hlk : termLen LAct k ≤ B) :
    formulaLen LAct (boxFact n k) ≤ formulaLen LAct (Pbox : V) * B :=
  formulaLen_fact_le hB isSemiformula_Pbox _ rfl (List.forall_mem_cons.mpr ⟨⟨hn, hln⟩, List.forall_mem_cons.mpr ⟨⟨hk, hlk⟩, List.forall_mem_nil _⟩⟩)
lemma fvOccF_boxFact_le {M : V} {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) (hon : fvOcc LAct n ≤ M) (hok : fvOcc LAct k ≤ M) :
    fvOccF LAct (boxFact n k) ≤ bvOccF LAct (Pbox : V) * M :=
  fvOccF_fact_le isSemiformula_Pbox fvOccF_Pbox _ rfl (List.forall_mem_cons.mpr ⟨⟨hn, hon⟩, List.forall_mem_cons.mpr ⟨⟨hk, hok⟩, List.forall_mem_nil _⟩⟩)

/-! ### The three new library rows (`Lib`), on the `Lib/Frag.lean` template -/

/-- `l = ‖k‖ → l * l = b → b * l = a → a = gBudget k` (the cube through two numeral products, §7.1 step 8). -/
noncomputable def gIntroNumB : ArithmeticSemisentence 4 :=
  “a b l k. !lengthDef l k → (l * l) = b → (b * l) = a → !gGraph a k”
noncomputable def gIntroNum : ArithmeticSentence := ∀¹* gIntroNumB
lemma models_gIntroNum : V↓[ℒₒᵣ] ⊧ gIntroNum ↔ ∀ a b l k : V, l = ‖k‖ → (l * l) = b → (b * l) = a → a = gBudget k := by
  simp [gIntroNum, gIntroNumB, models_iff, Matrix.vecForall_iff, length_defined.iff, gBudget.defined.iff]
theorem pa_proves_gIntroNum : 𝗣𝗔 ⊢ gIntroNum :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_gIntroNum.mpr fun _ _ _ _ h1 h2 h3 ↦ by subst_vars; first | rfl | assumption | trivial
theorem lib_gIntroNum : Lib gIntroNum := Lib.of_pa pa_proves_gIntroNum

/-- `proof d g → n = dlen d → n ≤ a → LenDerivable a g` (§7.1 step 7, folded). -/
noncomputable def lenDerIntroB : ArithmeticSemisentence 4 :=
  “a g n d. !(proof TAct).sigma d g → !(dlenDef TAct) n d → n ≤ a → !(lenDerivableDef TAct) a g”
noncomputable def lenDerIntro : ArithmeticSentence := ∀¹* lenDerIntroB
lemma models_lenDerIntro : V↓[ℒₒᵣ] ⊧ lenDerIntro ↔ ∀ a g n d : V, Proof TAct d g → n = dlen TAct d → n ≤ a → LenDerivable TAct a g := by
  simp [lenDerIntro, lenDerIntroB, models_iff, Matrix.vecForall_iff, dlen_defined.iff, (LenDerivable.defined (V := V) TAct).iff]
theorem pa_proves_lenDerIntro : 𝗣𝗔 ⊢ lenDerIntro :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_lenDerIntro.mpr fun _ _ _ _ h₁ h₂ h₃ ↦ by exact ⟨_, h₁, by rw [← h₂]; exact h₃⟩
theorem lib_lenDerIntro : Lib lenDerIntro := Lib.of_pa pa_proves_lenDerIntro

/-- `a = gBudget k → g = instB n k → LenDerivable a g → boxCore n k` — the target's ONE closing row (§7.1 step 9, as a row). -/
noncomputable def boxIntroB : ArithmeticSemisentence 4 :=
  “n k g a. !gGraph a k → !instBGraph g n k → !(lenDerivableDef TAct) a g → !boxCoreS n k”
noncomputable def boxIntro : ArithmeticSentence := ∀¹* boxIntroB
lemma models_boxIntro : V↓[ℒₒᵣ] ⊧ boxIntro ↔ ∀ n k g a : V, a = gBudget k → g = instB n k → LenDerivable TAct a g → LenDerivable TAct (gBudget k) (instB n k) := by
  simp [boxIntro, boxIntroB, models_iff, Matrix.vecForall_iff, gBudget.defined.iff, instB.defined.iff, (LenDerivable.defined (V := V) TAct).iff, boxRel.defined.iff, boxRel]
theorem pa_proves_boxIntro : 𝗣𝗔 ⊢ boxIntro :=
  Lib.pa_proves_of_models fun _ _ _ ↦ models_boxIntro.mpr fun _ _ _ _ h1 h2 h3 ↦ by subst_vars; first | rfl | assumption | trivial
theorem lib_boxIntro : Lib boxIntro := Lib.of_pa pa_proves_boxIntro

/-! ### The rows as pieces: `row_<r>_as`/`_c`, `quote_row_<r>`, `inst_<r>` (the `RowInstB` template) -/

/-! ### `gIntroNum` — `“a b l k. …”`, `m = 4` -/

noncomputable def row_gIntroNum_as : List V := [subst LAct (listToVec [bv 2, bv 3]) Plength, subst LAct (listToVec [(bv 2 ^* bv 2), bv 1]) PeqB, subst LAct (listToVec [(bv 1 ^* bv 2), bv 0]) PeqB]
noncomputable def row_gIntroNum_c : V := subst LAct (listToVec [bv 0, bv 3]) Pg

theorem quote_row_gIntroNum : (⌜Semiformula.lMap emb gIntroNumB⌝ : V) = impChain LAct row_gIntroNum_as row_gIntroNum_c := by
  unfold gIntroNumB row_gIntroNum_as row_gIntroNum_c PeqB Pg Plength
  all_goals row_shapeB

lemma isSemiformula_gIntroNum_as : ∀ A ∈ row_gIntroNum_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_gIntroNum_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Plength _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PeqB _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_gIntroNum_c : IsSemiformula LAct ((4 : ℕ) : V) row_gIntroNum_c := by
  unfold row_gIntroNum_c
  exact isSemiformula_substRow isSemiformula_Pg _ (by rfl) (by row_entriesB)

/-- `gIntroNum` at the witnesses `[wk, wl, wb, wa]` (the DSL variables right-to-left). -/
lemma inst_gIntroNum {wk wl wb wa : V} (hwk : IsSemiterm LAct 0 wk) (hwl : IsSemiterm LAct 0 wl) (hwb : IsSemiterm LAct 0 wb) (hwa : IsSemiterm LAct 0 wa) :
    row_gIntroNum_as.map (instOuter LAct [wk, wl, wb, wa]) = [lengthFact wl wk, eqFactB (wl ^* wl) wb, eqFactB (wb ^* wl) wa] ∧
    instOuter LAct [wk, wl, wb, wa] row_gIntroNum_c = gFact wa wk := by
  have hes : ∀ e ∈ ([wk, wl, wb, wa] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwk, List.forall_mem_cons.mpr ⟨hwl, List.forall_mem_cons.mpr ⟨hwb, List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_gIntroNum_as row_gIntroNum_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Plength (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PeqB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pg (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `lenDerIntro` — `“a g n d. …”`, `m = 4` -/

noncomputable def row_lenDerIntro_as : List V := [subst LAct (listToVec [bv 3, bv 1]) Pproof, subst LAct (listToVec [bv 2, bv 3]) PdlenDef, subst LAct (listToVec [bv 2, bv 0]) Ple]
noncomputable def row_lenDerIntro_c : V := subst LAct (listToVec [bv 0, bv 1]) PlenDer

theorem quote_row_lenDerIntro : (⌜Semiformula.lMap emb lenDerIntroB⌝ : V) = impChain LAct row_lenDerIntro_as row_lenDerIntro_c := by
  unfold lenDerIntroB row_lenDerIntro_as row_lenDerIntro_c PdlenDef Ple PlenDer Pproof leS
  all_goals row_shapeB

lemma isSemiformula_lenDerIntro_as : ∀ A ∈ row_lenDerIntro_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_lenDerIntro_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pproof _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PdlenDef _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Ple _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_lenDerIntro_c : IsSemiformula LAct ((4 : ℕ) : V) row_lenDerIntro_c := by
  unfold row_lenDerIntro_c
  exact isSemiformula_substRow isSemiformula_PlenDer _ (by rfl) (by row_entriesB)

/-- `lenDerIntro` at the witnesses `[wd, wn, wg, wa]` (the DSL variables right-to-left). -/
lemma inst_lenDerIntro {wd wn wg wa : V} (hwd : IsSemiterm LAct 0 wd) (hwn : IsSemiterm LAct 0 wn) (hwg : IsSemiterm LAct 0 wg) (hwa : IsSemiterm LAct 0 wa) :
    row_lenDerIntro_as.map (instOuter LAct [wd, wn, wg, wa]) = [proofFact wd wg, dlenDefFact wn wd, leFact wn wa] ∧
    instOuter LAct [wd, wn, wg, wa] row_lenDerIntro_c = lenDerFact wa wg := by
  have hes : ∀ e ∈ ([wd, wn, wg, wa] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwd, List.forall_mem_cons.mpr ⟨hwn, List.forall_mem_cons.mpr ⟨hwg, List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_lenDerIntro_as row_lenDerIntro_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pproof (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PdlenDef (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Ple (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PlenDer (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### `boxIntro` — `“n k g a. …”`, `m = 4` -/

noncomputable def row_boxIntro_as : List V := [subst LAct (listToVec [bv 3, bv 1]) Pg, subst LAct (listToVec [bv 2, bv 0, bv 1]) PinstB, subst LAct (listToVec [bv 3, bv 2]) PlenDer]
noncomputable def row_boxIntro_c : V := subst LAct (listToVec [bv 0, bv 1]) Pbox

theorem quote_row_boxIntro : (⌜Semiformula.lMap emb boxIntroB⌝ : V) = impChain LAct row_boxIntro_as row_boxIntro_c := by
  unfold boxIntroB row_boxIntro_as row_boxIntro_c Pbox Pg PinstB PlenDer
  all_goals row_shapeB

lemma isSemiformula_boxIntro_as : ∀ A ∈ row_boxIntro_as, IsSemiformula LAct ((4 : ℕ) : V) A := by
  unfold row_boxIntro_as
  exact (List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_Pg _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PinstB _ (by rfl) (by row_entriesB), List.forall_mem_cons.mpr ⟨isSemiformula_substRow isSemiformula_PlenDer _ (by rfl) (by row_entriesB), List.forall_mem_nil _⟩⟩⟩)
lemma isSemiformula_boxIntro_c : IsSemiformula LAct ((4 : ℕ) : V) row_boxIntro_c := by
  unfold row_boxIntro_c
  exact isSemiformula_substRow isSemiformula_Pbox _ (by rfl) (by row_entriesB)

/-- `boxIntro` at the witnesses `[wa, wg, wk, wn]` (the DSL variables right-to-left). -/
lemma inst_boxIntro {wa wg wk wn : V} (hwa : IsSemiterm LAct 0 wa) (hwg : IsSemiterm LAct 0 wg) (hwk : IsSemiterm LAct 0 wk) (hwn : IsSemiterm LAct 0 wn) :
    row_boxIntro_as.map (instOuter LAct [wa, wg, wk, wn]) = [gFact wa wk, instBFact wg wn wk, lenDerFact wa wg] ∧
    instOuter LAct [wa, wg, wk, wn] row_boxIntro_c = boxFact wn wk := by
  have hes : ∀ e ∈ ([wa, wg, wk, wn] : List V), IsSemiterm LAct 0 e := (List.forall_mem_cons.mpr ⟨hwa, List.forall_mem_cons.mpr ⟨hwg, List.forall_mem_cons.mpr ⟨hwk, List.forall_mem_cons.mpr ⟨hwn, List.forall_mem_nil _⟩⟩⟩⟩)
  unfold row_boxIntro_as row_boxIntro_c
  simp only [List.map_cons, List.map_nil]
  rw [instOuter_subst_listToVec _ isSemiformula_Pg (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PinstB (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_PlenDer (by rfl) _ hes (by row_entriesB), instOuter_subst_listToVec _ isSemiformula_Pbox (by rfl) _ hes (by row_entriesB)]
  all_goals try row_entries_simpB
  row_finish

/-! ### The top table: the Frag2 rows, then the five top rows at `150 + k` -/

section topTable

def tIdx_dlenDefIntro : ℕ := 150
def tIdx_proofIntro : ℕ := 151
def tIdx_gIntroNum : ℕ := 152
def tIdx_lenDerIntro : ℕ := 153
def tIdx_boxIntro : ℕ := 154
def topRowCount : ℕ := 155

/-- The rows at `150 + k`, in index order. -/
noncomputable def topExtraRows : List WRow := [
  ⟨2, dlenDefIntroB, lib_dlenDefIntro⟩,
  ⟨3, proofIntroB, lib_proofIntro⟩,
  ⟨4, gIntroNumB, lib_gIntroNum⟩,
  ⟨4, lenDerIntroB, lib_lenDerIntro⟩,
  ⟨4, boxIntroB, lib_boxIntro⟩
]

/-- The top table's rows: Frag2's, then the five top rows. -/
noncomputable def topRows : List WRow := frag2Rows ++ topExtraRows

lemma topRows_length : topRows.length = topRowCount := rfl

/-- **The top proof table**: `topRowCount` rows at least, the `i`-th with the arity and the matrix of
`topRows[i]`. -/
def TopTable (tbl : V) : Prop :=
  (topRowCount : V) ≤ len tbl ∧
  ∀ (i : ℕ) (h : i < topRows.length),
    rowM tbl.[(i : V)] = ((topRows[i]).m : V) ∧ rowB tbl.[(i : V)] = ⌜Semiformula.lMap emb (topRows[i]).B⌝

/-- A top table is a fragment-2 table (the first 150 rows). -/
lemma TopTable.frag2Table {tbl : V} (h : TopTable tbl) : Frag2Table tbl := by
  refine ⟨le_trans (by exact_mod_cast (by decide : frag2RowCount ≤ topRowCount)) h.1, ?_⟩
  intro i hi
  have hi' : i < topRows.length := by
    rw [topRows_length]; exact lt_of_lt_of_le (frag2Rows_length ▸ hi) (by decide)
  have := h.2 i hi'
  rwa [show topRows[i] = frag2Rows[i] from List.getElem_append_left hi] at this

lemma TopTable.frag1Table {tbl : V} (h : TopTable tbl) : Frag1Table tbl := h.frag2Table.frag1Table
lemma TopTable.layoutTable {tbl : V} (h : TopTable tbl) : LayoutTable tbl := h.frag2Table.layoutTable
lemma TopTable.walkTable {tbl : V} (h : TopTable tbl) : WalkTable tbl := h.frag2Table.walkTable

/-- **The top proof table exists in every model, with one standard length bound.** -/
theorem exists_topTable : ∃ N : ℕ, ∀ (V : Type) [ORingStructure V] [V↓[ℒₒᵣ] ⊧* 𝗜𝚺₁],
    ∃ tbl : V, TableOK tbl (N : V) ∧ TopTable tbl := by
  obtain ⟨N, hN⟩ := exists_rows topRows
  refine ⟨N, fun V _ _ ↦ ?_⟩
  obtain ⟨rows, hlen, hok, hidx⟩ := hN V
  refine ⟨vecOf rows, tableOK_vecOf rows hok, ?_, ?_⟩
  · rw [len_vecOf, hlen, topRows_length]
  · intro i h
    have h' : i < rows.length := by rw [hlen]; exact h
    rw [nth_vecOf rows i h']
    exact hidx i h h'

lemma topTable_len {tbl : V} (h : TopTable tbl) (i : ℕ) (hi : i < topRowCount) : ((i : ℕ) : V) < len tbl :=
  lt_of_lt_of_le (by exact_mod_cast hi) h.1

/-! ### The per-row readings of `TopTable` -/

lemma topTable_dlenDefIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ((2 : ℕ) : V) ∧
    rowB tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = impChainV LAct (vecOf row_dlenDefIntro_as) row_dlenDefIntro_c := by
  have this : rowM tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ((2 : ℕ) : V) ∧
      rowB tbl.[((tIdx_dlenDefIntro : ℕ) : V)] = ⌜Semiformula.lMap emb dlenDefIntroB⌝ :=
    h.2 tIdx_dlenDefIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_dlenDefIntro]

lemma topTable_proofIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_proofIntro : ℕ) : V)] = ((3 : ℕ) : V) ∧
    rowB tbl.[((tIdx_proofIntro : ℕ) : V)] = impChainV LAct (vecOf row_proofIntro_as) row_proofIntro_c := by
  have this : rowM tbl.[((tIdx_proofIntro : ℕ) : V)] = ((3 : ℕ) : V) ∧
      rowB tbl.[((tIdx_proofIntro : ℕ) : V)] = ⌜Semiformula.lMap emb proofIntroB⌝ :=
    h.2 tIdx_proofIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_proofIntro]

lemma topTable_gIntroNum {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_gIntroNum : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_gIntroNum : ℕ) : V)] = impChainV LAct (vecOf row_gIntroNum_as) row_gIntroNum_c := by
  have this : rowM tbl.[((tIdx_gIntroNum : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_gIntroNum : ℕ) : V)] = ⌜Semiformula.lMap emb gIntroNumB⌝ :=
    h.2 tIdx_gIntroNum (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_gIntroNum]

lemma topTable_lenDerIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_lenDerIntro : ℕ) : V)] = impChainV LAct (vecOf row_lenDerIntro_as) row_lenDerIntro_c := by
  have this : rowM tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_lenDerIntro : ℕ) : V)] = ⌜Semiformula.lMap emb lenDerIntroB⌝ :=
    h.2 tIdx_lenDerIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_lenDerIntro]

lemma topTable_boxIntro {tbl : V} (h : TopTable tbl) :
    rowM tbl.[((tIdx_boxIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
    rowB tbl.[((tIdx_boxIntro : ℕ) : V)] = impChainV LAct (vecOf row_boxIntro_as) row_boxIntro_c := by
  have this : rowM tbl.[((tIdx_boxIntro : ℕ) : V)] = ((4 : ℕ) : V) ∧
      rowB tbl.[((tIdx_boxIntro : ℕ) : V)] = ⌜Semiformula.lMap emb boxIntroB⌝ :=
    h.2 tIdx_boxIntro (Nat.lt_of_sub_eq_succ rfl)
  refine ⟨this.1, ?_⟩
  rw [impChainV_vecOf, this.2, quote_row_boxIntro]

/-! ### The piece table -/

noncomputable def tpiece_dlenDefIntro : V := ⟪(0 : V), vecOf row_dlenDefIntro_as, row_dlenDefIntro_c⟫
noncomputable def tpiece_proofIntro : V := ⟪(0 : V), vecOf row_proofIntro_as, row_proofIntro_c⟫
noncomputable def tpiece_gIntroNum : V := ⟪(0 : V), vecOf row_gIntroNum_as, row_gIntroNum_c⟫
noncomputable def tpiece_lenDerIntro : V := ⟪(0 : V), vecOf row_lenDerIntro_as, row_lenDerIntro_c⟫
noncomputable def tpiece_boxIntro : V := ⟪(0 : V), vecOf row_boxIntro_as, row_boxIntro_c⟫

noncomputable def topExtraPieceList : List V := [
  tpiece_dlenDefIntro,
  tpiece_proofIntro,
  tpiece_gIntroNum,
  tpiece_lenDerIntro,
  tpiece_boxIntro
]

/-- **The piece table of the top**: Frag2's pieces, then the top rows' pieces. -/
noncomputable def topPieces : V := vecOf (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList)

lemma topPieces_nth_lt (i : ℕ) (hi : i < frag2RowCount) : (topPieces : V).[(i : V)] = (frag2Pieces : V).[(i : V)] := by
  unfold topPieces frag2Pieces
  have h1 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList ++ topExtraPieceList : List V).length = topRowCount from rfl]
    exact lt_of_lt_of_le hi (by decide)
  have h2 : i < (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList : List V).length := by
    rw [show (walkPieceList ++ layoutExtraPieceList ++ frag1ExtraPieceList ++ frag2ExtraPieceList : List V).length = frag2RowCount from rfl]; exact hi
  rw [nth_vecOf _ i h1, nth_vecOf _ i h2]
  exact List.getElem_append_left h2

/-- A Frag2 step read from the top pieces is Frag2's step. -/
lemma mkStep_topPieces_lt (i : ℕ) (hi : i < frag2RowCount) (ev : V) :
    mkStep topPieces (i : V) ev = mkStep frag2Pieces (i : V) ev := by
  rw [mkStep, mkStep, topPieces_nth_lt i hi]

lemma topPieces_dlenDefIntro : (topPieces : V).[((tIdx_dlenDefIntro : ℕ) : V)] = tpiece_dlenDefIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_dlenDefIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_dlenDefIntro (ev : V) :
    mkStep topPieces ((tIdx_dlenDefIntro : ℕ) : V) ev = sUseHorn ((tIdx_dlenDefIntro : ℕ) : V) ev (vecOf row_dlenDefIntro_as) row_dlenDefIntro_c := by
  rw [mkStep, topPieces_dlenDefIntro]
  simp [tpiece_dlenDefIntro, sUseHorn]

lemma ttag_dlenDefIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (150 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_dlenDefIntro : ℕ) : V) = (150 : V) := by simp [tIdx_dlenDefIntro]
  rw [← hk, tmk_dlenDefIntro]; simp

lemma topPieces_proofIntro : (topPieces : V).[((tIdx_proofIntro : ℕ) : V)] = tpiece_proofIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_proofIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_proofIntro (ev : V) :
    mkStep topPieces ((tIdx_proofIntro : ℕ) : V) ev = sUseHorn ((tIdx_proofIntro : ℕ) : V) ev (vecOf row_proofIntro_as) row_proofIntro_c := by
  rw [mkStep, topPieces_proofIntro]
  simp [tpiece_proofIntro, sUseHorn]

lemma ttag_proofIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (151 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_proofIntro : ℕ) : V) = (151 : V) := by simp [tIdx_proofIntro]
  rw [← hk, tmk_proofIntro]; simp

lemma topPieces_gIntroNum : (topPieces : V).[((tIdx_gIntroNum : ℕ) : V)] = tpiece_gIntroNum := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_gIntroNum (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_gIntroNum (ev : V) :
    mkStep topPieces ((tIdx_gIntroNum : ℕ) : V) ev = sUseHorn ((tIdx_gIntroNum : ℕ) : V) ev (vecOf row_gIntroNum_as) row_gIntroNum_c := by
  rw [mkStep, topPieces_gIntroNum]
  simp [tpiece_gIntroNum, sUseHorn]

lemma ttag_gIntroNum {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (152 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_gIntroNum : ℕ) : V) = (152 : V) := by simp [tIdx_gIntroNum]
  rw [← hk, tmk_gIntroNum]; simp

lemma topPieces_lenDerIntro : (topPieces : V).[((tIdx_lenDerIntro : ℕ) : V)] = tpiece_lenDerIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_lenDerIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_lenDerIntro (ev : V) :
    mkStep topPieces ((tIdx_lenDerIntro : ℕ) : V) ev = sUseHorn ((tIdx_lenDerIntro : ℕ) : V) ev (vecOf row_lenDerIntro_as) row_lenDerIntro_c := by
  rw [mkStep, topPieces_lenDerIntro]
  simp [tpiece_lenDerIntro, sUseHorn]

lemma ttag_lenDerIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (153 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_lenDerIntro : ℕ) : V) = (153 : V) := by simp [tIdx_lenDerIntro]
  rw [← hk, tmk_lenDerIntro]; simp

lemma topPieces_boxIntro : (topPieces : V).[((tIdx_boxIntro : ℕ) : V)] = tpiece_boxIntro := by
  unfold topPieces
  rw [nth_vecOf _ tIdx_boxIntro (Nat.lt_of_sub_eq_succ rfl)]
  rfl

lemma tmk_boxIntro (ev : V) :
    mkStep topPieces ((tIdx_boxIntro : ℕ) : V) ev = sUseHorn ((tIdx_boxIntro : ℕ) : V) ev (vecOf row_boxIntro_as) row_boxIntro_c := by
  rw [mkStep, topPieces_boxIntro]
  simp [tpiece_boxIntro, sUseHorn]

lemma ttag_boxIntro {W : V} (hWp : W = topPieces) (ev : V) : sTag (mkStep W (154 : V) ev) = 0 := by
  subst hWp
  have hk : ((tIdx_boxIntro : ℕ) : V) = (154 : V) := by simp [tIdx_boxIntro]
  rw [← hk, tmk_boxIntro]; simp

/-! ### The per-row applicability lemmas `tok_<row>` -/

/-- Row `dlenDefIntro` as a step. -/
lemma tok_dlenDefIntro {tbl N E Γ W : V} {wd wn : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hmem0 : neg LAct (derFact wd) ∈ Γ) (hmem1 : neg LAct (dlenFact wd wn) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 150 ?[wd, wn]) ∧ sTag (mkStep W 150 ?[wd, wn]) = 0 ∧
    ctxAfter Γ (mkStep W 150 ?[wd, wn]) = insert (neg LAct (dlenDefFact wn wd)) Γ := by
  subst hWp
  have hk : ((tIdx_dlenDefIntro : ℕ) : V) = (150 : V) := by simp [tIdx_dlenDefIntro]
  have hstep := tmk_dlenDefIntro (V := V) ?[wd, wn]
  have hlen := topTable_len hT tIdx_dlenDefIntro (by decide)
  have hrow := topTable_dlenDefIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wd, wn], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_nil _⟩⟩
  have hinst := inst_dlenDefIntro hwd hwn
  rw [hstep, show (?[wd, wn] : V) = vecOf [wd, wn] from rfl]
  refine ⟨stepOK_useHorn htbl [wd, wn] row_dlenDefIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 2 ≤ 8))
    (by rw [show row_dlenDefIntro_as.length = 2 from rfl] <;> exact_mod_cast (by decide : 2 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_nil _⟩⟩)
  · rw [ctxAfter_useHorn [wd, wn] row_dlenDefIntro_as isSemiformula_dlenDefIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `proofIntro` as a step. -/
lemma tok_proofIntro {tbl N E Γ W : V} {ws wg wd : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hws : IsSemiterm LAct 0 ws) (hEws : termLen LAct ws ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hmem0 : neg LAct (insFact ws wg (𝟎 : V)) ∈ Γ) (hmem1 : neg LAct (fstIdxFact ws wd) ∈ Γ) (hmem2 : neg LAct (derFact wd) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 151 ?[ws, wg, wd]) ∧ sTag (mkStep W 151 ?[ws, wg, wd]) = 0 ∧
    ctxAfter Γ (mkStep W 151 ?[ws, wg, wd]) = insert (neg LAct (proofFact wd wg)) Γ := by
  subst hWp
  have hk : ((tIdx_proofIntro : ℕ) : V) = (151 : V) := by simp [tIdx_proofIntro]
  have hstep := tmk_proofIntro (V := V) ?[ws, wg, wd]
  have hlen := topTable_len hT tIdx_proofIntro (by decide)
  have hrow := topTable_proofIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [ws, wg, wd], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hws, hEws⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_nil _⟩⟩⟩
  have hinst := inst_proofIntro hws hwg hwd
  rw [hstep, show (?[ws, wg, wd] : V) = vecOf [ws, wg, wd] from rfl]
  refine ⟨stepOK_useHorn htbl [ws, wg, wd] row_proofIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 3 ≤ 8))
    (by rw [show row_proofIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [ws, wg, wd] row_proofIntro_as isSemiformula_proofIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `gIntroNum` as a step. -/
lemma tok_gIntroNum {tbl N E Γ W : V} {wk wl wb wa : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwk : IsSemiterm LAct 0 wk) (hEwk : termLen LAct wk ≤ E) (hwl : IsSemiterm LAct 0 wl) (hEwl : termLen LAct wl ≤ E) (hwb : IsSemiterm LAct 0 wb) (hEwb : termLen LAct wb ≤ E) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hmem0 : neg LAct (lengthFact wl wk) ∈ Γ) (hmem1 : neg LAct (eqFactB (wl ^* wl) wb) ∈ Γ) (hmem2 : neg LAct (eqFactB (wb ^* wl) wa) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 152 ?[wk, wl, wb, wa]) ∧ sTag (mkStep W 152 ?[wk, wl, wb, wa]) = 0 ∧
    ctxAfter Γ (mkStep W 152 ?[wk, wl, wb, wa]) = insert (neg LAct (gFact wa wk)) Γ := by
  subst hWp
  have hk : ((tIdx_gIntroNum : ℕ) : V) = (152 : V) := by simp [tIdx_gIntroNum]
  have hstep := tmk_gIntroNum (V := V) ?[wk, wl, wb, wa]
  have hlen := topTable_len hT tIdx_gIntroNum (by decide)
  have hrow := topTable_gIntroNum hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wk, wl, wb, wa], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwk, hEwk⟩, List.forall_mem_cons.mpr ⟨⟨hwl, hEwl⟩, List.forall_mem_cons.mpr ⟨⟨hwb, hEwb⟩, List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_gIntroNum hwk hwl hwb hwa
  rw [hstep, show (?[wk, wl, wb, wa] : V) = vecOf [wk, wl, wb, wa] from rfl]
  refine ⟨stepOK_useHorn htbl [wk, wl, wb, wa] row_gIntroNum_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_gIntroNum_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wk, wl, wb, wa] row_gIntroNum_as isSemiformula_gIntroNum_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `lenDerIntro` as a step. -/
lemma tok_lenDerIntro {tbl N E Γ W : V} {wd wn wg wa : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwd : IsSemiterm LAct 0 wd) (hEwd : termLen LAct wd ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hmem0 : neg LAct (proofFact wd wg) ∈ Γ) (hmem1 : neg LAct (dlenDefFact wn wd) ∈ Γ) (hmem2 : neg LAct (leFact wn wa) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 153 ?[wd, wn, wg, wa]) ∧ sTag (mkStep W 153 ?[wd, wn, wg, wa]) = 0 ∧
    ctxAfter Γ (mkStep W 153 ?[wd, wn, wg, wa]) = insert (neg LAct (lenDerFact wa wg)) Γ := by
  subst hWp
  have hk : ((tIdx_lenDerIntro : ℕ) : V) = (153 : V) := by simp [tIdx_lenDerIntro]
  have hstep := tmk_lenDerIntro (V := V) ?[wd, wn, wg, wa]
  have hlen := topTable_len hT tIdx_lenDerIntro (by decide)
  have hrow := topTable_lenDerIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wd, wn, wg, wa], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwd, hEwd⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_lenDerIntro hwd hwn hwg hwa
  rw [hstep, show (?[wd, wn, wg, wa] : V) = vecOf [wd, wn, wg, wa] from rfl]
  refine ⟨stepOK_useHorn htbl [wd, wn, wg, wa] row_lenDerIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_lenDerIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wd, wn, wg, wa] row_lenDerIntro_as isSemiformula_lenDerIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-- Row `boxIntro` as a step. -/
lemma tok_boxIntro {tbl N E Γ W : V} {wa wg wk wn : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwa : IsSemiterm LAct 0 wa) (hEwa : termLen LAct wa ≤ E) (hwg : IsSemiterm LAct 0 wg) (hEwg : termLen LAct wg ≤ E) (hwk : IsSemiterm LAct 0 wk) (hEwk : termLen LAct wk ≤ E) (hwn : IsSemiterm LAct 0 wn) (hEwn : termLen LAct wn ≤ E) (hmem0 : neg LAct (gFact wa wk) ∈ Γ) (hmem1 : neg LAct (instBFact wg wn wk) ∈ Γ) (hmem2 : neg LAct (lenDerFact wa wg) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 154 ?[wa, wg, wk, wn]) ∧ sTag (mkStep W 154 ?[wa, wg, wk, wn]) = 0 ∧
    ctxAfter Γ (mkStep W 154 ?[wa, wg, wk, wn]) = insert (neg LAct (boxFact wn wk)) Γ := by
  subst hWp
  have hk : ((tIdx_boxIntro : ℕ) : V) = (154 : V) := by simp [tIdx_boxIntro]
  have hstep := tmk_boxIntro (V := V) ?[wa, wg, wk, wn]
  have hlen := topTable_len hT tIdx_boxIntro (by decide)
  have hrow := topTable_boxIntro hT
  rw [hk] at hstep hlen hrow
  have hes : ∀ e ∈ [wa, wg, wk, wn], IsSemiterm LAct 0 e ∧ termLen LAct e ≤ E := List.forall_mem_cons.mpr ⟨⟨hwa, hEwa⟩, List.forall_mem_cons.mpr ⟨⟨hwg, hEwg⟩, List.forall_mem_cons.mpr ⟨⟨hwk, hEwk⟩, List.forall_mem_cons.mpr ⟨⟨hwn, hEwn⟩, List.forall_mem_nil _⟩⟩⟩⟩
  have hinst := inst_boxIntro hwa hwg hwk hwn
  rw [hstep, show (?[wa, wg, wk, wn] : V) = vecOf [wa, wg, wk, wn] from rfl]
  refine ⟨stepOK_useHorn htbl [wa, wg, wk, wn] row_boxIntro_as hΓ hlen hrow.1 hrow.2 (by exact_mod_cast (by decide : 4 ≤ 8))
    (by rw [show row_boxIntro_as.length = 3 from rfl] <;> exact_mod_cast (by decide : 3 ≤ 8)) hes ?_, by simp, ?_⟩
  · exact neg_mem_of_map hinst.1 (List.forall_mem_cons.mpr ⟨hmem0, List.forall_mem_cons.mpr ⟨hmem1, List.forall_mem_cons.mpr ⟨hmem2, List.forall_mem_nil _⟩⟩⟩)
  · rw [ctxAfter_useHorn [wa, wg, wk, wn] row_boxIntro_as isSemiformula_boxIntro_c (fun e he ↦ (hes e he).1), hinst.2]

/-! ### The Frag1 row `leTrans` (110), read from the top pieces -/

lemma tfok_leTrans {tbl N E Γ W : V} {wz wy wx : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hWp : W = topPieces)
    (hΓ : IsFormulaSet LAct Γ) (hwz : IsSemiterm LAct 0 wz) (hEwz : termLen LAct wz ≤ E) (hwy : IsSemiterm LAct 0 wy) (hEwy : termLen LAct wy ≤ E) (hwx : IsSemiterm LAct 0 wx) (hEwx : termLen LAct wx ≤ E) (hmem0 : neg LAct (leFact wx wy) ∈ Γ) (hmem1 : neg LAct (leFact wy wz) ∈ Γ) :
    StepOK tbl E ((8 : ℕ) : V) Γ (mkStep W 110 ?[wz, wy, wx]) ∧ sTag (mkStep W 110 ?[wz, wy, wx]) = 0 ∧
    ctxAfter Γ (mkStep W 110 ?[wz, wy, wx]) = insert (neg LAct (leFact wx wz)) Γ := by
  subst hWp
  have e : ∀ ev : V, mkStep topPieces (110 : V) ev = mkStep frag1Pieces (110 : V) ev := fun ev ↦ by
    have h1 := mkStep_topPieces_lt 110 (by decide) ev
    have h2 := mkStep_frag2Pieces_lt 110 (by decide) ev
    simp only [Nat.cast_ofNat] at h1 h2; rw [h1, h2]
  rw [e]
  exact fok_leTrans htbl hT.frag1Table rfl hΓ hwz hEwz hwy hEwy hwx hEwx hmem0 hmem1

end topTable

/-! ## 2. The target's code shape (for a VARIABLE `χ` — no closed quote is ever unfolded) -/

section targetShape

noncomputable def qNum (χ : Semisentence LAct 1) : V := numeral (⌜χ⌝ : V)

lemma isSemiterm_qNum (χ : Semisentence LAct 1) : IsSemiterm LAct (0 : V) (qNum χ) :=
  InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)

theorem quote_Box_g (χ : Semisentence LAct 1) :
    (⌜Box_g χ⌝ : V) = subst LAct (qNum χ ∷ ^#0 ∷ 0) Pbox := by
  rw [Box_g_def]
  conv_lhs =>
    rw [Sentence.quote_def, Semiformula.coe_subst_eq_subst_coe, Semiformula.quote_def,
      Semiformula.typed_quote_substs, Bootstrapping.Semiformula.val_substs, ← Semiformula.quote_def,
      ← Sentence.quote_def]
  unfold Pbox
  congr 1
  have hv : (fun i ↦ (⌜(Rew.emb (![Semiterm.lMap emb (⌜χ⌝ : ArithmeticSemiterm Empty 1), #0] i) :
      SyntacticSemiterm LAct 1)⌝ : Bootstrapping.Semiterm V LAct 1)) =
      ![⌜(Rew.emb (Semiterm.lMap emb (⌜χ⌝ : ArithmeticSemiterm Empty 1)) : SyntacticSemiterm LAct 1)⌝,
        ⌜(Rew.emb (#0 : Semiterm LAct Empty 1) : SyntacticSemiterm LAct 1)⌝] := by
    funext i; fin_cases i <;> rfl
  rw [hv]
  simp only [SemitermVec.val_cons, SemitermVec.val_nil, Diag.typed_val_emb, quote_lMap_gödel]
  rfl

lemma termShift_numeral_LAct (x : V) : termShift LAct (numeral x) = numeral x := by
  induction x using ISigma1.sigma1_succ_induction
  · definability
  case zero => rw [numeral_zero, termShift_qqZero isFunc_LAct_zeroIndex]
  case succ x ih =>
    rcases zero_or_succ x with (rfl | ⟨x, rfl⟩)
    · rw [zero_add, numeral_one, termShift_qqOne isFunc_LAct_oneIndex]
    · rw [numeral_add_two, termShift_qqAdd isFunc_LAct_addIndex
        (InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)).isUTerm qqOne_uterm_LAct, ih,
        termShift_qqOne isFunc_LAct_oneIndex]

lemma termLen_numeral_le (x : V) : termLen LAct (numeral x) ≤ 2 * x + 1 := by
  induction x using ISigma1.sigma1_succ_induction
  · definability
  case zero => rw [numeral_zero, termLen_qqZero isFunc_LAct_zeroIndex]; simp
  case succ x ih =>
    rcases zero_or_succ x with (rfl | ⟨x, rfl⟩)
    · rw [zero_add, numeral_one, termLen_qqOne isFunc_LAct_oneIndex]; simp
    · rw [numeral_add_two, termLen_qqAdd isFunc_LAct_addIndex
        (InstV.isSemiterm_LAct_of_LOR (numeral_semiterm 0 _)).isUTerm qqOne_uterm_LAct,
        termLen_qqOne isFunc_LAct_oneIndex]
      calc termLen LAct (numeral (x + 1)) + 1 + 1 ≤ 2 * (x + 1) + 1 + 1 + 1 := by
            exact add_le_add (add_le_add ih le_rfl) le_rfl
        _ = 2 * (x + 1 + 1) + 1 := by ring

theorem instB_quote_Box_g (χ : Semisentence LAct 1) (k : V) :
    instB (⌜Box_g χ⌝ : V) k = subst LAct (qNum χ ∷ bnum k ∷ 0) Pbox := by
  rw [quote_Box_g, instB]
  have hq : IsSemiterm LAct ((0 : V) + 1) (qNum χ) := InstV.isSemiterm_LAct_of_LOR (numeral_semiterm ((0 : V) + 1) _)
  have hb : IsSemiterm LAct ((0 : V) + 1) (^#0 : V) := by simp
  have hv : IsSemitermVec LAct ((0 : V) + 1 + 1) ((0 : V) + 1) (qNum χ ∷ ^#0 ∷ (0 : V)) :=
    IsSemitermVec.adjoin (IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)) hb) hq
  have hw : IsSemitermVec LAct ((0 : V) + 1) (0 : V) (bnum k ∷ (0 : V)) :=
    IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) (0 : V)) (bnum_term_LAct k)
  have h2 : ((2 : ℕ) : V) = 0 + 1 + 1 := by simp [one_add_one_eq_two]
  rw [substs_substs (h2 ▸ isSemiformula_Pbox) hw hv]
  congr 1
  rw [termSubstVec_cons hq.isUTerm (IsSemitermVec.adjoin (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)) hb).isUTerm,
    termSubstVec_cons hb.isUTerm (IsSemitermVec.nil (L := LAct) ((0 : V) + 1)).isUTerm, termSubstVec_nil, termSubst_bvar,
    termSubst_eq_self (L := LAct) (w := bnum k ∷ (0 : V)) (isSemiterm_qNum χ) (fun i hi ↦ by simp at hi)]
  simp


/-- **The target IS the `boxIntro` fact**: `instB ⌜Box_g χ⌝ k = boxFact (qNum χ) (bnum k)`. -/
theorem target_eq_boxFact (χ : Semisentence LAct 1) (k : V) :
    instB (⌜Box_g χ⌝ : V) k = boxFact (qNum χ) (bnum k) :=
  instB_quote_Box_g χ k

lemma termShift_qNum (χ : Semisentence LAct 1) : termShift LAct (qNum χ : V) = qNum χ :=
  termShift_numeral_LAct _

/-- The numeral's length is a STANDARD constant of `χ`: `≤ 2·⌜χ⌝ + 1` with `⌜χ⌝ : ℕ` cast. -/
lemma termLen_qNum_le (χ : Semisentence LAct 1) :
    termLen LAct (qNum χ : V) ≤ ((2 * (⌜χ⌝ : ℕ) + 1 : ℕ) : V) := by
  unfold qNum
  push_cast
  rw [Sentence.coe_quote_eq_quote χ]
  exact termLen_numeral_le _

end targetShape

/-! ## 3. The root layout and the two kits -/

section rootLayout

/-! ### 3.1 Iterated shifts of the facts the top transports (`termShiftIterV`/`shiftIterV`, by
`sigma1_succ_induction` on the count — the `termShiftIterV_fvar` pattern) -/

lemma termShiftIterV_bnumTop (k : V) : ∀ c : V, termShiftIterV (bnum k) c = bnum k := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih => rw [termShiftIterV_succ, ih, termShift_bnum]

lemma termShiftIterV_qNum (χ : Semisentence LAct 1) : ∀ c : V, termShiftIterV (qNum χ : V) c = qNum χ := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih => rw [termShiftIterV_succ, ih, termShift_qNum]

lemma termShiftIterV_qqZero : ∀ c : V, termShiftIterV (𝟎 : V) c = 𝟎 := by
  intro c
  rw [← cTV_zero]
  exact termShiftIterV_cTV 0 c

instance boxFact_defined : 𝚺₁-Function₂ (boxFact : V → V → V) via
    fact2Def (Semiformula.lMap emb (↑boxCoreS : ArithmeticSemisentence 2)) := fact2_defined _
instance boxFact_definable : 𝚺₁-Function₂ (boxFact : V → V → V) := boxFact_defined.to_definable
instance instBFact_defined' : 𝚺₁-Function₃ (instBFact : V → V → V → V) via
    fact3Def (Semiformula.lMap emb (↑instBGraph : ArithmeticSemisentence 3)) := fact3_defined _
instance instBFact_definable' : 𝚺₁-Function₃ (instBFact : V → V → V → V) := instBFact_defined'.to_definable

lemma shiftIterV_memFact {x s : V} (hx : IsSemiterm LAct 0 x) (hs : IsSemiterm LAct 0 s) :
    ∀ c : V, shiftIterV (memFact x s) c = memFact (termShiftIterV x c) (termShiftIterV s c) := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih =>
    rw [shiftIterV_succ, ih, shift_memFact (isSemiterm_termShiftIterV hx c) (isSemiterm_termShiftIterV hs c),
      termShiftIterV_succ, termShiftIterV_succ]

lemma shiftIterV_setLenFact {l s : V} (hl : IsSemiterm LAct 0 l) (hs : IsSemiterm LAct 0 s) :
    ∀ c : V, shiftIterV (setLenFact l s) c = setLenFact (termShiftIterV l c) (termShiftIterV s c) := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih =>
    rw [shiftIterV_succ, ih, shift_setLenFact (isSemiterm_termShiftIterV hl c) (isSemiterm_termShiftIterV hs c),
      termShiftIterV_succ, termShiftIterV_succ]

lemma shiftIterV_insFact {t x s : V} (ht : IsSemiterm LAct 0 t) (hx : IsSemiterm LAct 0 x) (hs : IsSemiterm LAct 0 s) :
    ∀ c : V, shiftIterV (insFact t x s) c = insFact (termShiftIterV t c) (termShiftIterV x c) (termShiftIterV s c) := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih =>
    rw [shiftIterV_succ, ih, shift_insFact (isSemiterm_termShiftIterV ht c) (isSemiterm_termShiftIterV hx c)
      (isSemiterm_termShiftIterV hs c), termShiftIterV_succ, termShiftIterV_succ, termShiftIterV_succ]

lemma shiftIterV_instBFact {g n k : V} (hg : IsSemiterm LAct 0 g) (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) :
    ∀ c : V, shiftIterV (instBFact g n k) c = instBFact (termShiftIterV g c) (termShiftIterV n c) (termShiftIterV k c) := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih =>
    rw [shiftIterV_succ, ih, shift_instBFact (isSemiterm_termShiftIterV hg c) (isSemiterm_termShiftIterV hn c)
      (isSemiterm_termShiftIterV hk c), termShiftIterV_succ, termShiftIterV_succ, termShiftIterV_succ]

lemma shiftIterV_boxFact {n k : V} (hn : IsSemiterm LAct 0 n) (hk : IsSemiterm LAct 0 k) :
    ∀ c : V, shiftIterV (boxFact n k) c = boxFact (termShiftIterV n c) (termShiftIterV k c) := by
  intro c
  induction c using ISigma1.sigma1_succ_induction with
  | hP => definability
  | zero => simp
  | succ c ih =>
    rw [shiftIterV_succ, ih, shift_boxFact (isSemiterm_termShiftIterV hn c) (isSemiterm_termShiftIterV hk c),
      termShiftIterV_succ, termShiftIterV_succ]

/-- The target is shift-invariant (a sentence code). -/
lemma shiftIterV_target (χ : Semisentence LAct 1) (k : V) (c : V) :
    shiftIterV (boxFact (qNum χ) (bnum k)) c = boxFact (qNum χ) (bnum k) := by
  rw [shiftIterV_boxFact (isSemiterm_qNum χ) (bnum_term_LAct k), termShiftIterV_qNum, termShiftIterV_bnumTop]

/-! ### 3.2 The root layout -/

/-- **The root layout at offset `i`** — exactly what the walk of the root member `x` and the singleton
chain `{x}` deliver (`rootSteps_ok`, §4): the walk dossier of `x` at `&(i + 2)` (`Cert.DossF` over
`walkPieces`; the kit's discharger converts it to `Layout`'s `DossierAt` with `dossierAt_of_dossF`),
`IsSemiformula 0 &(i + 2)`, the chain `&(i + 1) = insert &(i + 2) 𝟎` with `IsFormulaSet &(i + 1)`,
`&(i + 2) ∈ &(i + 1)`, and the length OBJECT `&i = setLen &(i + 1)`. NOT included (an honest gap):
the NUMERIC length `leFact &i (bnum |x|)`, which `lenSteps` (in flight in `Cert`) derives from the
dossier — the kit's discharger produces it inside the root node's prologue. -/
def RootLayout (Γ x i : V) : Prop :=
  DossF walkPieces Γ 0 x (i + 2) ∧
  neg LAct (piFact (𝟎 : V) (^&(i + 2))) ∈ Γ ∧
  neg LAct (insFact (^&(i + 1)) (^&(i + 2)) (𝟎 : V)) ∈ Γ ∧
  neg LAct (fsetPiFact (^&(i + 1))) ∈ Γ ∧
  neg LAct (memFact (^&(i + 2)) (^&(i + 1))) ∈ Γ ∧
  neg LAct (setLenFact (^&i) (^&(i + 1))) ∈ Γ

/-- The root layout survives any further cut-admitting list, at the moved offset. -/
lemma RootLayout.transport {Γ x i S : V} (hS : NoDrop' S) (h : RootLayout Γ x i) :
    RootLayout (finalCtx Γ S) x (i + shiftsV S) := by
  obtain ⟨hD, hpi, hins, hfs, hmem, hsl⟩ := h
  have h0 : IsSemiterm LAct (0 : V) (𝟎 : V) := isSemiterm_qqZero_LAct 0
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · have := dossF_transport' hS hD
    rwa [add_right_comm] at this
  · have := mem_finalCtx_of_mem' hS hpi
    rwa [shiftIterV_neg (isFormula_piFact h0 (by simp)), shiftIterV_piFact h0 (by simp), termShiftIterV_qqZero,
      termShiftIterV_fvar, add_right_comm] at this
  · have := mem_finalCtx_of_mem' hS hins
    rwa [shiftIterV_neg (isFormula_insFact (by simp) (by simp) h0), shiftIterV_insFact (by simp) (by simp) h0,
      termShiftIterV_qqZero, termShiftIterV_fvar, termShiftIterV_fvar, add_right_comm i 1, add_right_comm i 2] at this
  · have := mem_finalCtx_of_mem' hS hfs
    rwa [shiftIterV_neg (isFormula_fsetPiFact (by simp)), shiftIterV_fsetPiFact (by simp), termShiftIterV_fvar,
      add_right_comm] at this
  · have := mem_finalCtx_of_mem' hS hmem
    rwa [shiftIterV_neg (isFormula_memFact (by simp) (by simp)), shiftIterV_memFact (by simp) (by simp),
      termShiftIterV_fvar, termShiftIterV_fvar, add_right_comm i 2, add_right_comm i 1] at this
  · have := mem_finalCtx_of_mem' hS hsl
    rwa [shiftIterV_neg (isFormula_setLenFact (by simp) (by simp)), shiftIterV_setLenFact (by simp) (by simp),
      termShiftIterV_fvar, termShiftIterV_fvar, add_right_comm i 1] at this

/-! ### 3.3 The kits

`VerifyKit` states, for the RELATION `VerifyGraph W tblN ρ L` (`Verify.lean` §3 — the function
`verifySteps` does not exist yet, §3.6 there), exactly what `DESIGN_fragments.md` §6.3 (`ok`), §6.4 and
§5 (`cost`) promise, specialised to the ROOT (the only node the top calls it at):

* `ok` = §6.3 `verifySteps_ok` at the root: from `Proof TAct ρ x` (the root sequent is `{x}`), the root
  layout at offset `i`, and a witness cap `E ≥ Ck·(dlen ρ + i + 1)` (§5's `E ≤ C₁ g`, plus the root's
  index depth), every verification list is applicable at cap `9`, cut-admitting, has at most
  `Ck·(dlen ρ + 1)` eigenvariables (§5's `shiftsV ≤ C₀ g`), and leaves the root's goal fact
  `goalFact (^&(i + 1 + σ)) (bnum (dlen ρ))` (the sequent `&(i + 1)` shifted `σ` times, `ū = bnum (dlen ρ)`).
  §6.3's remaining conjuncts (`Layout' (finalCtx Γ L) ρ σ`, the parent's objects) are what the ROOT
  layout transports by `RootLayout.transport` — not part of the kit.
* `cost` = §6.4 without `dlen_chainCode_le` (which the top applies itself): the cost sum of `L` is
  §5's cubic `Ck·(g + 1)·(setLen Γ + N + E + (g + 1)²)`, together with §5's context bounds at the
  END of `L` (`setLen ≤ setLen Γ + Ck·E·(g + 1)`: at most `len L ≤ Ck·(g + 1)` facts of length `≤ B·E`;
  `fvOccS ≤ fvOccS Γ + Ck·(g + 1)`: at most nine `^&` witnesses per fact), which the top needs to
  bound its own closing block.

Discharging it: prove §6.3/§6.4 for `VerifyGraph` once the prologue producers land (the §3.6 clause
edit in `Verify.lean`, then `Derivation.induction1 𝚷`), derive the root's numeric length inside the
root prologue from the dossier (`lenSteps`), and read the constant `Ck` off the per-tag bounds. -/
structure VerifyKit (tbl N W tblN : V) (Ck : ℕ) : Prop where
  ok : ∀ {ρ x Γ i E L : V}, Proof TAct ρ x → RootLayout Γ x i → IsFormulaSet LAct Γ →
    (Ck : V) * (dlen TAct ρ + i + 1) ≤ E → VerifyGraph W tblN ρ L →
    ListOK tbl E ((9 : ℕ) : V) Γ L ∧ NoDrop' L ∧ shiftsV L ≤ (Ck : V) * (dlen TAct ρ + 1) ∧
    neg LAct (goalFact (^&(i + 1 + shiftsV L)) (bnum (dlen TAct ρ))) ∈ finalCtx Γ L
  cost : ∀ {ρ x Γ i E L : V}, Proof TAct ρ x → RootLayout Γ x i → IsFormulaSet LAct Γ →
    (Ck : V) * (dlen TAct ρ + i + 1) ≤ E → VerifyGraph W tblN ρ L →
    costSum N E Γ L ≤ (Ck : V) * (dlen TAct ρ + 1) * (setLen LAct Γ + N + E + (dlen TAct ρ + 1) ^ 2) ∧
    setLen LAct (finalCtx Γ L) ≤ setLen LAct Γ + (Ck : V) * (E * (dlen TAct ρ + 1)) ∧
    fvOccS LAct (finalCtx Γ L) ≤ fvOccS LAct Γ + (Ck : V) * (dlen TAct ρ + 1)

/-- **The pinning kit** (`DESIGN_fragments.md` §7.1 steps 1–4 and §7.2, per `χ`) — the ONE place the
closed code `⌜χ⌝` enters the object proof. From a context holding the root layout of the member
`x = instB ⌜χ⌝ k` at offset `i` (its walk dossier at `&(i + 2)`), a list `P` that certifies
`&(i + 2) = subst (bnum k ∷ 0) ⌜χ⌝`, i.e. leaves `instBFact (^&(i + 2 + π)) (qNum χ) (bnum k)` in its
final context, `π = shiftsV P`. Inside it: `describeT`/`bnumZero/One/Even/OddCert` certifying
`bnumGraph t̂ (bnum k)` along the bits of `k` (`O(‖k‖)`), `adjoinTotal`, the per-`χ` closed shape rows
of the numeral `⌜χ⌝` (`O(|χ|)` `sLemma` steps with STANDARD derivations — the constant `Cχ`), the
certified substitution `certSubst` (in flight in `Cert`), and `instBIntro`. Sizes: `≤ Cχ·(‖k‖ + 1)`
steps and shifts (`|instB ⌜χ⌝ k| ≤ |χ|·|bnum k|`), the cost polynomial of §5 in `‖k‖`, and the
context bounds at the end, all with the `χ`-dependent constant `Cχ` — this is why `BoundedInnerNec`
has its `∃ C` AFTER `∀ χ`. The cap requirement `Cχ·(‖k‖ + i + 1) ≤ E` covers the witnesses
`bnum k` (`≤ 6‖k‖ + 1`), `qNum χ` (`≤ 2⌜χ⌝ + 1`, inside `Cχ`) and the indices. -/
structure PinKit (χ : Semisentence LAct 1) (tbl N : V) (Cχ : ℕ) : Prop where
  pin : ∀ (k : V) {Γ i E : V}, RootLayout Γ (instB (⌜χ⌝ : V) k) i → IsFormulaSet LAct Γ →
    (Cχ : V) * (‖k‖ + i + 1) ≤ E →
    ∃ P : V, ListOK tbl E ((9 : ℕ) : V) Γ P ∧ NoDrop' P ∧ shiftsV P ≤ (Cχ : V) * (‖k‖ + 1) ∧
      neg LAct (instBFact (^&(i + 2 + shiftsV P)) (qNum χ) (bnum k)) ∈ finalCtx Γ P ∧
      costSum N E Γ P ≤ (Cχ : V) * (‖k‖ + 1) * (setLen LAct Γ + N + E + (‖k‖ + 1) ^ 2) ∧
      setLen LAct (finalCtx Γ P) ≤ setLen LAct Γ + (Cχ : V) * (E * (‖k‖ + 1)) ∧
      fvOccS LAct (finalCtx Γ P) ≤ fvOccS LAct Γ + (Cχ : V) * (‖k‖ + 1)

end rootLayout

/-! ## 4. The root steps: the walk of the member and the singleton chain (§7.1 steps 3 and 5) -/

section rootSteps

/-- `rootSteps x := describeF walkPieces 0 x ++ chainSteps layoutPieces ?[^&0]`: walk the root member,
then chain it into the root sequent. -/
noncomputable def rootSteps (x : V) : V :=
  appendV (describeF walkPieces 0 x) (chainSteps layoutPieces ?[^&0])

/-- **The root steps are applicable and produce the root layout at offset `0`**: Horn-only,
`descCountF + 2` eigenvariables, at most `12|x| + 13` steps. -/
theorem rootSteps_ok {tbl N x E Γ : V} (htbl : TableOK tbl N) (hT : TopTable tbl) (hx : IsSemiformula LAct 0 x)
    (hΓ : IsFormulaSet LAct Γ) (hE : 2 * formulaLen LAct x + 8 ≤ E) :
    ListOK tbl E ((8 : ℕ) : V) Γ (rootSteps x) ∧ NoDrop (rootSteps x) ∧ HornOnly (rootSteps x) ∧
    shiftsV (rootSteps x) = descCountF walkPieces 0 x + 2 ∧
    len (rootSteps x) + 4 ≤ 12 * formulaLen LAct x + 13 ∧
    RootLayout (finalCtx Γ (rootSteps x)) x 0 := by
  have hE' : 2 * (0 : V) + 2 * formulaLen LAct x + 8 ≤ E := by rwa [mul_zero, zero_add]
  obtain ⟨wok, wnd, wsh, _, wpi⟩ := describeF_ok htbl hT.walkTable hx hE' hΓ
  have who : HornOnly (describeF walkPieces 0 x) := hornOnly_describeF rfl hx
  have wlen := len_describeF_le walkPieces hx
  set Γ₁ := finalCtx Γ (describeF walkPieces 0 x) with hΓ₁
  have hΓ₁f : IsFormulaSet LAct Γ₁ := finalCtx_isFormulaSet 8 htbl hΓ wok
  have hpi₁ : neg LAct (piFact (𝟎 : V) (^&0)) ∈ Γ₁ := by rwa [cTV_zero] at wpi
  have hlen1 : len (?[^&0] : V) = 1 := by simp
  have h8 : (8 : V) ≤ E := le_trans le_add_self hE
  have hE1 : (1 : V) ≤ E := le_trans (by norm_num) h8
  have hEc : len (?[^&0] : V) + 2 ≤ E := by rw [hlen1]; exact le_trans (by norm_num) h8
  have hxs : ∀ i < len (?[^&0] : V), IsSemiterm LAct 0 (?[^&0] : V).[i] ∧
      termLen LAct (termShiftIterV (?[^&0] : V).[i] (len (?[^&0] : V) + 1)) ≤ E ∧
      neg LAct (piFact (𝟎 : V) (?[^&0] : V).[i]) ∈ Γ₁ := by
    intro i hi
    rw [hlen1] at hi
    have hi0 : i = 0 := by
      rcases zero_or_succ i with rfl | ⟨i, rfl⟩
      · rfl
      · exact absurd hi (not_lt.mpr le_add_self)
    subst hi0
    rw [nth_adjoin_zero, hlen1, termShiftIterV_fvar, termLen_fvar]
    refine ⟨by simp, ?_, hpi₁⟩
    calc (0 : V) + (1 + 1) + 1 = 3 := by norm_num
      _ ≤ 8 := by norm_num
      _ ≤ E := h8
  obtain ⟨cok, cnd, cho, csh, clen, cfacts, csl⟩ :=
    chainSteps_ok htbl hT.layoutTable rfl hΓ₁f (by rw [hlen1]) hEc hxs
  rw [hlen1] at csh clen cfacts
  have c2 : (1 : V) + 1 = 2 := one_add_one_eq_two
  rw [c2] at csh cfacts
  obtain ⟨cins, cfs, cmem⟩ := cfacts 0 (by simp)
  simp only [nth_adjoin_zero, termShiftIterV_fvar, zero_add] at cins cmem cfs
  have hprev : prevAt (2 : V) 1 = (𝟎 : V) := by
    unfold prevAt; rw [if_pos c2]
  rw [hprev] at cins
  refine ⟨listOK_appendV wok cok, noDrop_appendV wnd cnd, hornOnly_appendV who cho, ?_, ?_, ?_⟩
  · rw [rootSteps, shiftsV_appendV, wsh, csh]
  · rw [rootSteps, len_appendV]
    calc len (describeF walkPieces 0 x) + len (chainSteps layoutPieces ?[^&0]) + 4
        = (len (describeF walkPieces 0 x) + 4) + len (chainSteps layoutPieces ?[^&0]) := by ring
      _ ≤ 12 * formulaLen LAct x + (7 * 1 + 6) := add_le_add wlen clen
      _ = 12 * formulaLen LAct x + 13 := by norm_num
  · rw [rootSteps, finalCtx_appendV, ← hΓ₁]
    have hD : DossF walkPieces Γ₁ 0 x 0 := dossF_of_walk (describeF_noDrop_shifts htbl hT.walkTable rfl hx).1
    have hD' := dossF_transport cnd hD
    rw [csh, zero_add] at hD'
    have hpi₂ := mem_finalCtx_of_mem cnd hpi₁
    rw [csh, shiftIterV_neg (isFormula_piFact (isSemiterm_qqZero_LAct 0) (by simp)),
      shiftIterV_piFact (isSemiterm_qqZero_LAct 0) (by simp), termShiftIterV_qqZero, termShiftIterV_fvar,
      zero_add] at hpi₂
    exact ⟨by simpa using hD', by simpa using hpi₂, by simpa using cins, by simpa using cfs,
      by simpa using cmem, by simpa using csl⟩

end rootSteps

/-! ## 5. The closing steps (§7.1 steps 6–9, folded): recover the root goal, the four numeral lemmas,
the five rows to the target fact -/

section closeSteps

/-- `closeSteps χ k ρ js tblN tblL tblM`: with the root goal fact `goalFact (^&js) (bnum (dlen ρ))`, the chain
fact `insFact &js &(js+1) 𝟎` and the pinned `instBFact &(js+1) (qNum χ) (bnum k)` in context —
`goalElim` (2 shifts: `d = &1`, `n = &0`, the sequent at `&(js+2)`, the member at `&(js+3)`), then
`sLemma` N5 (`‖k‖`), N4 twice (`‖k‖·‖k‖`, `‖k‖²·‖k‖ = gBudget k`), N2 (`dlen ρ ≤ gBudget k`), then
`dlenDefIntro [&1, &0]`, `proofIntro [&(js+2), &(js+3), &1]`, `leTrans [bnum g, bnum (dlen ρ), &0]`,
`lenDerIntro [&1, &0, &(js+3), bnum g]`, `gIntroNum [bnum k, bnum ‖k‖, bnum ‖k‖², bnum g]`,
`boxIntro [bnum g, &(js+3), bnum k, qNum χ]` — whose conclusion is the target `boxFact (qNum χ) (bnum k)`. -/
noncomputable def closeSteps (χ : Semisentence LAct 1) (k ρ js tblN tblL tblM : V) : V :=
  appendV (goalElim (^&js) (bnum (dlen TAct ρ)))
    (sLemma (lengthEqFact k) (lengthEqCode tblL tblN k) ∷
     sLemma (mulFact ‖k‖ ‖k‖) (mulEqCode tblM tblN ‖k‖ ‖k‖) ∷
     sLemma (mulFact (‖k‖ * ‖k‖) ‖k‖) (mulEqCode tblM tblN (‖k‖ * ‖k‖) ‖k‖) ∷
     sLemma (leFact (bnum (dlen TAct ρ)) (bnum (gBudget k))) (leCode tblN (dlen TAct ρ) (gBudget k)) ∷
     mkStep topPieces 150 ?[^&1, ^&0] ∷
     mkStep topPieces 151 ?[^&(js + 2), ^&(js + 3), ^&1] ∷
     mkStep topPieces 110 ?[bnum (gBudget k), bnum (dlen TAct ρ), ^&0] ∷
     mkStep topPieces 153 ?[^&1, ^&0, ^&(js + 3), bnum (gBudget k)] ∷
     mkStep topPieces 152 ?[bnum k, bnum ‖k‖, bnum (‖k‖ * ‖k‖), bnum (gBudget k)] ∷
     mkStep topPieces 154 ?[bnum (gBudget k), ^&(js + 3), bnum k, qNum χ] ∷ (0 : V))

lemma mem_ins {x a Γ : V} (h : x ∈ Γ) : x ∈ insert a Γ := by simp [h]

lemma eqFact_eq_eqFactB (a b : V) : eqFact a b = eqFactB a b := rfl

/-- **The closing steps are applicable** and end with the target fact: cap `8`, cut-admitting, `2` shifts,
`15` steps. Hypotheses: the three tables, `dlen ρ ≤ gBudget k` (the N2 lemma is TRUE), the witness caps,
and the three facts. -/
theorem closeSteps_ok (χ : Semisentence LAct 1) {tbl N E Γ tblN N' B' tblL N₂ B₂ tblM N₃ B₃ k ρ js : V}
    (htbl : TableOK tbl N) (hT : TopTable tbl) (htblN : NumTableOK tblN N' B') (htblL : LenTableOK tblL N₂ B₂)
    (htblM : MulTableOK tblM N₃ B₃) (hΓ : IsFormulaSet LAct Γ) (hρ : dlen TAct ρ ≤ gBudget k)
    (hE1 : js + 4 ≤ E) (hEq : termLen LAct (qNum χ : V) ≤ E) (hEk : termLen LAct (bnum k) ≤ E)
    (hEl : termLen LAct (bnum ‖k‖) ≤ E) (hEb : termLen LAct (bnum (‖k‖ * ‖k‖)) ≤ E)
    (hEg : termLen LAct (bnum (gBudget k)) ≤ E) (hEd : termLen LAct (bnum (dlen TAct ρ)) ≤ E)
    (hgoal : neg LAct (goalFact (^&js) (bnum (dlen TAct ρ))) ∈ Γ)
    (hins : neg LAct (insFact (^&js) (^&(js + 1)) (𝟎 : V)) ∈ Γ)
    (hinst : neg LAct (instBFact (^&(js + 1)) (qNum χ) (bnum k)) ∈ Γ) :
    ListOK tbl E ((8 : ℕ) : V) Γ (closeSteps χ k ρ js tblN tblL tblM) ∧
    NoDrop' (closeSteps χ k ρ js tblN tblL tblM) ∧ shiftsV (closeSteps χ k ρ js tblN tblL tblM) = 2 ∧
    len (closeSteps χ k ρ js tblN tblL tblM) = 15 ∧
    neg LAct (boxFact (qNum χ) (bnum k)) ∈ finalCtx Γ (closeSteps χ k ρ js tblN tblL tblM) := by
  -- the witnesses
  have h0 : IsSemiterm LAct (0 : V) (𝟎 : V) := isSemiterm_qqZero_LAct 0
  have hq : IsSemiterm LAct (0 : V) (qNum χ) := isSemiterm_qNum χ
  have hbk : IsSemiterm LAct (0 : V) (bnum k) := isSemiterm_bnum_LAct 0 k
  have hbl : IsSemiterm LAct (0 : V) (bnum ‖k‖) := isSemiterm_bnum_LAct 0 _
  have hbb : IsSemiterm LAct (0 : V) (bnum (‖k‖ * ‖k‖)) := isSemiterm_bnum_LAct 0 _
  have hbg : IsSemiterm LAct (0 : V) (bnum (gBudget k)) := isSemiterm_bnum_LAct 0 _
  have hbd : IsSemiterm LAct (0 : V) (bnum (dlen TAct ρ)) := isSemiterm_bnum_LAct 0 _
  have hE4 : (4 : V) ≤ E := le_trans le_add_self hE1
  have hf0 : termLen LAct (^&0 : V) ≤ E := termLen_fvar_le (le_trans (by norm_num) hE4)
  have hf1 : termLen LAct (^&1 : V) ≤ E := termLen_fvar_le (le_trans (by norm_num) hE4)
  have hf2 : termLen LAct (^&(js + 2) : V) ≤ E := termLen_fvar_le (by
    calc js + 2 + 1 = js + 3 := by ring
      _ ≤ js + 4 := add_le_add le_rfl (by norm_num)
      _ ≤ E := hE1)
  have hf3 : termLen LAct (^&(js + 3) : V) ≤ E := termLen_fvar_le (by
    calc js + 3 + 1 = js + 4 := by ring
      _ ≤ E := hE1)
  have e2 : (js : V) + 1 + 1 = js + 2 := by rw [add_assoc, one_add_one_eq_two]
  have e3 : (js : V) + 1 + 2 = js + 3 := by rw [add_assoc]; norm_num
  -- the recovery of the goal
  obtain ⟨gok, gnd, gsh, _, gder, gfst, gdlen, gle⟩ := goalElim_ok 8 htbl hΓ (by simp) hbd hgoal
  rw [termShift_fvar, termShift_fvar, e2] at gfst
  rw [termShift_bnum, termShift_bnum] at gle
  have hΓ₀ : IsFormulaSet LAct (finalCtx Γ (goalElim (^&js) (bnum (dlen TAct ρ)))) :=
    finalCtx_isFormulaSet 8 htbl hΓ gok
  have hins₀ := mem_finalCtx_of_mem' gnd hins
  rw [gsh, shiftIterV_neg (isFormula_insFact (by simp) (by simp) h0), shiftIterV_insFact (by simp) (by simp) h0,
    termShiftIterV_fvar, termShiftIterV_fvar, termShiftIterV_qqZero, e3] at hins₀
  have hinst₀ := mem_finalCtx_of_mem' gnd hinst
  rw [gsh, shiftIterV_neg (isFormula_instBFact (by simp) hq hbk), shiftIterV_instBFact (by simp) hq hbk,
    termShiftIterV_fvar, termShiftIterV_qNum, termShiftIterV_bnumTop, e3] at hinst₀
  set Γ₀ := finalCtx Γ (goalElim (^&js) (bnum (dlen TAct ρ))) with hΓ₀def
  -- the four numeral lemmas
  have ok₁ : StepOK tbl E ((8 : ℕ) : V) Γ₀ (sLemma (lengthEqFact k) (lengthEqCode tblL tblN k)) :=
    stepOK_sLemma hΓ₀ (lemmaOK_lengthEq htblN htblL k)
  have cx₁ := ctxAfter_sLemma Γ₀ (lengthEqFact k) (lengthEqCode tblL tblN k)
  have hΓ₁ : IsFormulaSet LAct (insert (neg LAct (lengthEqFact k)) Γ₀) := cx₁ ▸ isFormulaSet_ctxAfter 8 htbl ok₁
  have ok₂ : StepOK tbl E ((8 : ℕ) : V) (insert (neg LAct (lengthEqFact k)) Γ₀)
      (sLemma (mulFact ‖k‖ ‖k‖) (mulEqCode tblM tblN ‖k‖ ‖k‖)) :=
    stepOK_sLemma hΓ₁ (lemmaOK_mulEq htblN htblM _ _)
  have cx₂ := ctxAfter_sLemma (insert (neg LAct (lengthEqFact k)) Γ₀) (mulFact ‖k‖ ‖k‖) (mulEqCode tblM tblN ‖k‖ ‖k‖)
  have hΓ₂ : IsFormulaSet LAct (insert (neg LAct (mulFact ‖k‖ ‖k‖)) (insert (neg LAct (lengthEqFact k)) Γ₀)) :=
    cx₂ ▸ isFormulaSet_ctxAfter 8 htbl ok₂
  have ok₃ : StepOK tbl E ((8 : ℕ) : V) (insert (neg LAct (mulFact ‖k‖ ‖k‖)) (insert (neg LAct (lengthEqFact k)) Γ₀))
      (sLemma (mulFact (‖k‖ * ‖k‖) ‖k‖) (mulEqCode tblM tblN (‖k‖ * ‖k‖) ‖k‖)) :=
    stepOK_sLemma hΓ₂ (lemmaOK_mulEq htblN htblM _ _)
  have cx₃ := ctxAfter_sLemma (insert (neg LAct (mulFact ‖k‖ ‖k‖)) (insert (neg LAct (lengthEqFact k)) Γ₀))
    (mulFact (‖k‖ * ‖k‖) ‖k‖) (mulEqCode tblM tblN (‖k‖ * ‖k‖) ‖k‖)
  set Γ₃ := insert (neg LAct (mulFact (‖k‖ * ‖k‖) ‖k‖))
    (insert (neg LAct (mulFact ‖k‖ ‖k‖)) (insert (neg LAct (lengthEqFact k)) Γ₀)) with hΓ₃def
  have hΓ₃ : IsFormulaSet LAct Γ₃ := cx₃ ▸ isFormulaSet_ctxAfter 8 htbl ok₃
  have ok₄ : StepOK tbl E ((8 : ℕ) : V) Γ₃
      (sLemma (leFact (bnum (dlen TAct ρ)) (bnum (gBudget k))) (leCode tblN (dlen TAct ρ) (gBudget k))) :=
    stepOK_sLemma hΓ₃ (lemmaOK_of (isFormula_leFact_bnum _ _) (leCode_proof htblN hρ))
  have cx₄ := ctxAfter_sLemma Γ₃ (leFact (bnum (dlen TAct ρ)) (bnum (gBudget k))) (leCode tblN (dlen TAct ρ) (gBudget k))
  set Γ₄ := insert (neg LAct (leFact (bnum (dlen TAct ρ)) (bnum (gBudget k)))) Γ₃ with hΓ₄def
  have hΓ₄ : IsFormulaSet LAct Γ₄ := cx₄ ▸ isFormulaSet_ctxAfter 8 htbl ok₄
  -- the facts so far, in `Γ₄`
  have m_der : neg LAct (derFact (^&1 : V)) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins gder)))
  have m_fst : neg LAct (fstIdxFact (^&(js + 2)) (^&1)) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins gfst)))
  have m_dlen : neg LAct (dlenFact (^&1 : V) (^&0)) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins gdlen)))
  have m_le : neg LAct (leFact (^&0) (bnum (dlen TAct ρ))) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins gle)))
  have m_ins : neg LAct (insFact (^&(js + 2)) (^&(js + 3)) (𝟎 : V)) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins hins₀)))
  have m_inst : neg LAct (instBFact (^&(js + 3)) (qNum χ) (bnum k)) ∈ Γ₄ := mem_ins (mem_ins (mem_ins (mem_ins hinst₀)))
  have m_len : neg LAct (lengthFact (bnum ‖k‖) (bnum k)) ∈ Γ₄ := by
    have : neg LAct (lengthEqFact k) ∈ Γ₄ := mem_ins (by rw [hΓ₃def]; simp)
    exact this
  have m_mul1 : neg LAct (eqFactB (bnum ‖k‖ ^* bnum ‖k‖) (bnum (‖k‖ * ‖k‖))) ∈ Γ₄ := by
    have : neg LAct (mulFact ‖k‖ ‖k‖) ∈ Γ₄ := mem_ins (by rw [hΓ₃def]; simp)
    exact this
  have m_mul2 : neg LAct (eqFactB (bnum (‖k‖ * ‖k‖) ^* bnum ‖k‖) (bnum (gBudget k))) ∈ Γ₄ := by
    have : neg LAct (mulFact (‖k‖ * ‖k‖) ‖k‖) ∈ Γ₄ := mem_ins (by rw [hΓ₃def]; simp)
    exact this
  have m_leg : neg LAct (leFact (bnum (dlen TAct ρ)) (bnum (gBudget k))) ∈ Γ₄ := by rw [hΓ₄def]; simp
  -- step 5: dlenDefIntro
  obtain ⟨ok₅, tg₅, cx₅⟩ := tok_dlenDefIntro (wd := ^&1) (wn := ^&0) htbl hT rfl hΓ₄ (by simp) hf1 (by simp) hf0 m_der m_dlen
  set Γ₅ := insert (neg LAct (dlenDefFact (^&0) (^&1))) Γ₄ with hΓ₅def
  have hΓ₅ : IsFormulaSet LAct Γ₅ := cx₅ ▸ isFormulaSet_ctxAfter 8 htbl ok₅
  -- step 6: proofIntro
  obtain ⟨ok₆, tg₆, cx₆⟩ := tok_proofIntro (ws := ^&(js + 2)) (wg := ^&(js + 3)) (wd := ^&1) htbl hT rfl hΓ₅
    (by simp) hf2 (by simp) hf3 (by simp) hf1 (mem_ins m_ins) (mem_ins m_fst) (mem_ins m_der)
  set Γ₆ := insert (neg LAct (proofFact (^&1) (^&(js + 3)))) Γ₅ with hΓ₆def
  have hΓ₆ : IsFormulaSet LAct Γ₆ := cx₆ ▸ isFormulaSet_ctxAfter 8 htbl ok₆
  -- step 7: leTrans
  obtain ⟨ok₇, tg₇, cx₇⟩ := tfok_leTrans (wz := bnum (gBudget k)) (wy := bnum (dlen TAct ρ)) (wx := ^&0) htbl hT rfl hΓ₆
    hbg hEg hbd hEd (by simp) hf0 (mem_ins (mem_ins m_le)) (mem_ins (mem_ins m_leg))
  set Γ₇ := insert (neg LAct (leFact (^&0) (bnum (gBudget k)))) Γ₆ with hΓ₇def
  have hΓ₇ : IsFormulaSet LAct Γ₇ := cx₇ ▸ isFormulaSet_ctxAfter 8 htbl ok₇
  -- step 8: lenDerIntro
  obtain ⟨ok₈, tg₈, cx₈⟩ := tok_lenDerIntro (wd := ^&1) (wn := ^&0) (wg := ^&(js + 3)) (wa := bnum (gBudget k)) htbl hT rfl hΓ₇
    (by simp) hf1 (by simp) hf0 (by simp) hf3 hbg hEg (mem_ins (by rw [hΓ₆def]; simp))
    (mem_ins (mem_ins (by rw [hΓ₅def]; simp))) (by rw [hΓ₇def]; simp)
  set Γ₈ := insert (neg LAct (lenDerFact (bnum (gBudget k)) (^&(js + 3)))) Γ₇ with hΓ₈def
  have hΓ₈ : IsFormulaSet LAct Γ₈ := cx₈ ▸ isFormulaSet_ctxAfter 8 htbl ok₈
  -- step 9: gIntroNum
  obtain ⟨ok₉, tg₉, cx₉⟩ := tok_gIntroNum (wk := bnum k) (wl := bnum ‖k‖) (wb := bnum (‖k‖ * ‖k‖)) (wa := bnum (gBudget k))
    htbl hT rfl hΓ₈ hbk hEk hbl hEl hbb hEb hbg hEg
    (mem_ins (mem_ins (mem_ins (mem_ins m_len)))) (mem_ins (mem_ins (mem_ins (mem_ins m_mul1))))
    (mem_ins (mem_ins (mem_ins (mem_ins m_mul2))))
  set Γ₉ := insert (neg LAct (gFact (bnum (gBudget k)) (bnum k))) Γ₈ with hΓ₉def
  have hΓ₉ : IsFormulaSet LAct Γ₉ := cx₉ ▸ isFormulaSet_ctxAfter 8 htbl ok₉
  -- step 10: boxIntro
  obtain ⟨ok₁₀, tg₁₀, cx₁₀⟩ := tok_boxIntro (wa := bnum (gBudget k)) (wg := ^&(js + 3)) (wk := bnum k) (wn := qNum χ)
    htbl hT rfl hΓ₉ hbg hEg (by simp) hf3 hbk hEk hq hEq (by rw [hΓ₉def]; simp)
    (mem_ins (mem_ins (mem_ins (mem_ins (mem_ins m_inst))))) (mem_ins (by rw [hΓ₈def]; simp))
  -- assembly
  have hfin : finalCtx Γ (closeSteps χ k ρ js tblN tblL tblM) =
      insert (neg LAct (boxFact (qNum χ) (bnum k))) Γ₉ := by
    unfold closeSteps
    rw [finalCtx_appendV, ← hΓ₀def, finalCtx_cons, cx₁, finalCtx_cons, cx₂, finalCtx_cons, cx₃,
      finalCtx_cons, cx₄, finalCtx_cons, cx₅, finalCtx_cons, cx₆,
      finalCtx_cons, cx₇, finalCtx_cons, cx₈, finalCtx_cons, cx₉,
      finalCtx_single, cx₁₀]
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · unfold closeSteps
    refine listOK_appendV gok ?_
    rw [← hΓ₀def]
    refine listOK_cons ok₁ ?_; rw [cx₁]
    refine listOK_cons ok₂ ?_; rw [cx₂]
    refine listOK_cons ok₃ ?_; rw [cx₃]
    refine listOK_cons ok₄ ?_; rw [cx₄]
    refine listOK_cons ok₅ ?_; rw [cx₅]
    refine listOK_cons ok₆ ?_; rw [cx₆]
    refine listOK_cons ok₇ ?_; rw [cx₇]
    refine listOK_cons ok₈ ?_; rw [cx₈]
    refine listOK_cons ok₉ ?_; rw [cx₉]
    exact listOK_single ok₁₀
  · unfold closeSteps
    refine noDrop'_appendV gnd ?_
    exact noDrop'_cons (by simp) (noDrop'_cons (by simp) (noDrop'_cons (by simp) (noDrop'_cons (by simp)
      (noDrop'_cons (by rw [tg₅]; simp) (noDrop'_cons (by rw [tg₆]; simp) (noDrop'_cons (by rw [tg₇]; simp)
      (noDrop'_cons (by rw [tg₈]; simp) (noDrop'_cons (by rw [tg₉]; simp) (noDrop'_single (by rw [tg₁₀]; simp))))))))))
  · unfold closeSteps
    rw [shiftsV_appendV, gsh, shiftsV_cons, shiftsV_cons, shiftsV_cons, shiftsV_cons, shiftsV_cons, shiftsV_cons,
      shiftsV_cons, shiftsV_cons, shiftsV_cons, shiftsV_single, tg₅, tg₆, tg₇, tg₈, tg₉, tg₁₀]
    simp
  · unfold closeSteps
    rw [len_appendV, len_goalElim]; simp [len_adjoin]; norm_num
  · rw [hfin]; simp

end closeSteps

/-! ## 6. The whole list, its derivation, and the explicit cost -/

section assembly

/-- Negation preserves the length of a formula code. -/
lemma formulaLen_neg_eq {n p : V} (hp : IsSemiformula LAct n p) : formulaLen LAct (neg LAct p) = formulaLen LAct p := by
  apply IsSemiformula.pi1_structural_induction (P := fun n p ↦ formulaLen LAct (neg LAct p) = formulaLen LAct p)
    ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ hp
  · definability
  · intro n k r v hr hv; rw [neg_rel hr hv.isUTerm, formulaLen_nrel hr hv.isUTerm, formulaLen_rel hr hv.isUTerm]
  · intro n k r v hr hv; rw [neg_nrel hr hv.isUTerm, formulaLen_rel hr hv.isUTerm, formulaLen_nrel hr hv.isUTerm]
  · intro n; simp
  · intro n; simp
  · intro n p q hp hq ihp ihq
    rw [neg_and hp.isUFormula hq.isUFormula, formulaLen_or (IsSemiformula.neg_iff.mpr hp).isUFormula
      (IsSemiformula.neg_iff.mpr hq).isUFormula, formulaLen_and hp.isUFormula hq.isUFormula, ihp, ihq]
  · intro n p q hp hq ihp ihq
    rw [neg_or hp.isUFormula hq.isUFormula, formulaLen_and (IsSemiformula.neg_iff.mpr hp).isUFormula
      (IsSemiformula.neg_iff.mpr hq).isUFormula, formulaLen_or hp.isUFormula hq.isUFormula, ihp, ihq]
  · intro n p hp ih
    rw [neg_all hp.isUFormula, formulaLen_exs (IsSemiformula.neg_iff.mpr hp).isUFormula, formulaLen_all hp.isUFormula, ih]
  · intro n p hp ih
    rw [neg_ex hp.isUFormula, formulaLen_all (IsSemiformula.neg_iff.mpr hp).isUFormula, formulaLen_exs hp.isUFormula, ih]

/-! ### The witness cap of the top — thirteen named requirements

Each requirement of §4–§5 and of the two kits is ONE named summand of `Etop`, so that each is `≤ Etop`
by a chain of `le_self_add`/`le_add_self` (TRAP: with summands that are themselves sums, the
`?a + ?b` unification of that chain backtracks into `whnf` and times out — the names make the
summands atomic). -/

/-- The walk of the root member (`rootSteps_ok`). -/
noncomputable def eWalk (χ : Semisentence LAct 1) (k : V) : V := 2 * formulaLen LAct (instB (⌜χ⌝ : V) k) + 8
/-- The pin kit at offset `0`. -/
noncomputable def ePin (k : V) (Cχ : ℕ) : V := (Cχ : V) * (‖k‖ + 0 + 1)
/-- The verify kit at offset `π ≤ Cχ(‖k‖ + 1)`. -/
noncomputable def eVer (k d : V) (Ck Cχ : ℕ) : V := (Ck : V) * (d + (0 + (Cχ : V) * (‖k‖ + 1)) + 1)
/-- The closing block's indices: `js + 4` with `js = π + 1 + σ`. -/
noncomputable def eJs (k d : V) (Ck Cχ : ℕ) : V := (Cχ : V) * (‖k‖ + 1) + 1 + (Ck : V) * (d + 1) + 4
noncomputable def eQ (χ : Semisentence LAct 1) : V := termLen LAct (qNum χ : V)
noncomputable def eK (k : V) : V := termLen LAct (bnum k)
noncomputable def eL (k : V) : V := termLen LAct (bnum ‖k‖)
noncomputable def eB (k : V) : V := termLen LAct (bnum (‖k‖ * ‖k‖))
noncomputable def eG (k : V) : V := termLen LAct (bnum (gBudget k))
noncomputable def eD (d : V) : V := termLen LAct (bnum d)
/-- The three numeral-fact length requirements (N5, N4, N4). -/
noncomputable def eN5 (k : V) : V := 12 * ‖k‖ + 3
noncomputable def eN4a (k : V) : V := 12 * ‖‖k‖ * ‖k‖ + ‖k‖ + ‖k‖‖ + 3
noncomputable def eN4b (k : V) : V := 12 * ‖‖k‖ * ‖k‖ * ‖k‖ + ‖k‖ * ‖k‖ + ‖k‖‖ + 3

/-- **The witness cap of the top**: the sum of the thirteen requirements. -/
noncomputable def Etop (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : V :=
  eWalk χ k + ePin k Cχ + eVer k d Ck Cχ + eJs k d Ck Cχ + eQ χ + eK k + eL k + eB k + eG k + eD d +
  eN5 k + eN4a k + eN4b k

/-! Each requirement is below the cap (thirteen chains of `le_self_add`/`le_add_self`). -/
lemma le_Etop_walk (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eWalk χ k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_pin (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : ePin k Cχ ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_ver (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eVer k d Ck Cχ ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_js (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eJs k d Ck Cχ ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_q (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eQ χ ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_k (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eK k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_l (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eL k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_b (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eB k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_g (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eG k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add) le_self_add
lemma le_Etop_d (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eD d ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_trans (le_add_self) le_self_add) le_self_add) le_self_add
lemma le_Etop_n5 (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eN5 k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_trans (le_add_self) le_self_add) le_self_add
lemma le_Etop_n4a (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eN4a k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_trans (le_add_self) le_self_add
lemma le_Etop_n4b (χ : Semisentence LAct 1) (k d : V) (Ck Cχ : ℕ) : eN4b k ≤ Etop χ k d Ck Cχ := by
  unfold Etop; exact le_add_self

/-! ### The bound, piece by piece (`S`/`F` = `setLen`/`fvOccS` of the context at the start of each block) -/

noncomputable def topS1 (B E S₀ F₀ Lr : V) : V := S₀ + Lr * F₀ + (Lr * Lr + Lr) * (4 * (B * E))
noncomputable def topF1 (B E F₀ Lr : V) : V := F₀ + Lr * (4 * (B * E))
noncomputable def topS2 (B E Cχ lk S₀ F₀ Lr : V) : V := topS1 B E S₀ F₀ Lr + Cχ * (E * (lk + 1))
noncomputable def topF2 (B E Cχ lk F₀ Lr : V) : V := topF1 B E F₀ Lr + Cχ * (lk + 1)
noncomputable def topS3 (B E Ck Cχ lk d S₀ F₀ Lr : V) : V := topS2 B E Cχ lk S₀ F₀ Lr + Ck * (E * (d + 1))
noncomputable def topF3 (B E Ck Cχ lk d F₀ Lr : V) : V := topF2 B E Cχ lk F₀ Lr + Ck * (d + 1)
noncomputable def topQ (B E Ck Cχ lk d S₀ F₀ Lr : V) : V := 4 * topS3 B E Ck Cχ lk d S₀ F₀ Lr + B * E
/-- The `sLemma` derivations of the closing block, summed (N5, N4, N4, N2 — `leCode` through `addCode`). -/
noncomputable def topD (N' B' N₂ B₂ N₃ B₃ k d : V) : V :=
  lengthEqBound N' B' N₂ B₂ k + mulEqBound N' B' N₃ B₃ ‖k‖ ‖k‖ + mulEqBound N' B' N₃ B₃ (‖k‖ * ‖k‖) ‖k‖ +
  ((‖d‖ + 1) * (‖gBudget k‖ + 2) * nodeCost N' B' (12 * ‖gBudget k‖ + 3) + nodeCost N' B' (12 * ‖gBudget k‖ + 3))

/-- **The explicit bound**: leaf + root (Horn-only, `costSum_le_of_hornOnly`) + pin kit + verify kit +
closing block (`costSum_le_of_sizeOK` at cap `8`, `15` steps). -/
noncomputable def topBound (N B E Ck Cχ lk d S₀ F₀ Lr D : V) : V :=
  (topS3 B E Ck Cχ lk d S₀ F₀ Lr + 15 * topF3 B E Ck Cχ lk d F₀ Lr +
      (15 * 15 + 15) * growK B E (topQ B E Ck Cχ lk d S₀ F₀ Lr) + 1) +
  Lr * (stepK N E B + 36 * topS1 B E S₀ F₀ Lr) +
  Cχ * (lk + 1) * (topS1 B E S₀ F₀ Lr + N + E + (lk + 1) ^ 2) +
  Ck * (d + 1) * (topS2 B E Cχ lk S₀ F₀ Lr + N + E + (d + 1) ^ 2) +
  15 * (costK N E B ((8 : ℕ) : V) (topQ B E Ck Cχ lk d S₀ F₀ Lr) D +
    (3 * ((8 : ℕ) : V) + 11) * ((topS3 B E Ck Cχ lk d S₀ F₀ Lr + 15 * topF3 B E Ck Cχ lk d F₀ Lr +
      (15 * 15 + 15) * growK B E (topQ B E Ck Cχ lk d S₀ F₀ Lr)) +
      (topF3 B E Ck Cχ lk d F₀ Lr + 15 * growK B E (topQ B E Ck Cχ lk d S₀ F₀ Lr))))

/-- The top list for a pin list `P` and a verification list `L`. -/
noncomputable def topList (χ : Semisentence LAct 1) (k ρ P L tblN tblL tblM : V) : V :=
  appendV (rootSteps (instB (⌜χ⌝ : V) k))
    (appendV P (appendV L (closeSteps χ k ρ (0 + shiftsV P + 1 + shiftsV L) tblN tblL tblM)))

lemma dlen_leCode_le' {tbl N B : V} (htbl : NumTableOK tbl N B) {a b : V} (hab : a ≤ b) :
    dlen TAct (leCode tbl a b) ≤ (‖a‖ + 1) * (‖b‖ + 2) * nodeCost N B (12 * ‖b‖ + 3) + nodeCost N B (12 * ‖b‖ + 3) := by
  refine le_trans (dlen_leCode_le htbl hab) (add_le_add ?_ le_rfl)
  have := dlen_addCode_le htbl a (b - a)
  rwa [add_tsub_cancel_of_le hab] at this

/-- The Frag1 row `leTrans` (110) read from the top pieces is a Horn step (tag `0`). -/
lemma ttag_leTrans (ev : V) : sTag (mkStep (topPieces : V) (110 : V) ev) = 0 := by
  have h1 := mkStep_topPieces_lt 110 (by decide) ev
  have h2 := mkStep_frag2Pieces_lt 110 (by decide) ev
  simp only [Nat.cast_ofNat] at h1 h2
  rw [h1, h2]
  exact ftag_leTrans rfl ev

/-- **The top, assembled**: from a proof code `ρ` of the `k`-instance with `dlen ρ ≤ gBudget k`, a
verification list `L`, the two kits and the tables, a proof code of the `k`-instance of the box of length
`≤ topBound …`, for every cap `E ≥ Etop`. The list is `rootSteps ++ P ++ L ++ closeSteps` and the leaf is
`axL` on the (transported) target. -/
theorem top_main (χ : Semisentence LAct 1) {tbl N B W tblN N' B' tblL N₂ B₂ tblM N₃ B₃ : V} {Ck Cχ : ℕ}
    (htbl : TableOK tbl N) (hT : TopTable tbl) (hB : ∀ j < len tbl, formulaLen LAct (rowB tbl.[j]) ≤ B)
    (hPl : formulaLen LAct (Plength : V) ≤ B) (hPeq : formulaLen LAct (Peq : V) ≤ B) (hPle : formulaLen LAct (Ple : V) ≤ B)
    (htblN : NumTableOK tblN N' B') (htblL : LenTableOK tblL N₂ B₂) (htblM : MulTableOK tblM N₃ B₃)
    (hkit : VerifyKit tbl N W tblN Ck) (hpin : PinKit χ tbl N Cχ)
    {k ρ : V} (hρ : Proof TAct ρ (instB (⌜χ⌝ : V) k)) (hlen : dlen TAct ρ ≤ gBudget k)
    {L : V} (hL : VerifyGraph W tblN ρ L) {E : V} (hE : Etop χ k (dlen TAct ρ) Ck Cχ ≤ E) :
    ∃ e Lr : V, LenDerivable TAct e (instB (⌜Box_g χ⌝ : V) k) ∧
      Lr + 4 ≤ 12 * formulaLen LAct (instB (⌜χ⌝ : V) k) + 13 ∧
      e ≤ topBound N B E Ck Cχ ‖k‖ (dlen TAct ρ) (setLen LAct (insert (boxFact (qNum χ) (bnum k)) (∅ : V)))
        (fvOccS LAct (insert (boxFact (qNum χ) (bnum k)) (∅ : V))) Lr (topD N' B' N₂ B₂ N₃ B₃ k (dlen TAct ρ)) := by
  obtain ⟨x, hxdef⟩ : ∃ x, x = instB (⌜χ⌝ : V) k := ⟨_, rfl⟩
  obtain ⟨T, hTdef⟩ : ∃ T, T = boxFact (qNum χ) (bnum k) := ⟨_, rfl⟩
  obtain ⟨Γ₀, hΓ₀def⟩ : ∃ Γ₀ : V, Γ₀ = insert T (∅ : V) := ⟨_, rfl⟩
  rw [← hxdef] at hρ ⊢
  rw [← hTdef, ← hΓ₀def]
  have hx : IsSemiformula LAct 0 x := hxdef ▸ isFormula_instB_quote χ k
  have hq : IsSemiterm LAct (0 : V) (qNum χ) := isSemiterm_qNum χ
  have hbk : IsSemiterm LAct (0 : V) (bnum k) := isSemiterm_bnum_LAct 0 k
  have hTf : IsFormula LAct T := hTdef ▸ isFormula_boxFact hq hbk
  have hΓ₀ : IsFormulaSet LAct Γ₀ := hΓ₀def ▸ IsFormulaSet.insert_iff.mpr ⟨hTf, IsFormulaSet.empty⟩
  have hTmem : T ∈ Γ₀ := by rw [hΓ₀def]; simp
  -- the cap requirements, read off `Etop`
  have hE0 : Etop χ k (dlen TAct ρ) Ck Cχ ≤ E := hE
  have r_walk : eWalk χ k ≤ E := le_trans (le_Etop_walk χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_pin : ePin k Cχ ≤ E := le_trans (le_Etop_pin χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_ver : eVer k (dlen TAct ρ) Ck Cχ ≤ E := le_trans (le_Etop_ver χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_js : eJs k (dlen TAct ρ) Ck Cχ ≤ E := le_trans (le_Etop_js χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_q : eQ χ ≤ E := le_trans (le_Etop_q χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_k : eK k ≤ E := le_trans (le_Etop_k χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_l : eL k ≤ E := le_trans (le_Etop_l χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_b : eB k ≤ E := le_trans (le_Etop_b χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_g : eG k ≤ E := le_trans (le_Etop_g χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_d : eD (dlen TAct ρ) ≤ E := le_trans (le_Etop_d χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_n5 : eN5 k ≤ E := le_trans (le_Etop_n5 χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_n4a : eN4a k ≤ E := le_trans (le_Etop_n4a χ k (dlen TAct ρ) Ck Cχ) hE0
  have r_n4b : eN4b k ≤ E := le_trans (le_Etop_n4b χ k (dlen TAct ρ) Ck Cχ) hE0
  unfold eWalk at r_walk
  rw [← hxdef] at r_walk
  unfold ePin at r_pin
  unfold eVer at r_ver
  unfold eJs at r_js
  unfold eQ at r_q
  unfold eK at r_k
  unfold eL at r_l
  unfold eB at r_b
  unfold eG at r_g
  unfold eD at r_d
  unfold eN5 at r_n5
  unfold eN4a at r_n4a
  unfold eN4b at r_n4b
  have hE1 : (1 : V) ≤ E := le_trans (by norm_num) (le_trans le_add_self r_walk)
  -- (1) the root block
  obtain ⟨rok, rnd, rho, rsh, rlen, rlay⟩ := rootSteps_ok htbl hT hx hΓ₀ r_walk
  set Γ₁ := finalCtx Γ₀ (rootSteps x) with hΓ₁def
  have hΓ₁ : IsFormulaSet LAct Γ₁ := finalCtx_isFormulaSet 8 htbl hΓ₀ rok
  have rB : ∀ i < len (rootSteps x), formulaLen LAct (rowB tbl.[sRow (rootSteps x).[i]]) ≤ B :=
    fun i hi ↦ hB _ (sRow_lt_of_stepOK (rok i hi) (rho i hi))
  have rcost := costSum_le_of_hornOnly hE1 htbl rok rho rB
  obtain ⟨rF, rS⟩ := ctxVec_len_le hE1 htbl rok rho rB (len (rootSteps x)) le_rfl
  have rF' : fvOccS LAct Γ₁ ≤ topF1 B E (fvOccS LAct Γ₀) (len (rootSteps x)) := rF
  have rS' : setLen LAct Γ₁ ≤ topS1 B E (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) := rS
  -- (2) the pin block
  obtain ⟨P, pok, pnd, psh, pinst, pcost, pS, pF⟩ := hpin.pin k (hxdef ▸ rlay) hΓ₁ r_pin
  set Γ₂ := finalCtx Γ₁ P with hΓ₂def
  have hΓ₂ : IsFormulaSet LAct Γ₂ := finalCtx_isFormulaSet 9 htbl hΓ₁ pok
  have lay₂ : RootLayout Γ₂ x (0 + shiftsV P) := rlay.transport pnd
  -- (3) the verification block
  have r_ver' : (Ck : V) * ((dlen TAct ρ) + (0 + shiftsV P) + 1) ≤ E :=
    le_trans (mul_le_mul_of_nonneg_left (add_le_add (add_le_add le_rfl (add_le_add le_rfl psh)) le_rfl) zero_le) r_ver
  obtain ⟨vok, vnd, vsh, vgoal⟩ := hkit.ok hρ lay₂ hΓ₂ r_ver' hL
  obtain ⟨vcost, vS, vF⟩ := hkit.cost hρ lay₂ hΓ₂ r_ver' hL
  set Γ₃ := finalCtx Γ₂ L with hΓ₃def
  have hΓ₃ : IsFormulaSet LAct Γ₃ := finalCtx_isFormulaSet 9 htbl hΓ₂ vok
  have lay₃ : RootLayout Γ₃ x (0 + shiftsV P + shiftsV L) := lay₂.transport vnd
  set js := 0 + shiftsV P + 1 + shiftsV L with hjsdef
  have hins₃ : neg LAct (insFact (^&js) (^&(js + 1)) (𝟎 : V)) ∈ Γ₃ := by
    have := lay₃.2.2.1
    have e1 : (0 : V) + shiftsV P + shiftsV L + 1 = js := by rw [hjsdef]; ring
    have e2 : (0 : V) + shiftsV P + shiftsV L + 2 = js + 1 := by rw [hjsdef]; ring
    rwa [e1, e2] at this
  have hinst₃ : neg LAct (instBFact (^&(js + 1)) (qNum χ) (bnum k)) ∈ Γ₃ := by
    have := mem_finalCtx_of_mem' vnd pinst
    rw [shiftIterV_neg (isFormula_instBFact (by simp) hq hbk), shiftIterV_instBFact (by simp) hq hbk,
      termShiftIterV_fvar, termShiftIterV_qNum, termShiftIterV_bnumTop] at this
    have e : (0 : V) + 2 + shiftsV P + shiftsV L = js + 1 := by rw [hjsdef]; ring
    rwa [e] at this
  -- (4) the closing block
  have r_js' : js + 4 ≤ E := by
    refine le_trans ?_ r_js
    rw [hjsdef]
    calc (0 : V) + shiftsV P + 1 + shiftsV L + 4 ≤ 0 + (Cχ : V) * (‖k‖ + 1) + 1 + (Ck : V) * ((dlen TAct ρ) + 1) + 4 :=
          add_le_add (add_le_add (add_le_add (add_le_add le_rfl psh) le_rfl) vsh) le_rfl
      _ = (Cχ : V) * (‖k‖ + 1) + 1 + (Ck : V) * ((dlen TAct ρ) + 1) + 4 := by rw [zero_add]
  obtain ⟨cok, cnd, csh, clen, cT⟩ := closeSteps_ok χ htbl hT htblN htblL htblM hΓ₃ hlen r_js' r_q r_k r_l r_b r_g r_d
    vgoal hins₃ hinst₃
  set Γ₄ := finalCtx Γ₃ (closeSteps χ k ρ js tblN tblL tblM) with hΓ₄def
  have hΓ₄ : IsFormulaSet LAct Γ₄ := finalCtx_isFormulaSet 8 htbl hΓ₃ cok
  -- the whole list
  set S := topList χ k ρ P L tblN tblL tblM with hSdef
  have h89 : ((8 : ℕ) : V) ≤ ((9 : ℕ) : V) := by exact_mod_cast (by decide : (8 : ℕ) ≤ 9)
  have hSfin : finalCtx Γ₀ S = Γ₄ := by
    rw [hSdef, topList, ← hxdef, ← hjsdef, finalCtx_appendV, finalCtx_appendV, finalCtx_appendV, ← hΓ₁def,
      ← hΓ₂def, ← hΓ₃def]
  have hok : ListOK tbl E ((9 : ℕ) : V) Γ₀ S := by
    rw [hSdef, topList, ← hxdef, ← hjsdef]
    refine listOK_appendV (rok.mono h89) ?_
    rw [← hΓ₁def]
    refine listOK_appendV pok ?_
    rw [← hΓ₂def]
    refine listOK_appendV vok ?_
    rw [← hΓ₃def]
    exact cok.mono h89
  have hnd : NoDrop' S := by
    rw [hSdef, topList, ← hxdef, ← hjsdef]
    exact noDrop'_appendV rnd.noDrop' (noDrop'_appendV pnd (noDrop'_appendV vnd cnd))
  have hT₄ : T ∈ Γ₄ := by
    have := mem_finalCtx_of_mem' hnd hTmem
    rw [hSfin, hTdef, shiftIterV_target] at this
    rw [hTdef]; exact this
  have hnT₄ : neg LAct T ∈ Γ₄ := by rw [hTdef]; exact cT
  -- the leaf and the derivation
  have hleaf : DerivationOf TAct (axL Γ₄ T) Γ₄ := ⟨by simp, Derivation.axL hΓ₄ hT₄ hnT₄⟩
  have hleaf' : DerivationOf TAct (axL Γ₄ T) (ctxVec Γ₀ S).[len S] := by
    show DerivationOf TAct (axL Γ₄ T) (finalCtx Γ₀ S); rw [hSfin]; exact hleaf
  have hdlen_leaf : dlen TAct (axL Γ₄ T) = setLen LAct Γ₄ + 1 :=
    dlen_eq_of_graph hleaf.2 (DlenGraph.axL_iff.mpr rfl)
  have hproof : DerivationOf TAct (chainCode tbl Γ₀ S (axL Γ₄ T)) Γ₀ := chainCode_proof 9 htbl hok hleaf'
  have hcost := dlen_chainCode_le 9 hE1 htbl hok hleaf'
  -- the closing block's cost
  have hgoalLen : formulaLen LAct (goalFact (^&js) (bnum (dlen TAct ρ))) ≤ setLen LAct Γ₃ := by
    have h := formulaLen_le_setLen_of_mem (L := LAct) vgoal
    rwa [formulaLen_neg_eq (isFormula_goalFact (by simp) (isSemiterm_bnum_LAct 0 _))] at h
  set Q := topQ B E Ck Cχ ‖k‖ (dlen TAct ρ) (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) with hQdef
  set D := topD N' B' N₂ B₂ N₃ B₃ k (dlen TAct ρ) with hDdef
  have hS3 : setLen LAct Γ₃ ≤ topS3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) := by
    refine le_trans vS (add_le_add ?_ le_rfl)
    refine le_trans pS (add_le_add rS' le_rfl)
  have hF3 : fvOccS LAct Γ₃ ≤ topF3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (fvOccS LAct Γ₀) (len (rootSteps x)) := by
    refine le_trans vF (add_le_add ?_ le_rfl)
    refine le_trans pF (add_le_add rF' le_rfl)
  have hBE : B * E ≤ Q := by rw [hQdef, topQ]; exact le_add_self
  have hQg : 4 * formulaLen LAct (goalFact (^&js) (bnum (dlen TAct ρ))) ≤ Q := by
    rw [hQdef, topQ]
    exact le_trans (mul_le_mul_of_nonneg_left (le_trans hgoalLen hS3) zero_le) le_self_add
  have hsz : SizeOK Q D (closeSteps χ k ρ js tblN tblL tblM) := by
    unfold closeSteps
    refine sizeOK_appendV ((sizeOK_goalElim (D := D) (by simp) (isSemiterm_bnum_LAct 0 _)).mono hQg le_rfl) ?_
    have hE1' : (1 : V) ≤ E := hE1
    have hbd : IsSemiterm LAct (0 : V) (bnum (dlen TAct ρ)) := isSemiterm_bnum_LAct 0 _
    have hbg : IsSemiterm LAct (0 : V) (bnum (gBudget k)) := isSemiterm_bnum_LAct 0 _
    refine sizeOK_cons (stepSizeOK_sLemma (le_trans (formulaLen_lengthEqFact_le hPl r_n5) hBE)
      (le_trans (dlen_lengthEqCode_le htblN htblL k) (by rw [hDdef, topD]; exact le_trans le_self_add (le_trans le_self_add le_self_add)))) ?_
    refine sizeOK_cons (stepSizeOK_sLemma (le_trans (formulaLen_mulFact_le hPeq r_n4a) hBE)
      (le_trans (dlen_mulEqCode_le htblN htblM _ _) (by rw [hDdef, topD]; exact le_trans le_add_self (le_trans le_self_add le_self_add)))) ?_
    refine sizeOK_cons (stepSizeOK_sLemma (le_trans (formulaLen_mulFact_le hPeq r_n4b) hBE)
      (le_trans (dlen_mulEqCode_le htblN htblM _ _) (by rw [hDdef, topD]; exact le_trans le_add_self le_self_add))) ?_
    refine sizeOK_cons (stepSizeOK_sLemma
      (le_trans (formulaLen_leFact_le hE1' hbd hbg r_d r_g) (le_trans (mul_le_mul_of_nonneg_right hPle zero_le) hBE))
      (le_trans (dlen_leCode_le' htblN hlen) (by rw [hDdef, topD]; exact le_add_self))) ?_
    refine sizeOK_cons (stepSizeOK_horn0 (ttag_dlenDefIntro rfl _)) ?_
    refine sizeOK_cons (stepSizeOK_horn0 (ttag_proofIntro rfl _)) ?_
    refine sizeOK_cons (stepSizeOK_horn0 (ttag_leTrans _)) ?_
    refine sizeOK_cons (stepSizeOK_horn0 (ttag_lenDerIntro rfl _)) ?_
    refine sizeOK_cons (stepSizeOK_horn0 (ttag_gIntroNum rfl _)) ?_
    exact sizeOK_single (stepSizeOK_horn0 (ttag_boxIntro rfl _))
  have ccost := costSum_le_of_sizeOK 8 hE1 htbl hB cok hsz
  rw [clen] at ccost
  obtain ⟨_, cS⟩ := ctxVec_len_le_sizeOK 8 hE1 htbl hB cok hsz (len (closeSteps χ k ρ js tblN tblL tblM)) le_rfl
  have cS' : setLen LAct Γ₄ ≤ setLen LAct Γ₃ + len (closeSteps χ k ρ js tblN tblL tblM) * fvOccS LAct Γ₃ +
      (len (closeSteps χ k ρ js tblN tblL tblM) * len (closeSteps χ k ρ js tblN tblL tblM) +
        len (closeSteps χ k ρ js tblN tblL tblM)) * growK B E Q := cS
  rw [clen] at cS'
  -- the total
  refine ⟨dlen TAct (chainCode tbl Γ₀ S (axL Γ₄ T)), len (rootSteps x), ?_, rlen, ?_⟩
  · refine ⟨chainCode tbl Γ₀ S (axL Γ₄ T), ?_, le_refl (dlen TAct (chainCode tbl Γ₀ S (axL Γ₄ T)))⟩
    rw [target_eq_boxFact, ← hTdef]
    have e : insert T (∅ : V) = {T} := mem_ext fun _ ↦ by simp
    show DerivationOf TAct _ {T}
    rw [← e, ← hΓ₀def]; exact hproof
  · have hsplit : costSum N E Γ₀ S = costSum N E Γ₀ (rootSteps x) +
        (costSum N E Γ₁ P + (costSum N E Γ₂ L + costSum N E Γ₃ (closeSteps χ k ρ js tblN tblL tblM))) := by
      rw [hSdef, topList, ← hxdef, ← hjsdef, costSum_appendV, costSum_appendV, costSum_appendV, ← hΓ₁def, ← hΓ₂def,
        ← hΓ₃def]
    have hS2 : setLen LAct Γ₂ ≤ topS2 B E Cχ ‖k‖ (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) :=
      le_trans pS (add_le_add rS' le_rfl)
    have h_leaf : setLen LAct Γ₄ + 1 ≤ topS3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) +
        15 * topF3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (fvOccS LAct Γ₀) (len (rootSteps x)) + (15 * 15 + 15) * growK B E Q + 1 :=
      add_le_add (le_trans cS' (add_le_add (add_le_add hS3 (mul_le_mul_of_nonneg_left hF3 zero_le)) le_rfl)) le_rfl
    have h_root : costSum N E Γ₀ (rootSteps x) ≤
        len (rootSteps x) * (stepK N E B + 36 * topS1 B E (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x))) := by
      unfold topS1; unfold ctxBound at rcost; exact rcost
    have h_pin : costSum N E Γ₁ P ≤ (Cχ : V) * (‖k‖ + 1) *
        (topS1 B E (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) + N + E + (‖k‖ + 1) ^ 2) :=
      le_trans pcost (mul_le_mul_of_nonneg_left (add_le_add (add_le_add (add_le_add rS' le_rfl) le_rfl) le_rfl) zero_le)
    have h_ver : costSum N E Γ₂ L ≤ (Ck : V) * (dlen TAct ρ + 1) *
        (topS2 B E Cχ ‖k‖ (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) + N + E + (dlen TAct ρ + 1) ^ 2) :=
      le_trans vcost (mul_le_mul_of_nonneg_left (add_le_add (add_le_add (add_le_add hS2 le_rfl) le_rfl) le_rfl) zero_le)
    have h_close : costSum N E Γ₃ (closeSteps χ k ρ js tblN tblL tblM) ≤
        15 * (costK N E B ((8 : ℕ) : V) Q D + (3 * ((8 : ℕ) : V) + 11) *
          ((topS3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (setLen LAct Γ₀) (fvOccS LAct Γ₀) (len (rootSteps x)) +
            15 * topF3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (fvOccS LAct Γ₀) (len (rootSteps x)) + (15 * 15 + 15) * growK B E Q) +
           (topF3 B E Ck Cχ ‖k‖ (dlen TAct ρ) (fvOccS LAct Γ₀) (len (rootSteps x)) + 15 * growK B E Q))) := by
      refine le_trans ccost (mul_le_mul_of_nonneg_left (add_le_add le_rfl (mul_le_mul_of_nonneg_left
        (add_le_add ?_ (add_le_add hF3 le_rfl)) zero_le)) zero_le)
      unfold ctxBoundG
      exact add_le_add (add_le_add hS3 (mul_le_mul_of_nonneg_left hF3 zero_le)) le_rfl
    refine le_trans hcost ?_
    rw [hdlen_leaf, hsplit]
    unfold topBound
    calc setLen LAct Γ₄ + 1 + (costSum N E Γ₀ (rootSteps x) + (costSum N E Γ₁ P +
          (costSum N E Γ₂ L + costSum N E Γ₃ (closeSteps χ k ρ js tblN tblL tblM))))
        = (setLen LAct Γ₄ + 1) + costSum N E Γ₀ (rootSteps x) + costSum N E Γ₁ P + costSum N E Γ₂ L +
          costSum N E Γ₃ (closeSteps χ k ρ js tblN tblL tblM) := by ring
      _ ≤ _ := add_le_add (add_le_add (add_le_add (add_le_add h_leaf h_root) h_pin) h_ver) h_close

end assembly

end ArithS
